//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atdi.Icsm.Plugins.GE06Calc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atdi.Icsm.Plugins.GE06Calc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active context.
        /// </summary>
        public static string ActiveContext {
            get {
                return ResourceManager.GetString("ActiveContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional contours  by distances.
        /// </summary>
        public static string AdditionalContoursByDistances {
            get {
                return ResourceManager.GetString("AdditionalContoursByDistances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adm.
        /// </summary>
        public static string Adm {
            get {
                return ResourceManager.GetString("Adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdmRefId.
        /// </summary>
        public static string AdmRefId {
            get {
                return ResourceManager.GetString("AdmRefId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected ADM.
        /// </summary>
        public static string AffectedADM {
            get {
                return ResourceManager.GetString("AffectedADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected services.
        /// </summary>
        public static string AffectedServices {
            get {
                return ResourceManager.GetString("AffectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AglHeight m.
        /// </summary>
        public static string AglHeight_m {
            get {
                return ResourceManager.GetString("AglHeight_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt m.
        /// </summary>
        public static string Alt_m {
            get {
                return ResourceManager.GetString("Alt_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna directional.
        /// </summary>
        public static string AntennaDirectional {
            get {
                return ResourceManager.GetString("AntennaDirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth step.
        /// </summary>
        public static string AzimuthStep {
            get {
                return ResourceManager.GetString("AzimuthStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base context.
        /// </summary>
        public static string BaseContext {
            get {
                return ResourceManager.GetString("BaseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base contexts.
        /// </summary>
        public static string BaseContexts {
            get {
                return ResourceManager.GetString("BaseContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client contexts.
        /// </summary>
        public static string ClientContexts {
            get {
                return ResourceManager.GetString("ClientContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformity Check Ann. 4 Sec II.
        /// </summary>
        public static string ConformityCheck {
            get {
                return ResourceManager.GetString("ConformityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contours.
        /// </summary>
        public static string Contoures {
            get {
                return ResourceManager.GetString("Contoures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contours points.
        /// </summary>
        public static string ContoursPoints {
            get {
                return ResourceManager.GetString("ContoursPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour type.
        /// </summary>
        public static string ContourType {
            get {
                return ResourceManager.GetString("ContourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conture by field strength.
        /// </summary>
        public static string ContureByFieldStrength {
            get {
                return ResourceManager.GetString("ContureByFieldStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create contours by distance (conformity file for HTZ).
        /// </summary>
        public static string CreateContoursByDistance {
            get {
                return ResourceManager.GetString("CreateContoursByDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create contours by FS.
        /// </summary>
        public static string CreateContoursByFS {
            get {
                return ResourceManager.GetString("CreateContoursByFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErpH_dBW.
        /// </summary>
        public static string ErpH_dBW {
            get {
                return ResourceManager.GetString("ErpH_dBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErpV_dBW.
        /// </summary>
        public static string ErpV_dBW {
            get {
                return ResourceManager.GetString("ErpV_dBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to HTZ.
        /// </summary>
        public static string ExportToHTZ {
            get {
                return ResourceManager.GetString("ExportToHTZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find affected ADM Ann. 4 Sec. I.
        /// </summary>
        public static string FindAffected {
            get {
                return ResourceManager.GetString("FindAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq_MHz.
        /// </summary>
        public static string Freq_MHz {
            get {
                return ResourceManager.GetString("Freq_MHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FS.
        /// </summary>
        public static string FS {
            get {
                return ResourceManager.GetString("FS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat Dec.
        /// </summary>
        public static string Lat_Dec {
            get {
                return ResourceManager.GetString("Lat_Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lon Dec.
        /// </summary>
        public static string Lon_Dec {
            get {
                return ResourceManager.GetString("Lon_Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map name.
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxEffHeight m.
        /// </summary>
        public static string MaxEffHeight_m {
            get {
                return ResourceManager.GetString("MaxEffHeight_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner instance.
        /// </summary>
        public static string OwnerInstance {
            get {
                return ResourceManager.GetString("OwnerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage time.
        /// </summary>
        public static string PercentageTime {
            get {
                return ResourceManager.GetString("PercentageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanEntry.
        /// </summary>
        public static string PlanEntry {
            get {
                return ResourceManager.GetString("PlanEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points count.
        /// </summary>
        public static string PointsCount {
            get {
                return ResourceManager.GetString("PointsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar.
        /// </summary>
        public static string Polar {
            get {
                return ResourceManager.GetString("Polar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare context.
        /// </summary>
        public static string PrepareContext {
            get {
                return ResourceManager.GetString("PrepareContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared.
        /// </summary>
        public static string Prepared {
            get {
                return ResourceManager.GetString("Prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection.
        /// </summary>
        public static string Projection {
            get {
                return ResourceManager.GetString("Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefNetworkConfig.
        /// </summary>
        public static string RefNetworkConfig {
            get {
                return ResourceManager.GetString("RefNetworkConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SfnId.
        /// </summary>
        public static string SfnId {
            get {
                return ResourceManager.GetString("SfnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Result.
        /// </summary>
        public static string ShowResult {
            get {
                return ResourceManager.GetString("ShowResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations and allotments.
        /// </summary>
        public static string StationsAndAllotments {
            get {
                return ResourceManager.GetString("StationsAndAllotments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status name.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status note.
        /// </summary>
        public static string StatusNote {
            get {
                return ResourceManager.GetString("StatusNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step between boundary points.
        /// </summary>
        public static string StepBetweenBoundaryPoints {
            get {
                return ResourceManager.GetString("StepBetweenBoundaryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers height.
        /// </summary>
        public static string SubscribersHeight {
            get {
                return ResourceManager.GetString("SubscribersHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type affected.
        /// </summary>
        public static string TypeAffected {
            get {
                return ResourceManager.GetString("TypeAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of calculation.
        /// </summary>
        public static string TypeOfCalculation {
            get {
                return ResourceManager.GetString("TypeOfCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use effective height.
        /// </summary>
        public static string UseEffectiveHeight {
            get {
                return ResourceManager.GetString("UseEffectiveHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewName.
        /// </summary>
        public static string ViewName {
            get {
                return ResourceManager.GetString("ViewName", resourceCulture);
            }
        }
    }
}
