//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atdi.Icsm.Plugins.SdrnStationCalibrationCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atdi.Icsm.Plugins.SdrnStationCalibrationCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude Station.
        /// </summary>
        public static string AltitudeStation {
            get {
                return ResourceManager.GetString("AltitudeStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area name.
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth Station.
        /// </summary>
        public static string AzimuthStation {
            get {
                return ResourceManager.GetString("AzimuthStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Context.
        /// </summary>
        public static string BaseContext {
            get {
                return ResourceManager.GetString("BaseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Contexts.
        /// </summary>
        public static string BaseContexts {
            get {
                return ResourceManager.GetString("BaseContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc Correlation.
        /// </summary>
        public static string CalcCorrelation {
            get {
                return ResourceManager.GetString("CalcCorrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration parameter.
        /// </summary>
        public static string CalibrationParameter {
            get {
                return ResourceManager.GetString("CalibrationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration result Id.
        /// </summary>
        public static string CalibrationResultId {
            get {
                return ResourceManager.GetString("CalibrationResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascade tuning.
        /// </summary>
        public static string CascadeTuning {
            get {
                return ResourceManager.GetString("CascadeTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contexts.
        /// </summary>
        public static string Contexts {
            get {
                return ResourceManager.GetString("Contexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates  Station.
        /// </summary>
        public static string CoordinatesStation {
            get {
                return ResourceManager.GetString("CoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation distance, m.
        /// </summary>
        public static string CorrelationDistance {
            get {
                return ResourceManager.GetString("CorrelationDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation threshold hard, %.
        /// </summary>
        public static string CorrelationThresholdHard {
            get {
                return ResourceManager.GetString("CorrelationThresholdHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation threshold weak, %.
        /// </summary>
        public static string CorrelationThresholdWeak {
            get {
                return ResourceManager.GetString("CorrelationThresholdWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count meas GSID.
        /// </summary>
        public static string CountMeasGSID {
            get {
                return ResourceManager.GetString("CountMeasGSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountMeasGSID in IT status.
        /// </summary>
        public static string CountMeasGSID_IT {
            get {
                return ResourceManager.GetString("CountMeasGSID_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountMeasGSID in LS status.
        /// </summary>
        public static string CountMeasGSID_LS {
            get {
                return ResourceManager.GetString("CountMeasGSID_LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count points in drive test.
        /// </summary>
        public static string CountPointsInDriveTest {
            get {
                return ResourceManager.GetString("CountPointsInDriveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountStation in CS status.
        /// </summary>
        public static string CountStation_CS {
            get {
                return ResourceManager.GetString("CountStation_CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count station in IT status.
        /// </summary>
        public static string CountStation_IT {
            get {
                return ResourceManager.GetString("CountStation_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count station in UN status.
        /// </summary>
        public static string CountStation_NF {
            get {
                return ResourceManager.GetString("CountStation_NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count station in NS status.
        /// </summary>
        public static string CountStation_NS {
            get {
                return ResourceManager.GetString("CountStation_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count station in UN status.
        /// </summary>
        public static string CountStation_UN {
            get {
                return ResourceManager.GetString("CountStation_UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta, dB.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of cascade.
        /// </summary>
        public static string DetailOfCascade {
            get {
                return ResourceManager.GetString("DetailOfCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance around contour, km.
        /// </summary>
        public static string DistanceAroundContour {
            get {
                return ResourceManager.GetString("DistanceAroundContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive test block.
        /// </summary>
        public static string DriveTestBlock {
            get {
                return ResourceManager.GetString("DriveTestBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive test Id.
        /// </summary>
        public static string DriveTestId {
            get {
                return ResourceManager.GetString("DriveTestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External code.
        /// </summary>
        public static string ExternalCode {
            get {
                return ResourceManager.GetString("ExternalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External source.
        /// </summary>
        public static string ExternalSource {
            get {
                return ResourceManager.GetString("ExternalSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Gsid.
        /// </summary>
        public static string LicenseGsid {
            get {
                return ResourceManager.GetString("LicenseGsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Name.
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max antennas pattern loss, dB.
        /// </summary>
        public static string MaxAntennasPatternLoss {
            get {
                return ResourceManager.GetString("MaxAntennasPatternLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum corellation.
        /// </summary>
        public static string MaxCorellation {
            get {
                return ResourceManager.GetString("MaxCorellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max deviation Altitude Station, m.
        /// </summary>
        public static string MaxDeviationAltitudeStation {
            get {
                return ResourceManager.GetString("MaxDeviationAltitudeStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max deviation Azimuth Station, deg.
        /// </summary>
        public static string MaxDeviationAzimuthStation {
            get {
                return ResourceManager.GetString("MaxDeviationAzimuthStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Coordinates  Station Step, m.
        /// </summary>
        public static string MaxDeviationCoordinatesStation {
            get {
                return ResourceManager.GetString("MaxDeviationCoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max deviation Tilt Station, deg.
        /// </summary>
        public static string MaxDeviationTiltStation {
            get {
                return ResourceManager.GetString("MaxDeviationTiltStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum percent corellation.
        /// </summary>
        public static string MaxPercentCorellation {
            get {
                return ResourceManager.GetString("MaxPercentCorellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max range measurements, dBmkV/m.
        /// </summary>
        public static string MaxRangeMeasurements {
            get {
                return ResourceManager.GetString("MaxRangeMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements from.
        /// </summary>
        public static string MeasurementsFrom {
            get {
                return ResourceManager.GetString("MeasurementsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min number point for correlation.
        /// </summary>
        public static string MinNumberPointForCorrelation {
            get {
                return ResourceManager.GetString("MinNumberPointForCorrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min range measurements, dBmkV/m.
        /// </summary>
        public static string MinRangeMeasurements {
            get {
                return ResourceManager.GetString("MinRangeMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New altitude, m.
        /// </summary>
        public static string New_Altitude_m {
            get {
                return ResourceManager.GetString("New_Altitude_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New azimuth, deg.
        /// </summary>
        public static string New_Azimuth_deg {
            get {
                return ResourceManager.GetString("New_Azimuth_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New freq, MHz.
        /// </summary>
        public static string New_Freq_MHz {
            get {
                return ResourceManager.GetString("New_Freq_MHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New lat, deg.
        /// </summary>
        public static string New_Lat_deg {
            get {
                return ResourceManager.GetString("New_Lat_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New lon, deg.
        /// </summary>
        public static string New_Lon_deg {
            get {
                return ResourceManager.GetString("New_Lon_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New power,  dB.
        /// </summary>
        public static string New_Power_dB {
            get {
                return ResourceManager.GetString("New_Power_dB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tilt, deg.
        /// </summary>
        public static string New_Tilt_deg {
            get {
                return ResourceManager.GetString("New_Tilt_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cascade.
        /// </summary>
        public static string NumberCascade {
            get {
                return ResourceManager.GetString("NumberCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number station.
        /// </summary>
        public static string NumberStation {
            get {
                return ResourceManager.GetString("NumberStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number station in contour.
        /// </summary>
        public static string NumberStationInContour {
            get {
                return ResourceManager.GetString("NumberStationInContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old altitude, m.
        /// </summary>
        public static string Old_Altitude_m {
            get {
                return ResourceManager.GetString("Old_Altitude_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old azimuth, deg.
        /// </summary>
        public static string Old_Azimuth_deg {
            get {
                return ResourceManager.GetString("Old_Azimuth_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old lat, deg.
        /// </summary>
        public static string Old_Lat_deg {
            get {
                return ResourceManager.GetString("Old_Lat_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old lon, deg.
        /// </summary>
        public static string Old_Lon_deg {
            get {
                return ResourceManager.GetString("Old_Lon_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old power, dB.
        /// </summary>
        public static string Old_Power_dB {
            get {
                return ResourceManager.GetString("Old_Power_dB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old tilt, deg.
        /// </summary>
        public static string Old_Tilt_deg {
            get {
                return ResourceManager.GetString("Old_Tilt_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old freq, MHz.
        /// </summary>
        public static string OldFreq_MHz {
            get {
                return ResourceManager.GetString("OldFreq_MHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Instance.
        /// </summary>
        public static string OwnerInstance {
            get {
                return ResourceManager.GetString("OwnerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters of task.
        /// </summary>
        public static string ParametersOfTask {
            get {
                return ResourceManager.GetString("ParametersOfTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Station.
        /// </summary>
        public static string PowerStation {
            get {
                return ResourceManager.GetString("PowerStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection.
        /// </summary>
        public static string Projection {
            get {
                return ResourceManager.GetString("Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Gsid.
        /// </summary>
        public static string RealGsid {
            get {
                return ResourceManager.GetString("RealGsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result drive test status.
        /// </summary>
        public static string ResultDriveTestStatus {
            get {
                return ResourceManager.GetString("ResultDriveTestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Altitude Station Max, m.
        /// </summary>
        public static string ShiftAltitudeStationMax {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Altitude Station Min, m.
        /// </summary>
        public static string ShiftAltitudeStationMin {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Altitude Station Step, m.
        /// </summary>
        public static string ShiftAltitudeStationStep {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Azimuth Station Max, deg.
        /// </summary>
        public static string ShiftAzimuthStationMax {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Azimuth Station Min, deg.
        /// </summary>
        public static string ShiftAzimuthStationMin {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Azimuth Station Step, deg.
        /// </summary>
        public static string ShiftAzimuthStationStep {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Coordinates  Station, m.
        /// </summary>
        public static string ShiftCoordinatesStation {
            get {
                return ResourceManager.GetString("ShiftCoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift coordinates station step, m.
        /// </summary>
        public static string ShiftCoordinatesStationStep {
            get {
                return ResourceManager.GetString("ShiftCoordinatesStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Power Station Max, dB.
        /// </summary>
        public static string ShiftPowerStationMax {
            get {
                return ResourceManager.GetString("ShiftPowerStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Power Station Min, dB.
        /// </summary>
        public static string ShiftPowerStationMin {
            get {
                return ResourceManager.GetString("ShiftPowerStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Power Station Step, dB.
        /// </summary>
        public static string ShiftPowerStationStep {
            get {
                return ResourceManager.GetString("ShiftPowerStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Tilt Station Max, deg.
        /// </summary>
        public static string ShiftTiltStationMax {
            get {
                return ResourceManager.GetString("ShiftTiltStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Tilt Station Min, deg.
        /// </summary>
        public static string ShiftTiltStationMin {
            get {
                return ResourceManager.GetString("ShiftTiltStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Tilt Station Step, deg.
        /// </summary>
        public static string ShiftTiltStationStep {
            get {
                return ResourceManager.GetString("ShiftTiltStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show result.
        /// </summary>
        public static string ShowResult {
            get {
                return ResourceManager.GetString("ShowResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start calc.
        /// </summary>
        public static string StartCalc {
            get {
                return ResourceManager.GetString("StartCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State for active station.
        /// </summary>
        public static string StateForActiveStation {
            get {
                return ResourceManager.GetString("StateForActiveStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State for not active station.
        /// </summary>
        public static string StateForNotActiveStation {
            get {
                return ResourceManager.GetString("StateForNotActiveStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations block.
        /// </summary>
        public static string StationsBlock {
            get {
                return ResourceManager.GetString("StationsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Note.
        /// </summary>
        public static string StatusNote {
            get {
                return ResourceManager.GetString("StatusNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Station.
        /// </summary>
        public static string TiltStation {
            get {
                return ResourceManager.GetString("TiltStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time start.
        /// </summary>
        public static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust old results.
        /// </summary>
        public static string TrustOldResults {
            get {
                return ResourceManager.GetString("TrustOldResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the area.
        /// </summary>
        public static string TypeOfArea {
            get {
                return ResourceManager.GetString("TypeOfArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use measurement with same GSID.
        /// </summary>
        public static string UseMeasurementSameGSID {
            get {
                return ResourceManager.GetString("UseMeasurementSameGSID", resourceCulture);
            }
        }
    }
}
