//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atdi.Icsm.Plugins.SdrnStationCalibrationCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atdi.Icsm.Plugins.SdrnStationCalibrationCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Altitude Station.
        /// </summary>
        public static string AltitudeStation {
            get {
                return ResourceManager.GetString("AltitudeStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Azimuth Station.
        /// </summary>
        public static string AzimuthStation {
            get {
                return ResourceManager.GetString("AzimuthStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calc Correlation.
        /// </summary>
        public static string CalcCorrelation {
            get {
                return ResourceManager.GetString("CalcCorrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibration parameter.
        /// </summary>
        public static string CalibrationParameter {
            get {
                return ResourceManager.GetString("CalibrationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cascade tuning.
        /// </summary>
        public static string CascadeTuning {
            get {
                return ResourceManager.GetString("CascadeTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coordinates  Station.
        /// </summary>
        public static string CoordinatesStation {
            get {
                return ResourceManager.GetString("CoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correlation distance.
        /// </summary>
        public static string CorrelationDistance {
            get {
                return ResourceManager.GetString("CorrelationDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correlation threshold hard.
        /// </summary>
        public static string CorrelationThresholdHard {
            get {
                return ResourceManager.GetString("CorrelationThresholdHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correlation threshold weak.
        /// </summary>
        public static string CorrelationThresholdWeak {
            get {
                return ResourceManager.GetString("CorrelationThresholdWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created by.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date Created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delta.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detail of cascade.
        /// </summary>
        public static string DetailOfCascade {
            get {
                return ResourceManager.GetString("DetailOfCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance around contour.
        /// </summary>
        public static string DistanceAroundContour {
            get {
                return ResourceManager.GetString("DistanceAroundContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive test block.
        /// </summary>
        public static string DriveTestBlock {
            get {
                return ResourceManager.GetString("DriveTestBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max antennas pattern loss.
        /// </summary>
        public static string MaxAntennasPatternLoss {
            get {
                return ResourceManager.GetString("MaxAntennasPatternLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max deviation Altitude Station.
        /// </summary>
        public static string MaxDeviationAltitudeStation {
            get {
                return ResourceManager.GetString("MaxDeviationAltitudeStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max deviation Azimuth Station.
        /// </summary>
        public static string MaxDeviationAzimuthStation {
            get {
                return ResourceManager.GetString("MaxDeviationAzimuthStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Coordinates  Station Step.
        /// </summary>
        public static string MaxDeviationCoordinatesStation {
            get {
                return ResourceManager.GetString("MaxDeviationCoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max deviation Tilt Station.
        /// </summary>
        public static string MaxDeviationTiltStation {
            get {
                return ResourceManager.GetString("MaxDeviationTiltStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max range measurements.
        /// </summary>
        public static string MaxRangeMeasurements {
            get {
                return ResourceManager.GetString("MaxRangeMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measurements from.
        /// </summary>
        public static string MeasurementsFrom {
            get {
                return ResourceManager.GetString("MeasurementsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min number point for correlation.
        /// </summary>
        public static string MinNumberPointForCorrelation {
            get {
                return ResourceManager.GetString("MinNumberPointForCorrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min range measurements.
        /// </summary>
        public static string MinRangeMeasurements {
            get {
                return ResourceManager.GetString("MinRangeMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number cascade.
        /// </summary>
        public static string NumberCascade {
            get {
                return ResourceManager.GetString("NumberCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters of task.
        /// </summary>
        public static string ParametersOfTask {
            get {
                return ResourceManager.GetString("ParametersOfTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power Station.
        /// </summary>
        public static string PowerStation {
            get {
                return ResourceManager.GetString("PowerStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Altitude Station Max.
        /// </summary>
        public static string ShiftAltitudeStationMax {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Altitude Station Min.
        /// </summary>
        public static string ShiftAltitudeStationMin {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Altitude Station Step.
        /// </summary>
        public static string ShiftAltitudeStationStep {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Azimuth Station Max.
        /// </summary>
        public static string ShiftAzimuthStationMax {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Azimuth Station Min.
        /// </summary>
        public static string ShiftAzimuthStationMin {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Azimuth Station Step.
        /// </summary>
        public static string ShiftAzimuthStationStep {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Coordinates  Station.
        /// </summary>
        public static string ShiftCoordinatesStation {
            get {
                return ResourceManager.GetString("ShiftCoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Power Station Max.
        /// </summary>
        public static string ShiftPowerStationMax {
            get {
                return ResourceManager.GetString("ShiftPowerStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Power Station Min.
        /// </summary>
        public static string ShiftPowerStationMin {
            get {
                return ResourceManager.GetString("ShiftPowerStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Power Station Step.
        /// </summary>
        public static string ShiftPowerStationStep {
            get {
                return ResourceManager.GetString("ShiftPowerStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Tilt Station Max.
        /// </summary>
        public static string ShiftTiltStationMax {
            get {
                return ResourceManager.GetString("ShiftTiltStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Tilt Station Min.
        /// </summary>
        public static string ShiftTiltStationMin {
            get {
                return ResourceManager.GetString("ShiftTiltStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Tilt Station Step.
        /// </summary>
        public static string ShiftTiltStationStep {
            get {
                return ResourceManager.GetString("ShiftTiltStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State for active station.
        /// </summary>
        public static string StateForActiveStation {
            get {
                return ResourceManager.GetString("StateForActiveStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State for not active station.
        /// </summary>
        public static string StateForNotActiveStation {
            get {
                return ResourceManager.GetString("StateForNotActiveStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stations block.
        /// </summary>
        public static string StationsBlock {
            get {
                return ResourceManager.GetString("StationsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tilt Station.
        /// </summary>
        public static string TiltStation {
            get {
                return ResourceManager.GetString("TiltStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trust old results.
        /// </summary>
        public static string TrustOldResults {
            get {
                return ResourceManager.GetString("TrustOldResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of the area.
        /// </summary>
        public static string TypeOfArea {
            get {
                return ResourceManager.GetString("TypeOfArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use measurement with same GSID.
        /// </summary>
        public static string UseMeasurementSameGSID {
            get {
                return ResourceManager.GetString("UseMeasurementSameGSID", resourceCulture);
            }
        }
    }
}
