//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atdi.Icsm.Plugins.SdrnStationCalibrationCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atdi.Icsm.Plugins.SdrnStationCalibrationCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Altitude Station.
        /// </summary>
        public static string AltitudeStation {
            get {
                return ResourceManager.GetString("AltitudeStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area name.
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Azimuth Station.
        /// </summary>
        public static string AzimuthStation {
            get {
                return ResourceManager.GetString("AzimuthStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base Contexts.
        /// </summary>
        public static string BaseContexts {
            get {
                return ResourceManager.GetString("BaseContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calc Correlation.
        /// </summary>
        public static string CalcCorrelation {
            get {
                return ResourceManager.GetString("CalcCorrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibration parameter.
        /// </summary>
        public static string CalibrationParameter {
            get {
                return ResourceManager.GetString("CalibrationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calibration result Id.
        /// </summary>
        public static string CalibrationResultId {
            get {
                return ResourceManager.GetString("CalibrationResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cascade tuning.
        /// </summary>
        public static string CascadeTuning {
            get {
                return ResourceManager.GetString("CascadeTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contexts.
        /// </summary>
        public static string Contexts {
            get {
                return ResourceManager.GetString("Contexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coordinates  Station.
        /// </summary>
        public static string CoordinatesStation {
            get {
                return ResourceManager.GetString("CoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correlation distance, m.
        /// </summary>
        public static string CorrelationDistance {
            get {
                return ResourceManager.GetString("CorrelationDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correlation threshold hard, %.
        /// </summary>
        public static string CorrelationThresholdHard {
            get {
                return ResourceManager.GetString("CorrelationThresholdHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correlation threshold weak, %.
        /// </summary>
        public static string CorrelationThresholdWeak {
            get {
                return ResourceManager.GetString("CorrelationThresholdWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count meas GSID.
        /// </summary>
        public static string CountMeasGSID {
            get {
                return ResourceManager.GetString("CountMeasGSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CountMeasGSID in IT status.
        /// </summary>
        public static string CountMeasGSID_IT {
            get {
                return ResourceManager.GetString("CountMeasGSID_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CountMeasGSID in LS status.
        /// </summary>
        public static string CountMeasGSID_LS {
            get {
                return ResourceManager.GetString("CountMeasGSID_LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count points in drive test.
        /// </summary>
        public static string CountPointsInDriveTest {
            get {
                return ResourceManager.GetString("CountPointsInDriveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CountStation in CS status.
        /// </summary>
        public static string CountStation_CS {
            get {
                return ResourceManager.GetString("CountStation_CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count station in IT status.
        /// </summary>
        public static string CountStation_IT {
            get {
                return ResourceManager.GetString("CountStation_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count station in UN status.
        /// </summary>
        public static string CountStation_NF {
            get {
                return ResourceManager.GetString("CountStation_NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count station in NS status.
        /// </summary>
        public static string CountStation_NS {
            get {
                return ResourceManager.GetString("CountStation_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count station in UN status.
        /// </summary>
        public static string CountStation_UN {
            get {
                return ResourceManager.GetString("CountStation_UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created by.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date Created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delta, dB.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detail of cascade.
        /// </summary>
        public static string DetailOfCascade {
            get {
                return ResourceManager.GetString("DetailOfCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance around contour, km.
        /// </summary>
        public static string DistanceAroundContour {
            get {
                return ResourceManager.GetString("DistanceAroundContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive test block.
        /// </summary>
        public static string DriveTestBlock {
            get {
                return ResourceManager.GetString("DriveTestBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive test Id.
        /// </summary>
        public static string DriveTestId {
            get {
                return ResourceManager.GetString("DriveTestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External code.
        /// </summary>
        public static string ExternalCode {
            get {
                return ResourceManager.GetString("ExternalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External source.
        /// </summary>
        public static string ExternalSource {
            get {
                return ResourceManager.GetString("ExternalSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Gsid.
        /// </summary>
        public static string LicenseGsid {
            get {
                return ResourceManager.GetString("LicenseGsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map Name.
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max antennas pattern loss, dB.
        /// </summary>
        public static string MaxAntennasPatternLoss {
            get {
                return ResourceManager.GetString("MaxAntennasPatternLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum corellation.
        /// </summary>
        public static string MaxCorellation {
            get {
                return ResourceManager.GetString("MaxCorellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max deviation Altitude Station, m.
        /// </summary>
        public static string MaxDeviationAltitudeStation {
            get {
                return ResourceManager.GetString("MaxDeviationAltitudeStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max deviation Azimuth Station, deg.
        /// </summary>
        public static string MaxDeviationAzimuthStation {
            get {
                return ResourceManager.GetString("MaxDeviationAzimuthStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Coordinates  Station Step, m.
        /// </summary>
        public static string MaxDeviationCoordinatesStation {
            get {
                return ResourceManager.GetString("MaxDeviationCoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max deviation Tilt Station, deg.
        /// </summary>
        public static string MaxDeviationTiltStation {
            get {
                return ResourceManager.GetString("MaxDeviationTiltStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum percent corellation.
        /// </summary>
        public static string MaxPercentCorellation {
            get {
                return ResourceManager.GetString("MaxPercentCorellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max range measurements, dBmkV/m.
        /// </summary>
        public static string MaxRangeMeasurements {
            get {
                return ResourceManager.GetString("MaxRangeMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measurements from.
        /// </summary>
        public static string MeasurementsFrom {
            get {
                return ResourceManager.GetString("MeasurementsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min number point for correlation.
        /// </summary>
        public static string MinNumberPointForCorrelation {
            get {
                return ResourceManager.GetString("MinNumberPointForCorrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min range measurements, dBmkV/m.
        /// </summary>
        public static string MinRangeMeasurements {
            get {
                return ResourceManager.GetString("MinRangeMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New altitude, m.
        /// </summary>
        public static string New_Altitude_m {
            get {
                return ResourceManager.GetString("New_Altitude_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New azimuth, deg.
        /// </summary>
        public static string New_Azimuth_deg {
            get {
                return ResourceManager.GetString("New_Azimuth_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New freq, MHz.
        /// </summary>
        public static string New_Freq_MHz {
            get {
                return ResourceManager.GetString("New_Freq_MHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New lat, deg.
        /// </summary>
        public static string New_Lat_deg {
            get {
                return ResourceManager.GetString("New_Lat_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New lon, deg.
        /// </summary>
        public static string New_Lon_deg {
            get {
                return ResourceManager.GetString("New_Lon_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New power,  dB.
        /// </summary>
        public static string New_Power_dB {
            get {
                return ResourceManager.GetString("New_Power_dB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New tilt, deg.
        /// </summary>
        public static string New_Tilt_deg {
            get {
                return ResourceManager.GetString("New_Tilt_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number cascade.
        /// </summary>
        public static string NumberCascade {
            get {
                return ResourceManager.GetString("NumberCascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number station.
        /// </summary>
        public static string NumberStation {
            get {
                return ResourceManager.GetString("NumberStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number station in contour.
        /// </summary>
        public static string NumberStationInContour {
            get {
                return ResourceManager.GetString("NumberStationInContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old altitude, m.
        /// </summary>
        public static string Old_Altitude_m {
            get {
                return ResourceManager.GetString("Old_Altitude_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old azimuth, deg.
        /// </summary>
        public static string Old_Azimuth_deg {
            get {
                return ResourceManager.GetString("Old_Azimuth_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old lat, deg.
        /// </summary>
        public static string Old_Lat_deg {
            get {
                return ResourceManager.GetString("Old_Lat_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old lon, deg.
        /// </summary>
        public static string Old_Lon_deg {
            get {
                return ResourceManager.GetString("Old_Lon_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old power, dB.
        /// </summary>
        public static string Old_Power_dB {
            get {
                return ResourceManager.GetString("Old_Power_dB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old tilt, deg.
        /// </summary>
        public static string Old_Tilt_deg {
            get {
                return ResourceManager.GetString("Old_Tilt_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old freq, MHz.
        /// </summary>
        public static string OldFreq_MHz {
            get {
                return ResourceManager.GetString("OldFreq_MHz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Owner Instance.
        /// </summary>
        public static string OwnerInstance {
            get {
                return ResourceManager.GetString("OwnerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters of task.
        /// </summary>
        public static string ParametersOfTask {
            get {
                return ResourceManager.GetString("ParametersOfTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power Station.
        /// </summary>
        public static string PowerStation {
            get {
                return ResourceManager.GetString("PowerStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Projection.
        /// </summary>
        public static string Projection {
            get {
                return ResourceManager.GetString("Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Real Gsid.
        /// </summary>
        public static string RealGsid {
            get {
                return ResourceManager.GetString("RealGsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result drive test status.
        /// </summary>
        public static string ResultDriveTestStatus {
            get {
                return ResourceManager.GetString("ResultDriveTestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Altitude Station Max, m.
        /// </summary>
        public static string ShiftAltitudeStationMax {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Altitude Station Min, m.
        /// </summary>
        public static string ShiftAltitudeStationMin {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Altitude Station Step, m.
        /// </summary>
        public static string ShiftAltitudeStationStep {
            get {
                return ResourceManager.GetString("ShiftAltitudeStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Azimuth Station Max, deg.
        /// </summary>
        public static string ShiftAzimuthStationMax {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Azimuth Station Min, deg.
        /// </summary>
        public static string ShiftAzimuthStationMin {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Azimuth Station Step, deg.
        /// </summary>
        public static string ShiftAzimuthStationStep {
            get {
                return ResourceManager.GetString("ShiftAzimuthStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Coordinates  Station, m.
        /// </summary>
        public static string ShiftCoordinatesStation {
            get {
                return ResourceManager.GetString("ShiftCoordinatesStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift coordinates station step, m.
        /// </summary>
        public static string ShiftCoordinatesStationStep {
            get {
                return ResourceManager.GetString("ShiftCoordinatesStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Power Station Max, dB.
        /// </summary>
        public static string ShiftPowerStationMax {
            get {
                return ResourceManager.GetString("ShiftPowerStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Power Station Min, dB.
        /// </summary>
        public static string ShiftPowerStationMin {
            get {
                return ResourceManager.GetString("ShiftPowerStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Power Station Step, dB.
        /// </summary>
        public static string ShiftPowerStationStep {
            get {
                return ResourceManager.GetString("ShiftPowerStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Tilt Station Max, deg.
        /// </summary>
        public static string ShiftTiltStationMax {
            get {
                return ResourceManager.GetString("ShiftTiltStationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Tilt Station Min, deg.
        /// </summary>
        public static string ShiftTiltStationMin {
            get {
                return ResourceManager.GetString("ShiftTiltStationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shift Tilt Station Step, deg.
        /// </summary>
        public static string ShiftTiltStationStep {
            get {
                return ResourceManager.GetString("ShiftTiltStationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show result.
        /// </summary>
        public static string ShowResult {
            get {
                return ResourceManager.GetString("ShowResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start calc.
        /// </summary>
        public static string StartCalc {
            get {
                return ResourceManager.GetString("StartCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State for active station.
        /// </summary>
        public static string StateForActiveStation {
            get {
                return ResourceManager.GetString("StateForActiveStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State for not active station.
        /// </summary>
        public static string StateForNotActiveStation {
            get {
                return ResourceManager.GetString("StateForNotActiveStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stations block.
        /// </summary>
        public static string StationsBlock {
            get {
                return ResourceManager.GetString("StationsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status Name.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status Note.
        /// </summary>
        public static string StatusNote {
            get {
                return ResourceManager.GetString("StatusNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tilt Station.
        /// </summary>
        public static string TiltStation {
            get {
                return ResourceManager.GetString("TiltStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time start.
        /// </summary>
        public static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trust old results.
        /// </summary>
        public static string TrustOldResults {
            get {
                return ResourceManager.GetString("TrustOldResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type Name.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of the area.
        /// </summary>
        public static string TypeOfArea {
            get {
                return ResourceManager.GetString("TypeOfArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use measurement with same GSID.
        /// </summary>
        public static string UseMeasurementSameGSID {
            get {
                return ResourceManager.GetString("UseMeasurementSameGSID", resourceCulture);
            }
        }
    }
}
