use ICSM_DB_148;
GO
INSERT INTO XUPDATEOBJECTS(ID,OBJTABLE,DATEMODIFIED) VALUES(1,'XWEBCONSTRAINT',NULL)
INSERT INTO XUPDATEOBJECTS(ID,OBJTABLE,DATEMODIFIED) VALUES(2,'XWEBQUERY',NULL)
INSERT INTO XUPDATEOBJECTS(ID,OBJTABLE,DATEMODIFIED) VALUES(3,'TASKFORCE',NULL)
INSERT INTO XUPDATEOBJECTS(ID,OBJTABLE,DATEMODIFIED) VALUES(4,'TSKF_MEMBER',NULL)
INSERT INTO XUPDATEOBJECTS(ID,OBJTABLE,DATEMODIFIED) VALUES(5,'XWEBQUERYATTRIBUTES',NULL)
INSERT INTO XUPDATEOBJECTS(ID,OBJTABLE,DATEMODIFIED) VALUES(6,'XWEBQUERYORDERS',NULL)
