use ICSM_DB_148;
GO

CREATE TRIGGER TASKFORCE_AFTER_DELETE
ON dbo.TASKFORCE 
AFTER DELETE
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS  SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='TASKFORCE';


GO
CREATE TRIGGER TASKFORCE_AFTER_INSERT
ON dbo.TASKFORCE 
AFTER INSERT
AS
  SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS  SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='TASKFORCE';


GO
CREATE TRIGGER TASKFORCE_AFTER_UPDATE
ON dbo.TASKFORCE 
AFTER UPDATE
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS  SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='TASKFORCE';


GO
CREATE TRIGGER XWEBCONSTRAINT_AFTER_DELETE
ON dbo.XWEBCONSTRAINT 
AFTER DELETE
AS
    SET NOCOUNT ON; 
    UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBCONSTRAINT';


GO
CREATE TRIGGER XWEBCONSTRAINT_AFTER_INSERT
ON dbo.XWEBCONSTRAINT 
AFTER INSERT
AS
    SET NOCOUNT ON;
    UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBCONSTRAINT';

GO
CREATE TRIGGER XWEBCONSTRAINT_AFTER_UPDATE
ON dbo.XWEBCONSTRAINT 
AFTER UPDATE
AS
  SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBCONSTRAINT';


GO
CREATE TRIGGER XWEBQUERY_AFTER_DELETE
ON dbo.XWEBQUERY 
AFTER DELETE
AS
    SET NOCOUNT ON;
    UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERY';


GO
CREATE TRIGGER XWEBQUERY_AFTER_INSERT
ON dbo.XWEBQUERY 
AFTER INSERT
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERY';


GO
CREATE TRIGGER XWEBQUERY_AFTER_UPDATE
ON dbo.XWEBQUERY 
AFTER UPDATE
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERY';

GO
CREATE TRIGGER TSKF_MEMBER_AFTER_DELETE
ON dbo.TSKF_MEMBER 
AFTER DELETE
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='TSKF_MEMBER';

GO
CREATE TRIGGER TSKF_MEMBER_AFTER_INSERT
ON dbo.TSKF_MEMBER 
AFTER INSERT
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='TSKF_MEMBER';

GO
CREATE TRIGGER TSKF_MEMBER_AFTER_UPDATE
ON dbo.TSKF_MEMBER 
AFTER UPDATE
AS
    SET NOCOUNT ON;
    UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='TSKF_MEMBER';


GO
CREATE TRIGGER XWEBQUERYATTRIBUTES_AFTER_DELETE
ON dbo.XWEBQUERYATTRIBUTES
AFTER DELETE
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERYATTRIBUTES';

GO
CREATE TRIGGER XWEBQUERYATTRIBUTES_AFTER_INSERT
ON dbo.XWEBQUERYATTRIBUTES
AFTER INSERT
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERYATTRIBUTES';

GO
CREATE TRIGGER XWEBQUERYATTRIBUTES_AFTER_UPDATE
ON dbo.XWEBQUERYATTRIBUTES
AFTER UPDATE
AS
    SET NOCOUNT ON;
    UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERYATTRIBUTES';


GO
CREATE TRIGGER XWEBQUERYORDERS_AFTER_DELETE
ON dbo.XWEBQUERYORDERS
AFTER DELETE
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERYORDERS';

GO
CREATE TRIGGER XWEBQUERYORDERS_AFTER_INSERT
ON dbo.XWEBQUERYORDERS
AFTER INSERT
AS
   SET NOCOUNT ON;
   UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERYORDERS';

GO
CREATE TRIGGER XWEBQUERYORDERS_AFTER_UPDATE
ON dbo.XWEBQUERYORDERS
AFTER UPDATE
AS
    SET NOCOUNT ON;
    UPDATE dbo.XUPDATEOBJECTS SET DATEMODIFIED = SYSDATETIME() WHERE OBJTABLE='XWEBQUERYORDERS';

