# ---------------------------------------------------------------------------
!if !$d(BCB)
BCB = $(MAKEDIR)\..
!endif

# ---------------------------------------------------------------------------
# IDE SECTION
# ---------------------------------------------------------------------------
# The following section of the project makefile is managed by the BCB IDE.
# It is recommended to use the IDE to change any of the values in this
# section.
# ---------------------------------------------------------------------------

VERSION = BCB.06.00
# ---------------------------------------------------------------------------
PROJECT = lisbc.exe
OBJFILES = LISBC.obj uMainForm.obj uMainDm.obj uConnect.obj uEditBases.obj uAbout.obj \
    uFrmTxBase.obj uFrmTxBaseAir.obj uFrmTxBaseAirAnalog.obj \
    uFrmTxBaseAirDigital.obj uFrmTxLfMf.obj uFrmTxVHF.obj uFrmTxDAB.obj uFrmTxDVB.obj \
    uFrmTxTVA.obj uFrmTxCTV.obj uBaseList.obj uBaseListTree.obj uFrmTxFxm.obj \
    uListCountry.obj uListArea.obj uListCity.obj uListAccountCondition.obj \
    uListStreet.obj uListAnalogRadioSystem.obj uListAnalogTeleSystem.obj \
    uListChannel.obj uListDigitalSystem.obj uListSystemCast.obj \
    uListCarrierGuardInterval.obj uListOffsetCarryFreqTVA.obj \
    uListDistrict.obj uListMinFieldStrength.obj uListRadioService.obj \
    uListTypeReceive.obj uListUncompatibleChannels.obj uListEquipment.obj \
    uListStand.obj TxBroker.obj uListOwner.obj \
    uListBank.obj uListTelecomOrganization.obj uNewTxWizard.obj \
    FormProvider.obj uTable36.obj uListBlockDAB.obj uListCityModal.obj \
    uListTransmitters.obj \
    uListTPOnBorder.obj uListLicense.obj uListSynhroNet.obj uListTypeSFN.obj \
    uExplorer.obj uNewSelection.obj uSelection.obj \
    "C:\Progra~1\Borland\CBuilder6\Imports\RSAGeography_TLB.obj" \
    "C:\Progra~1\Borland\CBuilder6\Imports\LISPropagation_TLB.obj" \
    "C:\Progra~1\Borland\CBuilder6\Imports\p1546_TLB.obj" \
    "C:\Progra~1\Borland\CBuilder6\Imports\p370_TLB.obj" \
    "C:\Progra~1\Borland\CBuilder6\Imports\MapXLib_TLB.obj" \
    "C:\Progra~1\Borland\CBuilder6\Imports\MapXLib_OCX.obj" \
    "C:\Progra~1\Borland\CBuilder6\Imports\LISBCCalc_TLB.obj" uParams.obj \
    "C:\Progra~1\Borland\CBuilder6\Imports\LISBCProtect_TLB.obj" \
    "C:\Progra~1\Borland\CBuilder6\Imports\ExpServer_TLB.obj" \
    uFrmDocumentsSettings.obj uCalcParamsDlg.obj uSelectTxTree.obj \
    uSectorDlg.obj uOffsetRangeDlg.obj uUserActivityLog.obj \
    uWhere.obj uSearch.obj uLayoutMngr.obj uListFrequencyGrid.obj \
    uFormOwner.obj uAnalyzer.obj uMessageLog.obj uPlanning.obj uDuelResult.obj \
    uDiagramPanel.obj DlgSelectTypeDoc.obj uProfileView.obj uReliefFrm.obj \
    SelectColumnsForm.obj uExportDlg.obj Transliterator.obj LISBC_TLB.obj LISProgress_OCX.obj \
    CoCalcProgressImpl.obj LISBC_ATL.obj uFrmPoint.obj uEnterCoordDlg.obj \
    uCoordinationPoint.obj CoPWRCallbackImpl.obj uContourForm.obj \
    uListDigAllotments.obj uImportDigLayer.obj BcDrawer.obj uItuImport.obj uItuExport.obj \
    uXmlDoc.obj uListSubareas.obj uDlgList.obj uAllotmentForm.obj \
    uDlgConstrSet.obj CoordConv.obj uLisObjectGrid.obj BaseMap.obj CustomMap.obj uDlgEminAndNote.obj \
    uDlgMapConf.obj uAutoUpgrade.obj uBcAutoUpgrade.obj uLogger.obj DbCreation.obj \
    uBaseObjForm.obj uSelectStations.obj \
    uNewChPlanDlg.obj CoStorageImpl.obj uSaveServer.obj uSelectServer.obj uSelectionGridProxi.obj \
    uLisObjectGridForm.obj uCoordZoneFieldStr.obj
RESFILES = LISBC.res LISBC.tlb
MAINSOURCE = LISBC.cpp
RESDEPEN = $(RESFILES) uMainForm.dfm uMainDm.dfm uConnect.dfm uEditBases.dfm \
    uAbout.dfm uFrmTxBase.dfm uFrmTxBaseAir.dfm uFrmTxBaseAirAnalog.dfm \
    uFrmTxBaseAirDigital.dfm uFrmTxLfMf.dfm uFrmTxVHF.dfm uFrmTxDAB.dfm uFrmTxDVB.dfm \
    uFrmTxTVA.dfm uFrmTxCTV.dfm uBaseList.dfm uBaseListTree.dfm uFrmTxFxm.dfm \
    uListCountry.dfm uListArea.dfm uListCity.dfm uListAccountCondition.dfm \
    uListStreet.dfm uListAnalogRadioSystem.dfm uListAnalogTeleSystem.dfm \
    uListChannel.dfm uListDigitalSystem.dfm uListSystemCast.dfm \
    uListCarrierGuardInterval.dfm uListOffsetCarryFreqTVA.dfm \
    uListDistrict.dfm uListMinFieldStrength.dfm uListRadioService.dfm \
    uListTypeReceive.dfm uListUncompatibleChannels.dfm uListEquipment.dfm \
    uListStand.dfm uListOwner.dfm uListBank.dfm \
    uListTelecomOrganization.dfm uNewTxWizard.dfm uTable36.dfm \
    uListBlockDAB.dfm uListCityModal.dfm \
    uListTransmitters.dfm uListTPOnBorder.dfm \
    uListLicense.dfm uListSynhroNet.dfm uListTypeSFN.dfm uExplorer.dfm \
    uNewSelection.dfm uSelection.dfm uFrmDocumentsSettings.dfm \
    uCalcParamsDlg.dfm uSelectTxTree.dfm uSectorDlg.dfm \
    uOffsetRangeDlg.dfm uUserActivityLog.dfm uWhere.dfm uSearch.dfm \
    uListFrequencyGrid.dfm uFormOwner.dfm uPlanning.dfm uDuelResult.dfm \
    uFormsDm.dfm DlgSelectTypeDoc.dfm \
    uProfileView.dfm uReliefFrm.dfm SelectColumnsForm.dfm \
    uExportDlg.dfm uFrmPoint.dfm uEnterCoordDlg.dfm \
    uContourForm.dfm uListDigAllotments.dfm uImportDigLayer.dfm uItuImport.dfm uItuExport.dfm \
    uListSubareas.dfm uDlgList.dfm uAllotmentForm.dfm uDlgConstrSet.dfm \
    uLisObjectGrid.dfm BaseMap.dfm CustomMap.dfm uDlgEminAndNote.dfm uDlgMapConf.dfm \
    uNewChPlanDlg.dfm uSaveServer.dfm uSelectServer.dfm uLisObjectGridForm.dfm uCoordZoneFieldStr.dfm
LIBFILES = 
IDLFILES = 
IDLGENFILES = 
LIBRARIES = vclnp.lib inet.lib xmlrtl.lib msxml20.lib PiFolio.lib NumEdit.lib \
    B6XLR4_R.lib rsMapUniversalX.lib vclx.lib bcb2kaxserver.lib indy.lib \
    dbxcds.lib dclocx.lib soaprtl.lib bcbie.lib nmfast.lib inetdbxpress.lib \
    inetdbbde.lib bcbsmp.lib dsnapcon.lib dsnapcrba.lib visualdbclx.lib \
    teeqr.lib dss.lib tee.lib teedb.lib teeui.lib qrpt.lib bdecds.lib \
    vcldbx.lib bdertl.lib adortl.lib vcldb.lib dbexpress.lib dsnap.lib cds.lib \
    ibxpress.lib dbrtl.lib 
PACKAGES = vcl.bpi rtl.bpi
SPARELIBS = vcl.lib rtl.lib dbrtl.lib ibxpress.lib cds.lib dsnap.lib dbexpress.lib \
    vcldb.lib adortl.lib bdertl.lib vcldbx.lib bdecds.lib qrpt.lib teeui.lib \
    teedb.lib tee.lib dss.lib teeqr.lib visualdbclx.lib dsnapcrba.lib \
    dsnapcon.lib bcbsmp.lib inetdbbde.lib inetdbxpress.lib nmfast.lib \
    bcbie.lib soaprtl.lib dclocx.lib dbxcds.lib indy.lib bcb2kaxserver.lib \
    vclx.lib rsMapUniversalX.lib B6XLR4_R.lib NumEdit.lib PiFolio.lib \
    msxml20.lib xmlrtl.lib inet.lib
DEFFILE = 
OTHERFILES = 
# ---------------------------------------------------------------------------
DEBUGLIBPATH = $(BCB)\lib\debug
RELEASELIBPATH = $(BCB)\lib\release
USERDEFINES = 
SYSDEFINES = NO_STRICT;_ATL_APARTMENT_THREADED;USING_ATLVCL;_ATL_NO_SECURITY;INC_ATL_HEADERS;USEPACKAGES
INCLUDEPATH = $(BCB)\include;$(BCB)\include\vcl;$(BCB)\Imports;"C:\Program Files\AfalinaSoft\XL Report 4\B6units"

!ifdef DEBUG
LIBPATH = $(BCB)\lib;$(BCB)\lib\obj;$(BCB)\Imports;"C:\Program Files\AfalinaSoft\XL Report 4\B6units";$(BCB)\Projects\Lib;$(BCB)\lib\psdk
!else
LIBPATH = $(BCB)\lib;$(BCB)\lib\obj;$(BCB)\Imports;"C:\Program Files\AfalinaSoft\XL Report 4\B6units";$(BCB)\Projects\Lib;$(BCB)\lib\psdk
!endif

WARNINGS= -w-pck -w-par
PATHCPP = .;"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports";"C:\Program Files\Borland\CBuilder6\Imports"
PATHASM = .;
PATHPAS = .;
PATHRC = .;
PATHOBJ = .;$(LIBPATH)
# ---------------------------------------------------------------------------

!ifdef DEBUG
CFLAG1 = -Od -H=$(BCB)\precomphdr\bc.csm -Vx -Ve -X- -r- -a2 -b -k -y -v -vi- -c -tW -tWM -D_DEBUG
!else
CFLAG1 = -Od -H=$(BCB)\precomphdr\bc.csm -Vx -Ve -X- -r- -a2 -b -k -y -vi- -c -tW -tWM
!endif

IDLCFLAGS = -I$(BCB)\include -I$(BCB)\include\vcl -I$(BCB)\Imports \
    -I"C:\Program Files\AfalinaSoft\XL Report 4\B6units" -src_suffix cpp -boa
PFLAGS = -$Y+ -$W -$O- -$A8 -JPHNE -M
RFLAGS = 
AFLAGS = /mx /w2 /zi

!ifdef DEBUG
LFLAGS =  -aa -Tpe -x -v
!else
LFLAGS =  -aa -Tpe -x
!endif

# ---------------------------------------------------------------------------
ALLOBJ = c0w32.obj $(PACKAGES) sysinit.obj Memmgr.Lib $(OBJFILES)
ALLRES = $(RESFILES)
ALLLIB = $(LIBFILES) $(LIBRARIES) import32.lib cp32mt.lib
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# MAKE SECTION
# ---------------------------------------------------------------------------
# This section of the project file is not used by the BCB IDE.  It is for
# the benefit of building from the command-line using the MAKE utility.
# ---------------------------------------------------------------------------

.autodepend
# ---------------------------------------------------------------------------
!if "$(USERDEFINES)" != ""
AUSERDEFINES = -d$(USERDEFINES:;= -d)
!else
AUSERDEFINES =
!endif

!if !$d(BCC32)
BCC32 = bcc32
!endif

!if !$d(CPP32)
CPP32 = cpp32
!endif

!if !$d(DCC32)
DCC32 = dcc32
!endif

!if !$d(TASM32)
TASM32 = tasm32
!endif

!if !$d(LINKER)
LINKER = ilink32
!endif

!if !$d(BRCC32)
BRCC32 = brcc32
!endif


# ---------------------------------------------------------------------------
!if $d(PATHCPP)
.PATH.CPP = $(PATHCPP)
.PATH.C   = $(PATHCPP)
!endif

!if $d(PATHPAS)
.PATH.PAS = $(PATHPAS)
!endif

!if $d(PATHASM)
.PATH.ASM = $(PATHASM)
!endif

!if $d(PATHRC)
.PATH.RC  = $(PATHRC)
!endif

!if $d(PATHOBJ)
.PATH.OBJ  = $(PATHOBJ)
!endif
# ---------------------------------------------------------------------------
$(PROJECT): $(OTHERFILES) $(IDLGENFILES) $(OBJFILES) $(RESDEPEN) $(DEFFILE)
    $(BCB)\BIN\$(LINKER) @&&!
    $(LFLAGS) -L$(LIBPATH) +
    $(ALLOBJ), +
    $(PROJECT),, +
    $(ALLLIB), +
    $(DEFFILE), +
    $(ALLRES)
!
# ---------------------------------------------------------------------------
.pas.hpp:
    $(BCB)\BIN\$(DCC32) $(PFLAGS) -U$(INCLUDEPATH) -D$(USERDEFINES);$(SYSDEFINES) -O$(INCLUDEPATH) --BCB {$< }

.pas.obj:
    $(BCB)\BIN\$(DCC32) $(PFLAGS) -U$(INCLUDEPATH) -D$(USERDEFINES);$(SYSDEFINES) -O$(INCLUDEPATH) --BCB {$< }

.cpp.obj:
    $(BCB)\BIN\$(BCC32) $(CFLAG1) $(WARNINGS) -I$(INCLUDEPATH) -D$(USERDEFINES);$(SYSDEFINES) -n$(@D) {$< }

.c.obj:
    $(BCB)\BIN\$(BCC32) $(CFLAG1) $(WARNINGS) -I$(INCLUDEPATH) -D$(USERDEFINES);$(SYSDEFINES) -n$(@D) {$< }

.c.i:
    $(BCB)\BIN\$(CPP32) $(CFLAG1) $(WARNINGS) -I$(INCLUDEPATH) -D$(USERDEFINES);$(SYSDEFINES) -n. {$< }

.cpp.i:
    $(BCB)\BIN\$(CPP32) $(CFLAG1) $(WARNINGS) -I$(INCLUDEPATH) -D$(USERDEFINES);$(SYSDEFINES) -n. {$< }

.asm.obj:
    $(BCB)\BIN\$(TASM32) $(AFLAGS) -i$(INCLUDEPATH:;= -i) $(AUSERDEFINES) -d$(SYSDEFINES:;= -d) $<, $@

.rc.res:
    $(BCB)\BIN\$(BRCC32) $(RFLAGS) -I$(INCLUDEPATH) -D$(USERDEFINES);$(SYSDEFINES) -fo$@ $<



# ---------------------------------------------------------------------------




