CREATE TABLE ICSC.RES_LOCATION_SENSOR_MEAS
(
  ID           NUMBER(15)                       NOT NULL,
  LON          NUMBER(30,10),
  LAT          NUMBER(30,10),
  ASL          NUMBER(30,10),
  RES_MEAS_ID  NUMBER(15),
  AGL          NUMBER(30,10)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ICSC.RES_LOC_SEN_MEAS_RESMEASID_PK ON ICSC.RES_LOCATION_SENSOR_MEAS
(RES_MEAS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ICSC.RES_LOC_SENSOR_MEAS_ID_PK ON ICSC.RES_LOCATION_SENSOR_MEAS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.RES_LOCATION_SENSOR_MEAS ADD (
  CONSTRAINT RESLOCSENSORMEAS_PK
 PRIMARY KEY
 (ID));
