CREATE TABLE ICSC.MEAS_SUB_TASK
(
  ID           NUMBER(15)                       NOT NULL,
  TIME_START   DATE,
  TIME_STOP    DATE,
  STATUS       NVARCHAR2(50),
  INTERVAL     NUMBER(9),
  ID_MEASTASK  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.XBS_MEASSUBTASK_PK ON ICSC.MEAS_SUB_TASK
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.MEAS_SUB_TASK ADD (
  CONSTRAINT XBS_MEASSUBTASK_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.MEAS_SUB_TASK ADD (
  CONSTRAINT FK_XBS_MEASSUBTASK_XBS_MEASTAS 
 FOREIGN KEY (ID_MEASTASK) 
 REFERENCES ICSC.MEAS_TASK (ID));
