CREATE TABLE ICSC.SENSOR_ANTENNA
(
  ID            NUMBER(15)                      NOT NULL,
  SENSOR_ID     NUMBER(15),
  CODE          NVARCHAR2(50),
  SLEWANG       NUMBER(30,10),
  MANUFACTURER  NVARCHAR2(50),
  NAME          NVARCHAR2(50),
  TECHID        NVARCHAR2(50),
  ANTDIR        NVARCHAR2(50),
  HBEAMWIDTH    NUMBER(30,10),
  VBEAMWIDTH    NUMBER(30,10),
  POLARIZATION  NVARCHAR2(50),
  USETYPE       NVARCHAR2(50),
  CATEGORY      NVARCHAR2(50),
  GAINTYPE      NVARCHAR2(50),
  GAINMAX       NUMBER(30,10),
  LOWERFREQ     NUMBER(30,10),
  UPPERFREQ     NUMBER(30,10),
  ADDLOSS       NUMBER(30,10),
  XPD           NUMBER(30,10),
  ANTCLASS      NVARCHAR2(50),
  REMARK        NVARCHAR2(250),
  CUSTTXT1      NVARCHAR2(250),
  CUSTDATA1     DATE,
  CUSTNBR1      NUMBER(30,10)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.SENSOR_ANTENNA_ID_PK ON ICSC.SENSOR_ANTENNA
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.SENSOR_ANTENNA ADD (
  CONSTRAINT SENSORANTENNA_PK
 PRIMARY KEY
 (ID));
