CREATE TABLE ICSC.FREQ_SAMPLE
(
  ID             NUMBER(15)                     NOT NULL,
  FREQ_MHZ       NUMBER(30,10),
  LEVEL_DBM      NUMBER(30,10),
  LEVEL_DBMKVM   NUMBER(30,10),
  LEVEL_MIN_DBM  NUMBER(30,10),
  LEVEL_MAX_DBM  NUMBER(30,10),
  OCCUPATION_PT  NUMBER(30,10),
  RES_MEAS_ID    NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.XBS_FREQSAMPLERAW_PK ON ICSC.FREQ_SAMPLE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.FREQ_SAMPLE ADD (
  CONSTRAINT FREQ_SAMPLE_PK
 PRIMARY KEY
 (ID));

ALTER TABLE ICSC.FREQ_SAMPLE ADD (
  CONSTRAINT FK_XBS_FREQSAMPLERAW_XBS_RESME 
 FOREIGN KEY (RES_MEAS_ID) 
 REFERENCES ICSC.RES_MEAS (ID));
