CREATE TABLE ICSC.STATION
(
  ID              NUMBER(15)                    NOT NULL,
  GLOBAL_SID      NVARCHAR2(50),
  STATUS          NVARCHAR2(50),
  STANDARD        NVARCHAR2(50),
  ID_MEASTASK     NUMBER(15),
  ID_STATION      NUMBER(15),
  START_DATE      DATE,
  END_DATE        DATE,
  CLOSE_DATE      DATE,
  DOZVIL_NAME     NVARCHAR2(100),
  ID_OWNERDATA    NUMBER(15),
  ID_STATIONSITE  NUMBER(15),
  ID_PERMISSION   NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.XBS_STATION_PK ON ICSC.STATION
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_STATION_STATION_FK ON ICSC.STATION
(ID_STATION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_STATION_STATIONSITE_FK ON ICSC.STATION
(ID_STATIONSITE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_STATION_XBS_MEASTASK_FK ON ICSC.STATION
(ID_MEASTASK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_STATION_XBS_OWNERDATA_FK ON ICSC.STATION
(ID_OWNERDATA)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.STATION ADD (
  CONSTRAINT XBS_STATION_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.STATION ADD (
  CONSTRAINT FK_XBS_STATION_XBS_OWNERDATA 
 FOREIGN KEY (ID_OWNERDATA) 
 REFERENCES ICSC.OWNER_DATA (ID),
  CONSTRAINT FK_XBS_STATION_XBS_STATIONSITE 
 FOREIGN KEY (ID_STATIONSITE) 
 REFERENCES ICSC.STATION_SITE (ID));
