CREATE TABLE ICSC.MEAS_OTHER
(
  ID                        NUMBER(15)          NOT NULL,
  TYPE_SPECTRUM_OCCUPATION  NVARCHAR2(50),
  LEVEL_MIN_OCCUP           NUMBER(30,10),
  NCHENAL                   NUMBER(9),
  MEAS_TASK_ID              NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.MEAS_OTHER_ID_PK ON ICSC.MEAS_OTHER
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.MEAS_OTHER ADD (
  CONSTRAINT MEASOTHER_PK
 PRIMARY KEY
 (ID));
