CREATE TABLE ICSC.RES_ROUTES
(
  ID               NUMBER(15)                   NOT NULL,
  ROUTE_ID         NVARCHAR2(250),
  AGL              NUMBER(30,10),
  ASL              NUMBER(30,10),
  FINISH_TIME      DATE                         NOT NULL,
  LAT              NUMBER(30,10),
  LON              NUMBER(30,10),
  POINT_STAY_TYPE  NVARCHAR2(150),
  START_TIME       DATE,
  RES_MEAS_ID      NUMBER(15)                   NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.RES_ROUTES_ID_PK ON ICSC.RES_ROUTES
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.RES_ROUTES ADD (
  CONSTRAINT RESROUTES_PK
 PRIMARY KEY
 (ID));
