CREATE TABLE ICSC.MEAS_SUBTASK
(
  ID            NUMBER(15)                      NOT NULL,
  TIME_START    DATE,
  TIME_STOP     DATE,
  STATUS        NVARCHAR2(50),
  INTERVAL      NUMBER(9),
  MEAS_TASK_ID  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.MEAS_SUB_TASK_ID_PK ON ICSC.MEAS_SUBTASK
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.MEAS_SUBTASK ADD (
  CONSTRAINT MEASSUBTASK_PK
 PRIMARY KEY
 (ID));
