CREATE TABLE ICSC.MEAS_DT_PARAM
(
  ID                 NUMBER(15)                 NOT NULL,
  TYPE_MEASUREMENTS  NVARCHAR2(50),
  DETECT_TYPE        NVARCHAR2(50),
  RF_ATTENUATION     NUMBER(30,10),
  IF_ATTENUATION     NUMBER(30,10),
  MEAS_TIME          NUMBER(30,10),
  DEMOD              NVARCHAR2(50),
  PREAMPLIFICATION   NUMBER(9),
  "MODE"             NVARCHAR2(50),
  RBW                NUMBER(30,10),
  VBW                NUMBER(30,10),
  MEAS_TASK_ID       NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.MEAS_DT_PARAM_ID_PK ON ICSC.MEAS_DT_PARAM
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.MEAS_DT_PARAM ADD (
  CONSTRAINT MEASDTPARAM_PK
 PRIMARY KEY
 (ID));
