CREATE TABLE ICSC.LINK_SECTOR_FREQ
(
  ID             NUMBER(15)                     NOT NULL,
  ID_SECTORFREQ  NUMBER(15),
  ID_SECTOR      NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ICSC.ID_XBS_SECTORFREQKEY ON ICSC.LINK_SECTOR_FREQ
(ID_SECTORFREQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.ID_XBS_SECTORKEY ON ICSC.LINK_SECTOR_FREQ
(ID_SECTOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ICSC.XBS_LINKSECTORFREQ_PK ON ICSC.LINK_SECTOR_FREQ
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.LINK_SECTOR_FREQ ADD (
  CONSTRAINT XBS_LINKSECTORFREQ_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.LINK_SECTOR_FREQ ADD (
  CONSTRAINT FK_XBS_LINKSECTORFREQ_XBS_SECT 
 FOREIGN KEY (ID_SECTOR) 
 REFERENCES ICSC.SECTOR (ID),
  CONSTRAINT FK_XBS_LINKSECTORFREQ_XBS_SE_1 
 FOREIGN KEY (ID_SECTORFREQ) 
 REFERENCES ICSC.SECTOR_FREQ (ID));
