CREATE TABLE ICSC.OWNER_DATA
(
  ID          NUMBER(15)                        NOT NULL,
  OWNER_NAME  NVARCHAR2(100),
  OKPO        NVARCHAR2(50),
  ZIP         NVARCHAR2(50),
  CODE        NVARCHAR2(50),
  ADDRES      NVARCHAR2(2000),
  STATION_ID  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.OWNER_DATA_ID_PK ON ICSC.OWNER_DATA
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.OWNER_DATA ADD (
  CONSTRAINT OWNERDATA_PK
 PRIMARY KEY
 (ID));
