CREATE TABLE ICSC.RES_MEAS_STATION
(
  ID               NUMBER(15)                   NOT NULL,
  GLOBAL_SID       NVARCHAR2(250),
  MEAS_GLOBAL_SID  NVARCHAR2(250),
  ID_SECTOR        NUMBER(15),
  ID_STATION       NUMBER(15),
  STATUS           NVARCHAR2(250),
  RESMEAS_ID       NUMBER(15),
  STANDARD         NVARCHAR2(50),
  STATION_ID       NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ICSC.XBS_RESMEASSIDXBSSTATION_FK ON ICSC.RES_MEAS_STATION
(STATION_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_RESMEASSTA_IDSTATION_FK ON ICSC.RES_MEAS_STATION
(ID_STATION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_RESMEASSTATION_IDSECTOR_FK ON ICSC.RES_MEAS_STATION
(ID_SECTOR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ICSC.XBS_RESMEASSTATION_PK ON ICSC.RES_MEAS_STATION
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_RESMEAS_XBSRESMEASID_FK ON ICSC.RES_MEAS_STATION
(RESMEAS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.RES_MEAS_STATION ADD (
  CONSTRAINT XBS_RESMEASSTATION_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.RES_MEAS_STATION ADD (
  CONSTRAINT FK_XBS_RESMEASSTATION_XBS_RESM 
 FOREIGN KEY (RESMEAS_ID) 
 REFERENCES ICSC.RES_MEAS (ID));
