CREATE TABLE ICSC.RES_MEAS_STATION
(
  ID                   NUMBER(15)               NOT NULL,
  GLOBAL_SID           NVARCHAR2(250),
  MEAS_GLOBAL_SID      NVARCHAR2(250),
  STATUS               NVARCHAR2(250),
  RES_MEAS_ID          NUMBER(15),
  STANDARD             NVARCHAR2(50),
  CLIENT_SECTOR_CODE   NUMBER(9),
  CLIENT_STATION_CODE  NUMBER(9)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.RES_MEAS_STATION_ID_PK ON ICSC.RES_MEAS_STATION
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.RES_MEAS_STATION_RESMEASID_PK ON ICSC.RES_MEAS_STATION
(RES_MEAS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.RES_MEAS_STATION ADD (
  CONSTRAINT RESMEASSTATION_PK
 PRIMARY KEY
 (ID));
