CREATE TABLE ICSC.RES_LEV_MEAS_ONLINE
(
  ID           NUMBER(15)                       NOT NULL,
  VALUE        NUMBER(30,10),
  RES_MEAS_ID  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.RES_LEV_MEAS_ONLINE_ID_PK ON ICSC.RES_LEV_MEAS_ONLINE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.RES_LEV_MEAS_ONLINE_PK ON ICSC.RES_LEV_MEAS_ONLINE
(RES_MEAS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.RES_LEV_MEAS_ONLINE ADD (
  CONSTRAINT RESLEVMEASONLINE_PK
 PRIMARY KEY
 (ID));
