CREATE TABLE ICSC.STATION
(
  ID                      NUMBER(15)            NOT NULL,
  GLOBAL_SID              NVARCHAR2(50),
  STATUS                  NVARCHAR2(50),
  STANDARD                NVARCHAR2(50),
  MEAS_TASK_ID            NUMBER(15),
  CLIENT_STATION_CODE     NUMBER(15),
  START_DATE              DATE,
  END_DATE                DATE,
  CLOSE_DATE              DATE,
  DOZVIL_NAME             NVARCHAR2(100),
  OWNER_DATA_ID           NUMBER(15),
  STATION_SITE_ID         NUMBER(15),
  CLIENT_PERMISSION_CODE  NUMBER(9)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.STATION_ID_PK ON ICSC.STATION
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.STATION_ID_STATION_PK ON ICSC.STATION
(CLIENT_STATION_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.STATION_MEASTASK_ID_PK ON ICSC.STATION
(MEAS_TASK_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.STATION_OWNERDATA_ID_PK ON ICSC.STATION
(OWNER_DATA_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.STATION_STATIONSITEID_PK ON ICSC.STATION
(STATION_SITE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.STATION ADD (
  CONSTRAINT STATION_PK
 PRIMARY KEY
 (ID));
