CREATE TABLE ICSC.ANTENNA_PATTERN
(
  ID                 NUMBER(15)                 NOT NULL,
  SENSOR_ANTENNA_ID  NUMBER(15),
  FREQ               NUMBER(30,10),
  GAIN               NUMBER(30,10),
  DIAGA              NVARCHAR2(1000),
  DIAGH              NVARCHAR2(1000),
  DIAGV              NVARCHAR2(1000)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.ANTENNA_PATTERN_ID_PK ON ICSC.ANTENNA_PATTERN
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.ANTENNA_PATTERN ADD (
  CONSTRAINT ANTENNAPATTERN_PK
 PRIMARY KEY
 (ID));
