CREATE TABLE ICSC.LINK_MEAS_STATION
(
  ID           NUMBER(15)                       NOT NULL,
  ID_MEASTASK  NUMBER(15),
  ID_STATION   NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.XBS_LINKMEASSTATION_PK ON ICSC.LINK_MEAS_STATION
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_LINKMEASSTATIONSTATION ON ICSC.LINK_MEAS_STATION
(ID_STATION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_LINKMEASXBSMEASTASK ON ICSC.LINK_MEAS_STATION
(ID_MEASTASK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.LINK_MEAS_STATION ADD (
  CONSTRAINT XBS_LINKMEASSTATION_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.LINK_MEAS_STATION ADD (
  CONSTRAINT FK_XBS_LINKMEASSTATION_XBS_MEA 
 FOREIGN KEY (ID_MEASTASK) 
 REFERENCES ICSC.MEAS_TASK (ID),
  CONSTRAINT FK_XBS_LINKMEASSTATION_XBS_STA 
 FOREIGN KEY (ID_STATION) 
 REFERENCES ICSC.STATION (ID));
