CREATE TABLE ICSC.LINK_SECTOR_MASK
(
  ID                   NUMBER(15)               NOT NULL,
  SECTOR_MASK_ELEM_ID  NUMBER(15),
  SECTOR_ID            NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ICSC.ID_LNKSECTORMASKELEMKEY ON ICSC.LINK_SECTOR_MASK
(SECTOR_MASK_ELEM_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.ID_XBS_LNKSECTORKEY ON ICSC.LINK_SECTOR_MASK
(SECTOR_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ICSC.XBS_LINKSECTORMASK_PK ON ICSC.LINK_SECTOR_MASK
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.LINK_SECTOR_MASK ADD (
  CONSTRAINT XBS_LINKSECTORMASK_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.LINK_SECTOR_MASK ADD (
  CONSTRAINT FK_XBS_LINKSECTORMASK_XBS_SECT 
 FOREIGN KEY (SECTOR_ID) 
 REFERENCES ICSC.SECTOR (ID),
  CONSTRAINT FK_XBS_LINKSECTORMASK_XBS_SE_1 
 FOREIGN KEY (SECTOR_MASK_ELEM_ID) 
 REFERENCES ICSC.SECTOR_MASK_ELEM (ID));
