CREATE TABLE ICSC.RES_STLEVEL_CAR
(
  ID                    NUMBER(15)              NOT NULL,
  RES_MEAS_STATION_ID   NUMBER(15),
  ALTITUDE              NUMBER(30,10),
  DIFFERENCE_TIMESTAMP  NUMBER(30,10),
  LAT                   NUMBER(30,10),
  LON                   NUMBER(30,10),
  LEVEL_DBM             NUMBER(30,10),
  LEVEL_DBMKVM          NUMBER(30,10),
  TIME_OF_MEASUREMENTS  DATE,
  AGL                   NUMBER(30,10)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ICSC.RES_ST_LEV_CAR_MEASSTATID_PK ON ICSC.RES_STLEVEL_CAR
(RES_MEAS_STATION_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX ICSC.RES_STLEVEL_CAR_ID_PK ON ICSC.RES_STLEVEL_CAR
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.RES_STLEVEL_CAR ADD (
  CONSTRAINT RESSTLEVELCAR_PK
 PRIMARY KEY
 (ID));
