CREATE TABLE ICSC.SENSOR_EQUIP
(
  ID              NUMBER(15)                    NOT NULL,
  SENSOR_ID       NUMBER(15),
  CODE            NVARCHAR2(50),
  MANUFACTURER    NVARCHAR2(50),
  NAME            NVARCHAR2(50),
  FAMILY          NVARCHAR2(50),
  TECHID          NVARCHAR2(200),
  VERSION         NVARCHAR2(50),
  LOWER_FREQ      NUMBER(22,8),
  UPPER_FREQ      NUMBER(22,8),
  RBW_MIN         NUMBER(22,8),
  RBW_MAX         NUMBER(22,8),
  VBW_MIN         NUMBER(22,8),
  VBW_MAX         NUMBER(22,8),
  MOBILITY        NUMBER(1),
  FFT_POINT_MAX   NUMBER(22,8),
  REF_LEVEL_DBM   NUMBER(22,8),
  OPERATION_MODE  NVARCHAR2(50),
  TYPE            NVARCHAR2(50),
  EQUIP_CLASS     NVARCHAR2(50),
  TUNING_STEP     NUMBER(22,8),
  USE_TYPE        NVARCHAR2(50),
  CATEGORY        NVARCHAR2(50),
  REMARK          NVARCHAR2(250),
  CUSTTXT1        NVARCHAR2(250),
  CUSTDATA1       DATE,
  CUSTNBR1        NUMBER(22,8)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.XBS_SENSOREQUIP_PK ON ICSC.SENSOR_EQUIP
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.SENSOR_EQUIP ADD (
  CONSTRAINT XBS_SENSOREQUIP_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.SENSOR_EQUIP ADD (
  CONSTRAINT FK_XBS_SENSOREQUIP_XBS_SENSOR 
 FOREIGN KEY (SENSOR_ID) 
 REFERENCES ICSC.SENSOR (ID));
