CREATE TABLE ICSC.MEAS_LOCATION_PARAM
(
  ID            NUMBER(15)                      NOT NULL,
  LON           NUMBER(22,8),
  LAT           NUMBER(22,8),
  ASL           NUMBER(22,8),
  MAXDIST       NUMBER(22,8),
  MEAS_TASK_ID  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.XBS_MEASLOCPARAM_PK ON ICSC.MEAS_LOCATION_PARAM
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.MEAS_LOCATION_PARAM ADD (
  CONSTRAINT XBS_MEASLOCPARAM_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.MEAS_LOCATION_PARAM ADD (
  CONSTRAINT FK_XBS_MEASLOCPARAM_XBS_MEASTA 
 FOREIGN KEY (MEAS_TASK_ID) 
 REFERENCES ICSC.MEAS_TASK (ID));
