CREATE TABLE ICSC.HEALTH_LOG_DETAIL
(
  ID              NUMBER(15)                    NOT NULL,
  HEALTH_ID       NUMBER(15),
  CREATED_DATE    TIMESTAMP(7) WITH TIME ZONE,
  MESSAGE         NVARCHAR2(250),
  THREAD_ID       NUMBER(9),
  SOURCE          RAW(450),
  SITE_TYPE_CODE  NUMBER(3),
  SITE_TYPE_NAME  NVARCHAR2(50),
  SITE_INSTANCE   NVARCHAR2(250),
  SITE_HOST       NVARCHAR2(250),
  NOTE            NCLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE ICSC.HEALTH_LOG_DETAIL ADD (
  PRIMARY KEY
 (ID));
