CREATE TABLE ICSC.MEAS_FREQ_PARAM
(
  ID            NUMBER(15)                      NOT NULL,
  "MODE"        NVARCHAR2(50),
  RGL           NUMBER(30,10),
  RGU           NUMBER(30,10),
  STEP          NUMBER(30,10),
  MEAS_TASK_ID  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.MEAS_FREQ_PARAM_ID_PK ON ICSC.MEAS_FREQ_PARAM
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.MEAS_FREQ_PARAM ADD (
  CONSTRAINT MEASFREQPARAM_PK
 PRIMARY KEY
 (ID));
