CREATE TABLE ICSC.MEAS_STATION
(
  ID                   NUMBER(15)               NOT NULL,
  STATION_TYPE         NVARCHAR2(50),
  MEAS_TASK_ID         NUMBER(15),
  CLIENT_STATION_CODE  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.MEAS_STATION_ID_PK ON ICSC.MEAS_STATION
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.MEAS_STATION ADD (
  CONSTRAINT MEASSTATION_PK
 PRIMARY KEY
 (ID));
