CREATE TABLE ICSC.SENSOR_EQUIP_SENSITIVITES
(
  ID               NUMBER(15)                   NOT NULL,
  SENSOR_EQUIP_ID  NUMBER(15),
  FREQ             NUMBER(30,10),
  KTBF             NUMBER(30,10),
  NOISEF           NUMBER(30,10),
  FREQ_STABILITY   NUMBER(30,10),
  ADDLOSS          NUMBER(30,10)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.SENSOR_EQUIP_SENS_ID_PK ON ICSC.SENSOR_EQUIP_SENSITIVITES
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.SENSOR_EQUIP_SENSITIVITES ADD (
  CONSTRAINT SENSOREQUIPSENS_PK
 PRIMARY KEY
 (ID));
