CREATE TABLE ICSC.HEALTH_LOG_DATA
(
  ID         NUMBER(15)                         NOT NULL,
  JSON_DATA  NCLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.HEALTH_LOG_DATA_PK ON ICSC.HEALTH_LOG_DATA
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.HEALTH_LOG_DATA ADD (
  CONSTRAINT HEALTH_LOG_DATA_PK
 PRIMARY KEY
 (ID));
