CREATE TABLE ICSC.MEAS_LOCATION_PARAM
(
  ID            NUMBER(15)                      NOT NULL,
  LON           NUMBER(30,10),
  LAT           NUMBER(30,10),
  ASL           NUMBER(30,10),
  MAXDIST       NUMBER(30,10),
  MEAS_TASK_ID  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.MEAS_LOC_PARAM_ID_PK ON ICSC.MEAS_LOCATION_PARAM
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.MEAS_LOCATION_PARAM ADD (
  CONSTRAINT MEASLOCPARAM_PK
 PRIMARY KEY
 (ID));
