CREATE TABLE ICSR.SENSOR_ANTENNA
(
  ID            NUMBER(15)                      NOT NULL,
  SENSOR_ID     NUMBER(15),
  CODE          NVARCHAR2(50),
  SLEWANG       NUMBER(22,8),
  MANUFACTURER  NVARCHAR2(50),
  NAME          NVARCHAR2(50),
  TECHID        NVARCHAR2(50),
  ANTDIR        NVARCHAR2(50),
  HBEAMWIDTH    NUMBER(22,8),
  VBEAMWIDTH    NUMBER(22,8),
  POLARIZATION  NVARCHAR2(50),
  USETYPE       NVARCHAR2(50),
  CATEGORY      NVARCHAR2(50),
  GAINTYPE      NVARCHAR2(50),
  GAINMAX       NUMBER(22,8),
  LOWERFREQ     NUMBER(22,8),
  UPPERFREQ     NUMBER(22,8),
  ADDLOSS       NUMBER(22,8),
  XPD           NUMBER(22,8),
  ANTCLASS      NVARCHAR2(50),
  REMARK        NVARCHAR2(250),
  CUSTTXT1      NVARCHAR2(250),
  CUSTDATA1     DATE,
  CUSTNBR1      NUMBER(22,8)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.XBS_SENSORANTENNA_PK ON ICSR.SENSOR_ANTENNA
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSR.SENSOR_ANTENNA ADD (
  CONSTRAINT XBS_SENSORANTENNA_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSR.SENSOR_ANTENNA ADD (
  CONSTRAINT FK_XBS_SENSORANTENNA_XBS_SENSO 
 FOREIGN KEY (SENSOR_ID) 
 REFERENCES ICSR.SENSOR (ID));
