CREATE TABLE ICSC.RES_LOCATION_SENSOR_MEAS
(
  ID          NUMBER(15)                        NOT NULL,
  LON         NUMBER(22,8),
  LAT         NUMBER(22,8),
  ASL         NUMBER(22,8),
  RESMEAS_ID  NUMBER(15),
  AGL         NUMBER(22,8)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.XBS_RESLOCSENSORMEAS_PK ON ICSC.RES_LOCATION_SENSOR_MEAS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.XBS_RESSTATIONMEAS_IDKEY ON ICSC.RES_LOCATION_SENSOR_MEAS
(RESMEAS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.RES_LOCATION_SENSOR_MEAS ADD (
  CONSTRAINT XBS_RESLOCSENSORMEAS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.RES_LOCATION_SENSOR_MEAS ADD (
  CONSTRAINT FK_XBS_RESLOCSENSORMEAS_XBS_RE 
 FOREIGN KEY (RESMEAS_ID) 
 REFERENCES ICSC.RES_MEAS (ID));
