CREATE TABLE ICSC.RES_LEVELS
(
  ID               NUMBER(15)                   NOT NULL,
  VALUE_LVL        NUMBER(22,8),
  STDDEV_LVL       NUMBER(22,8),
  VMIN_LVL         NUMBER(22,8),
  VMMAX_LVL        NUMBER(22,8),
  LIMIT_LVL        NUMBER(22,8),
  OCCUPANCY_LVL    NUMBER(22,8),
  PMIN_LVL         NUMBER(22,8),
  PMAX_LVL         NUMBER(22,8),
  PDIFF_LVL        NUMBER(22,8),
  FREQ_MEAS        NUMBER(22,8),
  VALUE_SPECT      NUMBER(22,8),
  STDDEV_SPECT     NUMBER(22,8),
  VMIN_SPECT       NUMBER(22,8),
  VMMAX_SPECT      NUMBER(22,8),
  LIMIT_SPECT      NUMBER(22,8),
  OCCUPANCY_SPECT  NUMBER(22,8),
  RES_MEAS_ID      NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.ID_XBS_RESLEVELS_PK ON ICSC.RES_LEVELS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX ICSC.ID_XBS_RESSTATIONMEAS_PK ON ICSC.RES_LEVELS
(RES_MEAS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.RES_LEVELS ADD (
  CONSTRAINT ID_XBS_RESLEVELS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE ICSC.RES_LEVELS ADD (
  CONSTRAINT FK_XBS_RESLEVELS_XBS_RESMEAS 
 FOREIGN KEY (RES_MEAS_ID) 
 REFERENCES ICSC.RES_MEAS (ID));
