CREATE TABLE ICSC.HEALTH_LOG
(
  ID                NUMBER(15)                  NOT NULL,
  SENDER_LOG_ID     NUMBER(15),
  SENDER_TYPE_CODE  NUMBER(3),
  SENDER_TYPE_NAME  NVARCHAR2(50),
  SENDER_INSTANCE   NVARCHAR2(250),
  SENDER_HOST       NVARCHAR2(250),
  SOURCE_TYPE_CODE  NUMBER(3),
  SOURCE_TYPE_NAME  NVARCHAR2(50),
  SOURCE_INSTANCE   NVARCHAR2(250),
  SOURCE_TECHID     NVARCHAR2(250),
  SOURCE_HOST       NVARCHAR2(250),
  EVENT_CODE        NUMBER(3),
  EVENT_NAME        NVARCHAR2(50),
  DISPATCH_TIME     TIMESTAMP(7) WITH TIME ZONE,
  RECEIVED_TIME     TIMESTAMP(7) WITH TIME ZONE,
  FORWARDED_TIME    TIMESTAMP(7) WITH TIME ZONE,
  EVENT_NOTE        NCLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX ICSC.HEALTH_LOG_PK ON ICSC.HEALTH_LOG
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE ICSC.HEALTH_LOG ADD (
  CONSTRAINT HEALTH_LOG_PK
 PRIMARY KEY
 (ID));
