CREATE TABLE CALC.CALCTASKS_COVERAGEPROFILES
(
  ID             NUMBER(15)                     NOT NULL,
  MODE_CODE      NUMBER(3)                      NOT NULL,
  MODE_NAME      NVARCHAR2(50),
  POINTS_CRDS_X  BLOB,
  POINTS_CRDS_Y  BLOB,
  RESULT_PATH    NVARCHAR2(450)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CALCTASKS_COVERAGEPROFILES_PK ON CALC.CALCTASKS_COVERAGEPROFILES
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CALCTASKS_COVERAGEPROFILES ADD (
  CONSTRAINT CALCTASKS_COVERAGEPROFILES_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
