CREATE TABLE CALC.CLUTTERS_DESCS_FREQS_CLUTTERS
(
  CODE              NUMBER(3)                   NOT NULL,
  LINEAR_LOSS_DBKM  NUMBER(30,10),
  FLAT_LOSS_DB      NUMBER(30,10),
  REFLECTION_MHZ    NUMBER(30,10),
  NOTE              NCLOB,
  FREQ_ID           NUMBER(15)                  NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.PK_CLUTTERS_DESCS_FREQS_CLUTTERS ON CALC.CLUTTERS_DESCS_FREQS_CLUTTERS
(FREQ_ID, CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CLUTTERS_DESCS_FREQS_CLUTTERS ADD (
  CONSTRAINT PK_CLUTTERS_DESCS_FREQS_CLUTTERS
 PRIMARY KEY
 (FREQ_ID, CODE));
