CREATE TABLE CALC.CALCRESULTS
(
  ID                NUMBER(15)                  NOT NULL,
  TASK_ID           NUMBER(15)                  NOT NULL,
  STATUS_CODE       NUMBER(3)                   NOT NULL,
  STATUS_NAME       NVARCHAR2(50)               NOT NULL,
  STATUS_NOTE       NCLOB,
  CALLER_INSTANCE   NVARCHAR2(250)              NOT NULL,
  CALLER_RESULT_ID  VARCHAR2(36 BYTE)           NOT NULL,
  CREATED_DATE      TIMESTAMP(7) WITH TIME ZONE default CURRENT_TIMESTAMP AT TIME ZONE 'GMT' NOT NULL,
  START_TIME        TIMESTAMP(7) WITH TIME ZONE,
  FINISH_TIME       TIMESTAMP(7) WITH TIME ZONE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CALCRESULTS_PK ON CALC.CALCRESULTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CALCRESULTS ADD (
  CONSTRAINT CALCRESULTS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
