
CREATE TABLE CALC.CONTEXT_STATIONS_RECEIVER
(
  FREQ_MHZ           NUMBER(22,8)               NOT NULL,
  BW_KHZ             NUMBER(22,8)               NOT NULL,
  LOSS_DB            NUMBER(30,10)              NOT NULL,
  KTBF_DBM           NUMBER(30,10)              NOT NULL,
  THRESHOLD_DBM      NUMBER(30,10)              NOT NULL,
  POLARIZATION_CODE  NUMBER(3)                  NOT NULL,
  POLARIZATION_NAME  NVARCHAR2(50)              NOT NULL,
  FREQS_MHZ          BLOB                       NOT NULL,
  STATION_ID         NUMBER(15)                 NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.PK_CONTEXT_STATIONS_RECEIVER ON CALC.CONTEXT_STATIONS_RECEIVER
(STATION_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CONTEXT_STATIONS_RECEIVER ADD (
  CONSTRAINT PK_CONTEXT_STATIONS_RECEIVER
 PRIMARY KEY
 (STATION_ID));
