CREATE TABLE CALC.CHECKPOINTS_DATA
(
  ID             NUMBER(15),
  CREATED_DATE   TIMESTAMP(7) WITH TIME ZONE    DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT' NOT NULL,
  CHECKPOINT_ID  NUMBER(15)                     NOT NULL,
  DATA_CONTEXT   NVARCHAR2(250)                 NOT NULL,
  DATA_JSON      NCLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CHECKPOINTS_DATA_PK ON CALC.CHECKPOINTS_DATA
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CHECKPOINTS_DATA ADD (
  CONSTRAINT CHECKPOINTS_DATA_PK
 PRIMARY KEY
 (ID));