CREATE TABLE CALC.CALCRESULT_EVENTS
(
  ID            NUMBER(15)                      NOT NULL,
  CREATED_DATE  TIMESTAMP(7) WITH TIME ZONE     DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT' NOT NULL,
  RESULT_ID     NUMBER(15)                      NOT NULL,
  LEVEL_CODE    NUMBER(3)                       NOT NULL,
  LEVEL_NAME    NVARCHAR2(50)                   NOT NULL,
  CONTEXT       NVARCHAR2(250),
  MESSAGE       NCLOB,
  DATA_TYPE     NVARCHAR2(250),
  DATA_JSON     NCLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CALCRESULT_EVENTS_PK ON CALC.CALCRESULT_EVENTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CALCRESULT_EVENTS ADD (
  CONSTRAINT CALCRESULT_EVENTS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
