CREATE TABLE CALC.CLIENT_CONTEXTS_MAINBLOCK
(
  CONTEXT_ID       NUMBER(15)                   NOT NULL,
  MODEL_TYPE_CODE  NUMBER(3)                    NOT NULL,
  MODEL_TYPE_NAME  NVARCHAR2(100)               NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CCLIENT_CONTEXTS_MAINBLOCK_PK ON CALC.CLIENT_CONTEXTS_MAINBLOCK
(CONTEXT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CLIENT_CONTEXTS_MAINBLOCK ADD (
  CONSTRAINT CLIENT_CONTEXTS_MAINBLOCK_PK
 PRIMARY KEY
 (CONTEXT_ID));
