CREATE TABLE CALC.CALCRESULTS_POINTFIELDSTRENGTH
(
  FS_DBUVM   NUMBER(30,10),
  LEVEL_DBM  NUMBER(30,10),
  RESULT_ID  NUMBER(15,10)                      NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.PK_CALCRESULTS_POINTFIELDSTRENGTH ON CALC.CALCRESULTS_POINTFIELDSTRENGTH
(RESULT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CALCRESULTS_POINTFIELDSTRENGTH ADD (
  CONSTRAINT PK_CALCRESULTS_POINTFIELDSTRENGTH
 PRIMARY KEY
 (RESULT_ID));
