CREATE TABLE CALC.CHECKPOINTS
(
  ID            NUMBER(15),
  CREATED_DATE  TIMESTAMP(7) WITH TIME ZONE     DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT' NOT NULL,
  RESULT_ID     NUMBER(15)                      NOT NULL,
  STATUS_CODE   NUMBER(3)                       NOT NULL,
  STATUS_NAME   NVARCHAR2(50)                   NOT NULL,
  STATUS_NOTE   NCLOB,
  NAME          NVARCHAR2(250)                  NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CHECKPOINTS_PK ON CALC.CHECKPOINTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CHECKPOINTS ADD (
  CONSTRAINT CHECKPOINTS_PK
 PRIMARY KEY
 (ID));
