CREATE TABLE CALC.CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS_DETAIL
(
  ID					NUMBER(15)                NOT NULL,
  ORDER_ID				NUMBER(15)                NOT NULL,
  CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS_ID      NUMBER(15)                NOT NULL,
  ID_ICSM				NUMBER(15)                NOT NULL,
  TABLE_ICSM_NAME		NVARCHAR2(50)		      NOT NULL,
  ID_SENSOR				NUMBER(15)                NOT NULL,
  GLOBAL_GSID			NVARCHAR2(50)             NOT NULL,
  FREQ_MHZ				NUMBER(30,10)             NOT NULL,
  LEVEL_DBM				NUMBER(30,10)             NOT NULL,
  PERCENT				NUMBER(30,10)             NOT NULL,
  DATE_MEAS				TIMESTAMP(7)			  NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS_DETAIL_PK ON CALC.CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS_DETAIL
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS_DETAIL ADD (
  CONSTRAINT CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS_DETAIL_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
