CREATE TABLE CALC.CALCRESULTS_POINTFIELDSTRENGTH
(
  RESULT_ID  NUMBER(15)                         NOT NULL,
  FS_DBUVM   NUMBER(30,10),
  LEVEL_DBM  NUMBER(30,10)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CALCRESULTS_POINTFIELDSTRENGTH_PK ON CALC.CALCRESULTS_POINTFIELDSTRENGTH
(RESULT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CALCRESULTS_POINTFIELDSTRENGTH ADD (
  CONSTRAINT CALCRESULTS_POINTFIELDSTRENGTH_PK
 PRIMARY KEY
 (RESULT_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
