Insert into ICSM.XPROTOCOL_BANDWIDTH (ID,STANDARD_NAME,BW) values ('1','GSM-900','379,4');
Insert into ICSM.XPROTOCOL_BANDWIDTH (ID,STANDARD_NAME,BW) values ('2','GSM-1800','379,4');
Insert into ICSM.XPROTOCOL_BANDWIDTH (ID,STANDARD_NAME,BW) values ('3','UMTS','7500');
Insert into ICSM.XPROTOCOL_BANDWIDTH (ID,STANDARD_NAME,BW) values ('4','LTE-1800',null);
Insert into ICSM.XPROTOCOL_BANDWIDTH (ID,STANDARD_NAME,BW) values ('5','LTE-2600',null);
Insert into ICSM.XPROTOCOL_BANDWIDTH (ID,STANDARD_NAME,BW) values ('6','CDMA-800','1750');