CREATE TABLE XPROTOCOL_REPORT
(
  DATE_CREATED       DATE,
  STANDARD_NAME      VARCHAR2(150 CHAR),
  OWNER_NAME         VARCHAR2(100 CHAR),
  PERMISSION_NUMBER  VARCHAR2(200 CHAR),
  PERMISSION_START   DATE,
  PERMISSION_STOP    DATE,
  ADDRESS            VARCHAR2(1000 CHAR),
  LONGITUDE          VARCHAR2(40 CHAR),
  LATITUDE           VARCHAR2(40 CHAR),
  SENSOR_LON         VARCHAR2(40 CHAR),
  SENSOR_LAT         VARCHAR2(40 CHAR),
  SENSOR_NAME        VARCHAR2(100 CHAR),
  DATE_MEAS          DATE,
  S_FREQ_MHZ         NUMBER(30,10),
  S_BW               NUMBER(30,10),
  FREQ_MHZ           NUMBER(30,10),
  BW                 NUMBER(30,10),
  LEVEL_DBM          NUMBER(30,10),
  DESIG_EMISSION     VARCHAR2(25 CHAR),
  GLOBAL_SID         VARCHAR2(50 CHAR),
  CREATED_BY         VARCHAR2(150 CHAR),
  ID                 NUMBER(9)                  NOT NULL,
  VISN               VARCHAR2(250 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX XPROTOCOL_REPORT_PK ON XPROTOCOL_REPORT
(ID)
LOGGING
NOPARALLEL;

ALTER TABLE XPROTOCOL_REPORT ADD (
  CONSTRAINT XPROTOCOL_REPORT_PK
 PRIMARY KEY
 (ID));

GRANT INSERT, SELECT, UPDATE ON XPROTOCOL_REPORT TO PUBLIC;