SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[LINK_HEAD_REF_SPECTRUM](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEAD_REF_SPECTRUM_ID] [bigint] NULL,
	[SYNCHRO_PROCESS_ID] [bigint] NULL,
 CONSTRAINT [LINK_HEAD_REF_SPECTRUM_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
