if exists (select * from dbo.sysobjects where id = object_id(N'[ICSC].[ONLINE_MEAS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	drop table [ICSC].[ONLINE_MEAS]
go
CREATE TABLE [ICSC].[ONLINE_MEAS](
	[ID]			 [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_DATE]   [datetimeoffset](7) NOT NULL,
	[SRV_TOKEN]      [uniqueidentifier] NOT NULL,
	[STATUS_CODE]	 [tinyint]  NOT NULL,
	[STATUS_NOTE]	 [nvarchar](max) NULL,
	[SENSOR_ID]		 [bigint]	NOT NULL,
	[PERIOD_MINUTES] [int]		NOT NULL,


	[START_TIME]	 [datetimeoffset](7) NULL,
	[FINISH_TIME]	 [datetimeoffset](7) NULL,

	[SNR_TOKEN] [varbinary](max) NULL,
	[WEBSOCKET_URL] [nvarchar](max) NULL,
	
 CONSTRAINT [PK_ONLINE_MEAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
go


CREATE UNIQUE NONCLUSTERED INDEX [ONLINE_MEAS_SRV_TOKEN_UI] ON [ICSC].[ONLINE_MEAS]
(
	[SRV_TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO