SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[SYNCHRO_PROCESS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_BY] [nvarchar](100) NULL,
	[CREATED_DATE] [datetime] NULL,
	[STATUS] [nvarchar](40) NULL,
	[DATE_START] [datetime] NULL,
	[DATE_END] [datetime] NULL,
	[COUNT_RECORDS_IMPORTED] [int] NULL,
	[COUNT_RECORDS_OUT] [int] NULL,
	[COUNT_RECORDS_OUT_WITHOUT_EMIT] [int] NULL,
 CONSTRAINT [SYNCHRO_PROCESS_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
