SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[AREA](
	[ID] [bigint] NOT NULL,
	[NAME] [nvarchar](500) NULL,
	[TYPE_OF_AREA] [nvarchar](50) NULL,
	[CREATED_BY] [nvarchar](100) NULL,
	[CREATED_DATE] [datetime] NULL,
	[AREA_ID_ICSM] [int] NULL,
 CONSTRAINT [AREA_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
