SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[LINK_PROTOCOLS_WITH_EMITTINGS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PROBABILITY] [float] NULL,
	[STARTFREQ_MHZ] [float] NULL,
	[STOPFREQ_MHZ] [float] NULL,
	[CURRPOWER_DBM] [float] NULL,
	[REFLEVEL_DBM] [float] NULL,
	[MEANDEVFROM_REF] [float] NULL,
	[TRIGGERDEVFROM_REF] [float] NULL,
	[ROLL_OFF_ACTOR] [float] NULL,
	[STANDARD_BW] [float] NULL,
	[LEVELS_DISTRIBUTION_LVL] [varbinary](max) NULL,
	[LEVELS_DISTRIBUTION_COUNT] [varbinary](max) NULL,
	[LOSS_DB] [varbinary](max) NULL,
	[FREQ_KHZ] [varbinary](max) NULL,
	[SPECTRUM_STARTFREQ_MHZ] [float] NULL,
	[SPECTRUM_STEPFREQ_KHZ] [float] NULL,
	[T1] [int] NULL,
	[T2] [int] NULL,
	[MARKER_INDEX] [int] NULL,
	[BW_KHZ] [float] NULL,
	[CORRECT_ESTIM] [int] NULL,
	[TRACE_COUNT] [int] NULL,
	[SIGNALLEVEL_DBM] [float] NULL,
	[LEVELS_DBM] [varbinary](max) NULL,
	[CONTRAVENTION] [int] NULL,
	[WORK_TIME_START] [datetime] NULL,
	[WORK_TIME_STOP] [datetime] NULL,
	[PROTOCOLS_ID] [bigint] NULL,
 CONSTRAINT [LINK_PROTOCOLS_WITH_EMITTINGS_LINK_PROTOCOLS_WITH_EMITTIN_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


