SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[PROTOCOLS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PERMISSION_NUMBER] [nvarchar](400) NULL,
	[PERMISSION_START] [datetime] NULL,
	[PERMISSION_STOP] [datetime] NULL,
	[GLOBAL_SID] [nvarchar](100) NULL,
	[FREQ_MHZ] [float] NULL,
	[LEVEL_DBM] [float] NULL,
	[DISPERSION_LOW] [float] NULL,
	[DISPERSION_UP] [float] NULL,
	[PERCENT] [float] NULL,
	[SENSOR_LON] [float] NULL,
	[SENSOR_LAT] [float] NULL,
	[SENSOR_NAME] [nvarchar](200) NULL,
	[STATION_EXTENDED_ID] [bigint] NULL,
	[SYNCHRO_PROCESS_ID] [bigint] NULL,
	[SENSOR_ID] [bigint] NULL,
	[RADIO_CONTROL_FREQ_MHZ] [float] NULL,
	[RADIO_CONTROL_BW] [float] NULL,
	[DATE_MEAS_DAY] [tinyint] NULL,
	[DATE_MEAS_MONTH] [tinyint] NULL,
	[DATE_MEAS_YEAR] [smallint] NULL,
	[STATUS_MEAS] [nvarchar](8) NULL,
	[TIME_MEAS] [datetime] NULL,
 CONSTRAINT [PROTOCOLS_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO