SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[AMQP_EVENTS](
	[ID] [bigint] NOT NULL,
	[PROP_TYPE] [nvarchar](250) NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
 CONSTRAINT [PK_AMQP_EVENTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [ICSC].[AMQP_EVENTS] ADD  CONSTRAINT [DF_AMQP_EVENTS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO