SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[STATION_EXTENDED](
	[ID] [bigint] NOT NULL,
	[TABLE_NAME] [nvarchar](100) NULL,
	[TABLE_ID] [int] NULL,
	[STANDARD] [nvarchar](300) NULL,
	[STANDARD_NAME] [nvarchar](300) NULL,
	[OWNER_NAME] [nvarchar](200) NULL,
	[PERMISSION_NUMBER] [nvarchar](200) NULL,
	[PERMISSION_START] [datetime] NULL,
	[PERMISSION_STOP] [datetime] NULL,
	[ADDRESS] [nvarchar](2000) NULL,
	[LONGITUDE] [float] NULL,
	[LATITUDE] [float] NULL,
	[BW] [float] NULL,
	[DESIG_EMISSION] [nvarchar](50) NULL,
	[PROVINCE] [nvarchar](200) NULL,
	[PERMISSION_DATE_CANCEL] [datetime] NULL,
	[DOC_NUM] [nvarchar](200) NULL,
	[TEST_START_DATE] [datetime] NULL,
	[TEST_STOP_DATE] [datetime] NULL,
	[CURR_STATUS_STATION] [nvarchar](8) NULL,
	[STATUS_MEAS] [nvarchar](8) NULL,
	[PERMISS_GLOBAL_SID] [nvarchar](100) NULL,
	[STATION_TX_FREQ] [varbinary](max) NULL,
	[STATION_RX_FREQ] [varbinary](max) NULL,
	[STATION_CHANNEL] [varbinary](max) NULL,
	[STATION_NAME] [nvarchar](200) NULL,
	[OKPO] [nvarchar](40) NULL,
 CONSTRAINT [STATION_EXTENDED_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

