SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[ONLINE_MEAS](
	[ID]			 [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_DATE]   [datetimeoffset](7) NOT NULL,
	[SRV_TOKEN]      [uniqueidentifier] NOT NULL,
	[STATUS_CODE]	 [tinyint]  NOT NULL,
	[STATUS_NOTE]	 [nvarchar](max) NULL,
	[SENSOR_ID]		 [bigint]	NOT NULL,
	[PERIOD_MINUTES] [int]		NOT NULL,


	[START_TIME]	 [datetimeoffset](7) NULL,
	[FINISH_TIME]	 [datetimeoffset](7) NULL,

	[SNR_TOKEN] [varbinary](max) NULL,
	[WEBSOCKET_URL] [nvarchar](max) NULL,
	
 CONSTRAINT [PK_ONLINE_MEAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]