SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ICSC].[HEALTH_LOG](
[ID] [bigint] IDENTITY(1,1) NOT NULL,

[SENDER_LOG_ID] [BIGINT] NULL,
[SENDER_TYPE_CODE] [tinyint] NULL,
[SENDER_TYPE_NAME] [nvarchar](50) NULL,
[SENDER_INSTANCE] [nvarchar](250) NULL,
[SENDER_HOST] [nvarchar](250) NULL,

[SOURCE_TYPE_CODE] [tinyint] NOT NULL,
[SOURCE_TYPE_NAME] [nvarchar](50) NOT NULL,
[SOURCE_INSTANCE] [nvarchar](250) NOT NULL,
[SOURCE_TECHID] [nvarchar](250) NULL,
[SOURCE_HOST] [nvarchar](250) NULL,

[EVENT_CODE] [tinyint] NOT NULL,
[EVENT_NAME] [nvarchar](50) NOT NULL,
[EVENT_NOTE] [nvarchar](max) NULL,

[DISPATCH_TIME] [datetimeoffset](7) NOT NULL,
[RECEIVED_TIME] [datetimeoffset](7) NOT NULL,
[FORWARDED_TIME] [datetimeoffset](7)     NULL,

CONSTRAINT [PK_HEALTH_LOG] PRIMARY KEY CLUSTERED
(
[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
