--
-- Create Schema Script 
--   Database Version   : 12.2.0.1.0 
--   TOAD Version       : 9.7.2.5 
--   DB Connect String  : ICSMV41 
--   Schema             : CALC 
--   Script Created by  : ICSC 
--   Script Created at  : 11.08.2020 07:49:07 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Users: 1           Sys Privs: 16        
-- 
--   Functions: 1       Lines of Code: 320 
--   Indexes: 50        Columns: 57         
--   Sequences: 46 
--   Tables: 51         Columns: 506        


CREATE USER CALC
  IDENTIFIED BY CALC
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 16 System Privileges for CALC 
  GRANT UNLIMITED TABLESPACE TO CALC;
  GRANT CREATE TRIGGER TO CALC;
  GRANT DROP ANY TRIGGER TO CALC;
  GRANT CREATE PROCEDURE TO CALC;
  GRANT CREATE SEQUENCE TO CALC;
  GRANT DELETE ANY TABLE TO CALC;
  GRANT CREATE SESSION TO CALC;
  GRANT ALTER ANY PROCEDURE TO CALC;
  GRANT DROP ANY VIEW TO CALC;
  GRANT CREATE VIEW TO CALC;
  GRANT ALTER ANY TABLE TO CALC;
  GRANT DROP ANY PROCEDURE TO CALC;
  GRANT CREATE TABLE TO CALC;
  GRANT ALTER ANY TRIGGER TO CALC;
  GRANT UNLIMITED TABLESPACE TO CALC;
  GRANT DROP ANY TABLE TO CALC;


CREATE SEQUENCE CALCRESULTS_GN06_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCRESULTS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCRESULTS_POINTFIELDSTRENGTH_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCRESULTS_STATION_CALIBRATION_DRIVE_TEST_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCRESULTS_STATION_CALIBRATION_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCRESULTS_STATION_CALIBRATION_STA_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCRESULT_EVENTS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCTASKS_COVERAGEPROFILES_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCTASKS_GN06_ARGS_DEF_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCTASKS_GN06_ARGS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCTASKS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCTASKS_POINTFIELDSTRENGTH_ARGS_DEF_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCTASKS_POINTFIELDSTRENGTH_ARGS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCTASKS_STATION_CALIBRATION_ARGS_DEF_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CALCTASKS_STATION_CALIBRATION_ARGS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_ABSORPTION_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_ADDITIONAL_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_ATMOSPHERIC_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_CLUTTER_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_DIFFRACTION_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_DUCTING_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_GLOBALPARAMS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_MAINBLOCK_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_REFLECTION_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_SUBPATHDIFFRACTION_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLIENT_CONTEXTS_TROPO_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLUTTERS_DESCS_CLUTTERS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLUTTERS_DESCS_FREQS_CLUTTERS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLUTTERS_DESCS_FREQS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CLUTTERS_DESCS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CONTEXT_PLANNEDCALCTASK_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CONTEXT_STATIONS_ANTENNA_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CONTEXT_STATIONS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CONTEXT_STATIONS_RECEIVER_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CONTEXT_STATIONS_SITE_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CONTEXT_STATIONS_TRANSMITTER_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CONTEXT_STATION_COORDINATES_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE CONTEXT_STATION_PATTERNS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE GN06_AFFECTED_ADM_RESULT_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE GN06_ALLOTMENT_OR_ASSIGNMENT_RESULT_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE GN06_CONTOURS_RESULT_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE PROJECTS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE PROJECT_MAPS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE PROJECT_MAP_CONTENTS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE SEQUENCE PROJECT_MAP_CONTENT_SOURCES_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 2
  NOORDER;


CREATE TABLE GN06_CONTOURS_RESULT
(
  ID                   NUMBER(15),
  CALCRESULTS_GN06_ID  NUMBER(15),
  CONTOUR_TYPE         NUMBER(3),
  DISTANCE             NUMBER(9),
  FS                   NUMBER(30,10),
  AFFECTED_ADM         NVARCHAR2(50),
  POINTS_COUNT         NUMBER(9),
  CONTOURS_POINTS      NCLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROJECT_MAPS
(
  ID                   NUMBER(15),
  PROJECT_ID           NUMBER(15),
  MAP_NAME             NVARCHAR2(250),
  MAP_NOTE             NCLOB,
  OWNER_INSTANCE       NVARCHAR2(250),
  OWNER_MAP_ID         VARCHAR2(36 BYTE),
  CREATED_DATE         TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  STATUS_CODE          NUMBER(3),
  STATUS_NAME          NVARCHAR2(50),
  STATUS_NOTE          NCLOB,
  STEP_UNIT            NVARCHAR2(10),
  OWNER_AXIS_X_NUMBER  NUMBER(9),
  OWNER_AXIS_X_STEP    NUMBER(9),
  OWNER_AXIS_Y_NUMBER  NUMBER(9),
  OWNER_AXIS_Y_STEP    NUMBER(9),
  OWNER_CRD_UPL_X      NUMBER(9),
  OWNER_CRD_UPL_Y      NUMBER(9),
  AXIS_X_NUMBER        NUMBER(9),
  AXIS_X_STEP          NUMBER(9),
  AXIS_Y_NUMBER        NUMBER(9),
  AXIS_Y_STEP          NUMBER(9),
  CRD_UPL_X            NUMBER(9),
  CRD_UPL_Y            NUMBER(9),
  CRD_LWR_X            NUMBER(9),
  CRD_LWR_Y            NUMBER(9),
  SOURCE_TYPE_CODE     NUMBER(3),
  SOURCE_TYPE_NAME     NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROJECT_MAP_CONTENTS
(
  ID                NUMBER(15),
  MAP_ID            NUMBER(15),
  CREATED_DATE      TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  TYPE_CODE         NUMBER(3),
  TYPE_NAME         NVARCHAR2(50),
  STEP_DATATYPE     NVARCHAR2(50),
  STEP_DATASIZE     NUMBER(3),
  SOURCE_COUNT      NUMBER(9),
  SOURCE_COVERAGE   NUMBER(22,8),
  CONTENT_SIZE      NUMBER(9),
  CONTENT_TYPE      NVARCHAR2(250),
  CONTENT_ENCODING  NVARCHAR2(250),
  CONTENT           BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROJECT_MAP_CONTENT_SOURCES
(
  ID              NUMBER(15),
  CONTENT_ID      NUMBER(15),
  INFOC_MAP_ID    NUMBER(15),
  INFOC_MAP_NAME  NVARCHAR2(450),
  COVERAGE        NUMBER(22,8),
  CRD_UPL_X       NUMBER(9),
  CRD_UPL_Y       NUMBER(9),
  CRD_LWR_X       NUMBER(9),
  CRD_LWR_Y       NUMBER(9),
  PRIORITY_CODE   NUMBER(3),
  PRIORITY_NAME   NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTEXT_STATIONS_TRANSMITTER
(
  FREQ_MHZ           NUMBER(30,10),
  BW_KHZ             NUMBER(22,8),
  LOSS_DB            NUMBER(30,10),
  MAX_POWER_DBM      NUMBER(30,10),
  POLARIZATION_CODE  NUMBER(3),
  POLARIZATION_NAME  NVARCHAR2(50),
  FREQS_MHZ          BLOB,
  STATION_ID         NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTEXT_STATIONS_SITE
(
  ID       NUMBER(15),
  LON_DEC  NUMBER(22,8),
  LAT_DEC  NUMBER(22,8),
  ALT_M    NUMBER(22,8)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTEXT_STATIONS_RECEIVER
(
  FREQ_MHZ           NUMBER(22,8),
  BW_KHZ             NUMBER(22,8),
  LOSS_DB            NUMBER(30,10),
  KTBF_DBM           NUMBER(30,10),
  THRESHOLD_DBM      NUMBER(30,10),
  POLARIZATION_CODE  NUMBER(3),
  POLARIZATION_NAME  NVARCHAR2(50),
  FREQS_MHZ          BLOB,
  STATION_ID         NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTEXT_STATIONS_ANTENNA
(
  ID                NUMBER(15),
  GAIN_DB           NUMBER(30,10),
  TILT_DEG          NUMBER(22,8),
  AZIMUTH_DEG       NUMBER(22,8),
  XPD_DB            NUMBER(30,10),
  ITU_PATTERN_CODE  NUMBER(3),
  ITU_PATTERN_NAME  NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTEXT_STATIONS
(
  ID               NUMBER(15),
  CONTEXT_ID       NUMBER(15),
  CREATED_DATE     TIMESTAMP(7) WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  NAME             NVARCHAR2(250),
  CALL_SIGN        NVARCHAR2(50),
  STATE_CODE       NUMBER(3),
  STATE_NAME       NVARCHAR2(50),
  STANDARD         NVARCHAR2(50),
  EXTERNAL_CODE    NVARCHAR2(50),
  EXTERNAL_SOURCE  NVARCHAR2(50),
  MODIFIED_DATE    TIMESTAMP(7) WITH TIME ZONE,
  LICENSE_GSID     NVARCHAR2(50),
  REAL_GSID        NVARCHAR2(50),
  REGION_CODE      NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTEXT_STATION_PATTERNS
(
  ANTENNA_PLANE  NVARCHAR2(1),
  WAVE_PLANE     NVARCHAR2(1),
  LOSS_DB        BLOB,
  ANGLE_DEG      BLOB,
  STATION_ID     NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_ADDITIONAL
(
  MODEL_TYPE_CODE  NUMBER(3),
  MODEL_TYPE_NAME  NVARCHAR2(100),
  AVAILABLE        NUMBER(1),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLUTTERS_DESCS
(
  ID             NUMBER(15),
  INFOC_DESC_ID  NUMBER(15),
  MAP_ID         NUMBER(15),
  CREATED_DATE   TIMESTAMP(7) WITH TIME ZONE    DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  NAME           NVARCHAR2(450),
  NOTE           NCLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_TROPO
(
  MODEL_TYPE_CODE  NUMBER(3),
  MODEL_TYPE_NAME  NVARCHAR2(100),
  AVAILABLE        NUMBER(1),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_SUBPATHDIFFRACTION
(
  MODEL_TYPE_CODE  NUMBER(3),
  MODEL_TYPE_NAME  NVARCHAR2(100),
  AVAILABLE        NUMBER(1),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_REFLECTION
(
  AVAILABLE   NUMBER(1),
  CONTEXT_ID  NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_MAINBLOCK
(
  MODEL_TYPE_CODE  NUMBER(3),
  MODEL_TYPE_NAME  NVARCHAR2(100),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_GLOBALPARAMS
(
  TIME_PC          NUMBER(22,8),
  LOCATION_PC      NUMBER(22,8),
  EARTH_RADIUS_KM  NUMBER(22,8),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_DUCTING
(
  AVAILABLE   NUMBER(1),
  CONTEXT_ID  NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_DIFFRACTION
(
  MODEL_TYPE_CODE  NUMBER(3),
  MODEL_TYPE_NAME  NVARCHAR2(100),
  AVAILABLE        NUMBER(1),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_CLUTTER
(
  MODEL_TYPE_CODE  NUMBER(3),
  MODEL_TYPE_NAME  NVARCHAR2(100),
  AVAILABLE        NUMBER(1),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_ATMOSPHERIC
(
  MODEL_TYPE_CODE  NUMBER(3),
  MODEL_TYPE_NAME  NVARCHAR2(100),
  AVAILABLE        NUMBER(1),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS_ABSORPTION
(
  MODEL_TYPE_CODE  NUMBER(3),
  MODEL_TYPE_NAME  NVARCHAR2(100),
  AVAILABLE        NUMBER(1),
  CONTEXT_ID       NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLIENT_CONTEXTS
(
  ID                NUMBER(15),
  BASE_CONTEXT_ID   NUMBER(15),
  PROJECT_ID        NUMBER(15),
  CONTEXT_NAME      NVARCHAR2(250),
  CONTEXT_NOTE      NCLOB,
  OWNER_INSTANCE    NVARCHAR2(250),
  OWNER_CONTEXT_ID  VARCHAR2(36 BYTE),
  CREATED_DATE      TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  TYPE_CODE         NUMBER(3),
  TYPE_NAME         NVARCHAR2(50),
  STATUS_CODE       NUMBER(3),
  STATUS_NAME       NVARCHAR2(50),
  STATUS_NOTE       NCLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCTASKS_GN06_ARGS
(
  TASK_ID                          NUMBER(15),
  AZIMUTH_STEP_DEG                 NUMBER(22,8),
  ADDITIONAL_CONTOURS_BY_DISTANCE  NUMBER(1),
  INFOC_MEAS_RESULTS               BLOB,
  CONTURE_BY_FIELD_STRENGTH        NUMBER(1),
  FIELD_STRENGTH                   BLOB,
  SUBSCRIBERS_HEIGHT               NUMBER(9),
  PERCENTAGE_TIME                  NUMBER(30,10),
  USE_EFFECTIVE_HEIGHT             NUMBER(1),
  CALCULATION_TYPE_CODE            NUMBER(3),
  CALCULATION_TYPE_NAME            VARCHAR2(50 BYTE),
  BROADCASTING_EXTEND              NCLOB,
  STEP_BETWEEN_BUNDARY_POINTS      NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCTASKS_GN06_ARGS_DEF
(
  TASK_ID                          NUMBER(15),
  AZIMUTH_STEP_DEG                 NUMBER(22,8),
  ADDITIONAL_CONTOURS_BY_DISTANCE  NUMBER(1),
  INFOC_MEAS_RESULTS               BLOB,
  CONTURE_BY_FIELD_STRENGTH        NUMBER(1),
  FIELD_STRENGTH                   BLOB,
  SUBSCRIBERS_HEIGHT               NUMBER(9),
  PERCENTAGE_TIME                  NUMBER(30,10),
  USE_EFFECTIVE_HEIGHT             NUMBER(1),
  CALCULATION_TYPE_CODE            NUMBER(3),
  CALCULATION_TYPE_NAME            VARCHAR2(50 BYTE),
  BROADCASTING_EXTEND              NCLOB,
  STEP_BETWEEN_BUNDARY_POINTS      NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE GN06_AFFECTED_ADM_RESULT
(
  ID                   NUMBER(15),
  CALCRESULTS_GN06_ID  NUMBER(15),
  ADM                  NVARCHAR2(50),
  TYPE_AFFECTED        NVARCHAR2(50),
  AFFECTED_SERVICES    NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE GN06_ALLOTMENT_OR_ASSIGNMENT_RESULT
(
  ID                      NUMBER(15),
  CALCRESULTS_GN06_ID     NUMBER(15),
  ADM                     NVARCHAR2(50),
  TYPE_TABLE              NVARCHAR2(50),
  NAME                    NVARCHAR2(100),
  FREQ_MHZ                NUMBER(30,10),
  LON_DEC                 NUMBER(30,10),
  LAT_DEC                 NUMBER(30,10),
  MAX_EFFECTIVE_HEIGHT_M  NUMBER(9),
  POLAR                   NVARCHAR2(100),
  ERPH_DBW                NUMBER(22,8),
  ERPV_DBW                NUMBER(22,8),
  ANTENNA_DIRECTIONAL     NVARCHAR2(50),
  ADM_REF_ID              NVARCHAR2(100),
  CONTOURS_POINTS         NCLOB,
  SOURCE                  NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MD_APPLICATIONS
(
  ID                 NUMBER,
  NAME               VARCHAR2(4000 BYTE),
  DESCRIPTION        VARCHAR2(4000 BYTE),
  BASE_DIR           VARCHAR2(4000 BYTE),
  OUTPUT_DIR         VARCHAR2(4000 BYTE),
  BACKUP_DIR         VARCHAR2(4000 BYTE),
  INPLACE            NUMBER,
  PROJECT_ID_FK      NUMBER,
  SECURITY_GROUP_ID  NUMBER                     DEFAULT 0,
  CREATED_ON         DATE                       DEFAULT sysdate,
  CREATED_BY         VARCHAR2(255 BYTE),
  LAST_UPDATED_ON    DATE,
  LAST_UPDATED_BY    VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MD_APPLICATIONFILES
(
  ID                  NUMBER,
  APPLICATIONS_ID_FK  NUMBER,
  NAME                VARCHAR2(200 BYTE),
  URI                 VARCHAR2(4000 BYTE),
  TYPE                VARCHAR2(100 BYTE),
  STATE               VARCHAR2(100 BYTE),
  LANGUAGE            VARCHAR2(100 BYTE),
  LOC                 NUMBER,
  SECURITY_GROUP_ID   NUMBER                    DEFAULT 0,
  CREATED_ON          DATE                      DEFAULT sysdate,
  CREATED_BY          VARCHAR2(4000 BYTE),
  UPDATED_ON          DATE,
  UPDATED_BY          VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MD_FILE_ARTIFACTS
(
  ID                   NUMBER,
  APPLICATIONFILES_ID  NUMBER,
  PATTERN              VARCHAR2(4000 BYTE),
  STRING_FOUND         VARCHAR2(4000 BYTE),
  STRING_REPLACED      VARCHAR2(4000 BYTE),
  TYPE                 VARCHAR2(200 BYTE),
  STATUS               VARCHAR2(4000 BYTE),
  LINE                 NUMBER,
  PATTERN_START        NUMBER,
  PATTERN_END          NUMBER,
  DUE_DATE             DATE,
  DB_TYPE              VARCHAR2(100 BYTE),
  CODE_TYPE            VARCHAR2(1000 BYTE),
  DESCRIPTION          VARCHAR2(4000 BYTE),
  PRIORITY             INTEGER,
  SECURITY_GROUP_ID    VARCHAR2(20 BYTE)        DEFAULT '0',
  CREATED_ON           DATE                     DEFAULT sysdate,
  CREATED_BY           VARCHAR2(4000 BYTE),
  LAST_UPDATED         DATE,
  LAST_UPDATED_BY      VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MD_TABLESPACES
(
  ID                 NUMBER,
  SCHEMA_ID_FK       NUMBER,
  TABLESPACE_NAME    VARCHAR2(4000 BYTE),
  NATIVE_SQL         CLOB,
  NATIVE_KEY         VARCHAR2(4000 BYTE),
  COMMENTS           VARCHAR2(4000 BYTE),
  SECURITY_GROUP_ID  NUMBER                     DEFAULT 0,
  CREATED_ON         DATE                       DEFAULT sysdate,
  CREATED_BY         VARCHAR2(255 BYTE),
  LAST_UPDATED_ON    DATE,
  LAST_UPDATED_BY    VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MD_USER_PRIVILEGES
(
  ID                 NUMBER,
  USER_ID_FK         NUMBER,
  PRIVILEGE_ID_FK    NUMBER,
  SECURITY_GROUP_ID  NUMBER                     DEFAULT 0,
  CREATED_ON         DATE                       DEFAULT sysdate,
  CREATED_BY         VARCHAR2(255 BYTE),
  LAST_UPDATED_ON    DATE,
  LAST_UDPATED_BY    VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCTASKS_POINTFIELDSTRENGTH_ARGS_DEF
(
  STATION_ID     NUMBER(15),
  POINT_LON_DEC  NUMBER(22,8),
  POINT_LAT_DEC  NUMBER(22,8),
  POINT_ALT_M    NUMBER(22,8),
  TASK_ID        NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCTASKS_POINTFIELDSTRENGTH_ARGS
(
  STATION_ID     NUMBER(15),
  POINT_LON_DEC  NUMBER(22,8),
  POINT_LAT_DEC  NUMBER(22,8),
  POINT_ALT_M    NUMBER(22,8),
  TASK_ID        NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCTASKS_COVERAGEPROFILES
(
  ID             NUMBER(15),
  MODE_CODE      NUMBER(3),
  MODE_NAME      NVARCHAR2(50),
  POINTS_CRDS_X  BLOB,
  POINTS_CRDS_Y  BLOB,
  RESULT_PATH    NVARCHAR2(450)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCTASKS
(
  ID              NUMBER(15),
  CONTEXT_ID      NUMBER(15),
  TYPE_CODE       NUMBER(9),
  TYPE_NAME       NVARCHAR2(250),
  STATUS_CODE     NUMBER(3),
  STATUS_NAME     NVARCHAR2(50),
  STATUS_NOTE     NCLOB,
  OWNER_INSTANCE  NVARCHAR2(250),
  OWNER_TASK_ID   VARCHAR2(36 BYTE),
  CREATED_DATE    TIMESTAMP(7) WITH TIME ZONE   DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  MAP_NAME        NVARCHAR2(250)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCRESULTS_STATION_CALIBRATION_STA
(
  ID                                  NUMBER(15),
  CALCRESULTS_STATION_CALIBRATION_ID  NUMBER(15),
  EXTERNAL_SOURCE                     NVARCHAR2(50),
  EXTERNAL_CODE                       NVARCHAR2(50),
  LICENSE_GSID                        NVARCHAR2(50),
  REAL_GSID                           NVARCHAR2(50),
  RESULT_STATION_STATUS               NVARCHAR2(50),
  MAX_CORELLATION                     NUMBER(22,8),
  OLD_ALTITUDE_M                      NUMBER(9),
  OLD_TILT_DEG                        NUMBER(22,8),
  OLD_AZIMUTRH_DEG                    NUMBER(22,8),
  OLD_LAT_DEG                         NUMBER(30,10),
  OLD_LON_DEG                         NUMBER(30,10),
  OLD_POWER_DB                        NUMBER(30,10),
  OLD_FREQ_MHZ                        NUMBER(30,10),
  NEW_ALTITUDE_M                      NUMBER(9),
  NEW_TILT_DEG                        NUMBER(22,8),
  NEW_AZIMUTRH_DEG                    NUMBER(22,8),
  NEW_LAT_DEG                         NUMBER(30,10),
  NEW_LON_DEG                         NUMBER(30,10),
  NEW_POWER_DB                        NUMBER(30,10),
  STATION_MONITORING_ID               NUMBER(15),
  FREQ_MHZ                            NUMBER(30,10),
  STANDARD                            NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCRESULTS_STATION_CALIBRATION_DRIVE_TEST
(
  ID                                  NUMBER(15),
  CALCRESULTS_STATION_CALIBRATION_ID  NUMBER(15),
  EXTERNAL_SOURCE                     NVARCHAR2(50),
  EXTERNAL_CODE                       NVARCHAR2(50),
  STATION_GSID                        NVARCHAR2(50),
  MEAS_GSID                           NVARCHAR2(50),
  RESULT_DRIVE_TEST_STATUS            NVARCHAR2(50),
  MAX_PERCENT_CORELLATION             NUMBER(22,8),
  COUNT_POINTS_IN_DRIVE_TEST          NUMBER(9),
  DRIVE_TEST_ID                       NUMBER(15),
  LINK_STATION_MONITORING_ID          NUMBER(15),
  FREQ_MHZ                            NUMBER(22,8),
  STANDARD                            NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCRESULTS_STATION_CALIBRATION
(
  ID                         NUMBER(15),
  RESULT_ID                  NUMBER(15),
  TIME_START                 TIMESTAMP(7) WITH TIME ZONE,
  STANDARD                   NVARCHAR2(50),
  AREA_NAME                  NVARCHAR2(1000),
  NUMBER_STATION             NUMBER(9),
  NUMBER_STATION_IN_CONTOUR  NUMBER(9),
  COUNT_STATION_CS           NUMBER(9),
  COUNT_STATION_NS           NUMBER(9),
  COUNT_STATION_IT           NUMBER(9),
  COUNT_STATION_NF           NUMBER(9),
  COUNT_STATION_UN           NUMBER(9),
  COUNT_MEAS_GSID            NUMBER(9),
  COUNT_MEAS_GSID_LS         NUMBER(9),
  COUNT_MEAS_GSID_IT         NUMBER(9),
  PARAMETERS_TASK_ID         NUMBER(15),
  PERCENT_COMPLETE           NUMBER(9)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCRESULTS_POINTFIELDSTRENGTH
(
  FS_DBUVM   NUMBER(30,10),
  LEVEL_DBM  NUMBER(30,10),
  RESULT_ID  NUMBER(15,10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCRESULTS
(
  ID                NUMBER(15),
  TASK_ID           NUMBER(15),
  STATUS_CODE       NUMBER(3),
  STATUS_NAME       NVARCHAR2(50),
  STATUS_NOTE       NCLOB,
  CALLER_INSTANCE   NVARCHAR2(250),
  CALLER_RESULT_ID  VARCHAR2(36 BYTE),
  CREATED_DATE      TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  START_TIME        TIMESTAMP(7) WITH TIME ZONE,
  FINISH_TIME       TIMESTAMP(7) WITH TIME ZONE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROJECTS
(
  ID                NUMBER(15),
  PROJECT_NAME      NVARCHAR2(250),
  PROJECT_NOTE      NCLOB,
  OWNER_INSTANCE    NVARCHAR2(250),
  OWNER_PROJECT_ID  VARCHAR2(36 BYTE),
  CREATED_DATE      TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  STATUS_CODE       NUMBER(3),
  STATUS_NAME       NVARCHAR2(50),
  STATUS_NOTE       NCLOB,
  PROJECTION        NVARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTEXT_STATION_COORDINATES
(
  ATDI_X      NUMBER(9),
  ATDI_Y      NUMBER(9),
  EPSG_X      NUMBER(22,8),
  EPSG_Y      NUMBER(22,8),
  STATION_ID  NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CONTEXT_PLANNEDCALCTASK
(
  ID            NUMBER(15),
  CONTEXT_ID    NUMBER(15),
  TYPE_CODE     NUMBER(9),
  TYPE_NAME     NVARCHAR2(250),
  START_NUMBER  NUMBER(9),
  MAP_NAME      NVARCHAR2(250),
  NOTE          NCLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLUTTERS_DESCS_FREQS_CLUTTERS
(
  CODE              NUMBER(3),
  LINEAR_LOSS_DBKM  NUMBER(30,10),
  FLAT_LOSS_DB      NUMBER(30,10),
  REFLECTION_MHZ    NUMBER(30,10),
  NOTE              NCLOB,
  FREQ_ID           NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLUTTERS_DESCS_FREQS
(
  ID                NUMBER(15),
  CLUTTERS_DESC_ID  NUMBER(15),
  FREQ_MHZ          NUMBER(22,8),
  NOTE              NCLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLUTTERS_DESCS_CLUTTERS
(
  CODE              NUMBER(3),
  NAME              NVARCHAR2(150),
  NOTE              NCLOB,
  HEIGHT_M          NUMBER(3),
  CLUTTERS_DESC_ID  NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCTASKS_STATION_CALIBRATION_ARGS_DEF
(
  STANDARD                             NVARCHAR2(50),
  TASK_ID                              NUMBER(15),
  CORRELATION_THRESHOLD_HARD           NUMBER(22,8),
  CORRELATION_THRESHOLD_WEAK           NUMBER(22,8),
  TRUST_OLD_RESULTS                    NUMBER(1),
  USE_MEASUREMENT_SAME_GSID            NUMBER(1),
  DISTANCE_AROUND_CONTOUR_KM           NUMBER(9),
  MIN_NUMBER_POINT_FOR_CORRELATION     NUMBER(9),
  MIN_RANGE_MEASUREMENTS_DBMKV         NUMBER(22,8),
  MAX_RANGE_MEASUREMENTS_DBMKV         NUMBER(22,8),
  CORRELATION_DISTANCE_M               NUMBER(9),
  DELTA_DB                             NUMBER(22,8),
  MAX_ANTENNAS_PATTERN_LOSS_DB         NUMBER(22,8),
  DETAIL                               NUMBER(1),
  ALTITUDE_STATION                     NUMBER(1),
  SHIFT_ALTITUDE_STATION_MIN_M         NUMBER(9),
  SHIFT_ALTITUDE_STATION_MAX_M         NUMBER(9),
  SHIFT_ALTITUDE_STATION_STEP_M        NUMBER(9),
  MAX_DEVIATION_ALTITUDE_STATION_M     NUMBER(9),
  TILT_STATION                         NUMBER(1),
  SHIFT_TILT_STATION_MIN_DEG           NUMBER(22,8),
  SHIFT_TILT_STATION_MAX_DEG           NUMBER(22,8),
  SHIFT_TILT_STATION_STEP_DEG          NUMBER(22,8),
  MAX_DEVIATION_TILT_STATION_DEG       NUMBER(22,8),
  AZIMUTH_STATION                      NUMBER(1),
  SHIFT_AZIMUTH_STATION_MIN_DEG        NUMBER(22,8),
  SHIFT_AZIMUTH_STATION_MAX_DEG        NUMBER(22,8),
  SHIFT_AZIMUTH_STATION_STEP_DEG       NUMBER(22,8),
  MAX_DEVIATION_AZIMUTH_STATION_DEG    NUMBER(22,8),
  COORDINATES_STATION                  NUMBER(1),
  SHIFT_COORDINATES_STATION_M          NUMBER(9),
  SHIFT_COORDINATES_STATION_STEP_M     NUMBER(9),
  MAX_DEVIATION_COORDINATES_STATION_M  NUMBER(9),
  POWER_STATION                        NUMBER(1),
  SHIFT_POWER_STATION_MIN_DB           NUMBER(22,8),
  SHIFT_POWER_STATION_MAX_DB           NUMBER(22,8),
  SHIFT_POWER_STATION_STEP_DB          NUMBER(22,8),
  CASCADE_TUNING                       NUMBER(1),
  NUMBER_CASCADE                       NUMBER(9),
  DETAIL_OF_CASCADE                    NUMBER(9),
  METHOD                               NUMBER(3),
  INFOC_MEAS_RESULTS                   BLOB,
  STATION_IDS                          BLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCTASKS_STATION_CALIBRATION_ARGS
(
  STANDARD                             NVARCHAR2(50),
  TASK_ID                              NUMBER(15),
  CORRELATION_THRESHOLD_HARD           NUMBER(22,8),
  CORRELATION_THRESHOLD_WEAK           NUMBER(22,8),
  TRUST_OLD_RESULTS                    NUMBER(1),
  USE_MEASUREMENT_SAME_GSID            NUMBER(1),
  DISTANCE_AROUND_CONTOUR_KM           NUMBER(9),
  MIN_NUMBER_POINT_FOR_CORRELATION     NUMBER(9),
  MIN_RANGE_MEASUREMENTS_DBMKV         NUMBER(22,8),
  MAX_RANGE_MEASUREMENTS_DBMKV         NUMBER(22,8),
  CORRELATION_DISTANCE_M               NUMBER(9),
  DELTA_DB                             NUMBER(22,8),
  MAX_ANTENNAS_PATTERN_LOSS_DB         NUMBER(22,8),
  DETAIL                               NUMBER(1),
  ALTITUDE_STATION                     NUMBER(1),
  SHIFT_ALTITUDE_STATION_MIN_M         NUMBER(9),
  SHIFT_ALTITUDE_STATION_MAX_M         NUMBER(9),
  SHIFT_ALTITUDE_STATION_STEP_M        NUMBER(9),
  MAX_DEVIATION_ALTITUDE_STATION_M     NUMBER(9),
  TILT_STATION                         NUMBER(1),
  SHIFT_TILT_STATION_MIN_DEG           NUMBER(22,8),
  SHIFT_TILT_STATION_MAX_DEG           NUMBER(22,8),
  SHIFT_TILT_STATION_STEP_DEG          NUMBER(22,8),
  MAX_DEVIATION_TILT_STATION_DEG       NUMBER(22,8),
  AZIMUTH_STATION                      NUMBER(1),
  SHIFT_AZIMUTH_STATION_MIN_DEG        NUMBER(22,8),
  SHIFT_AZIMUTH_STATION_MAX_DEG        NUMBER(22,8),
  SHIFT_AZIMUTH_STATION_STEP_DEG       NUMBER(22,8),
  MAX_DEVIATION_AZIMUTH_STATION_DEG    NUMBER(22,8),
  COORDINATES_STATION                  NUMBER(1),
  SHIFT_COORDINATES_STATION_M          NUMBER(9),
  SHIFT_COORDINATES_STATION_STEP_M     NUMBER(9),
  MAX_DEVIATION_COORDINATES_STATION_M  NUMBER(9),
  POWER_STATION                        NUMBER(1),
  SHIFT_POWER_STATION_MIN_DB           NUMBER(22,8),
  SHIFT_POWER_STATION_MAX_DB           NUMBER(22,8),
  SHIFT_POWER_STATION_STEP_DB          NUMBER(22,8),
  CASCADE_TUNING                       NUMBER(1),
  NUMBER_CASCADE                       NUMBER(9),
  DETAIL_OF_CASCADE                    NUMBER(9),
  METHOD                               NUMBER(3),
  INFOC_MEAS_RESULTS                   BLOB,
  STATION_IDS                          BLOB

)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCRESULTS_GN06
(
  ID         NUMBER(15),
  RESULT_ID  NUMBER(15)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CALCRESULT_EVENTS
(
  ID            NUMBER(15),
  CREATED_DATE  TIMESTAMP(7) WITH TIME ZONE     DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  RESULT_ID     NUMBER(15),
  LEVEL_CODE    NUMBER(3),
  LEVEL_NAME    NVARCHAR2(50),
  CONTEXT       NVARCHAR2(250),
  MESSAGE       NCLOB,
  DATA_TYPE     NVARCHAR2(250),
  DATA_JSON     NCLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_GN06_CONTOURS_RESULT ON GN06_CONTOURS_RESULT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROJECTS_PK ON PROJECTS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROJECT_MAPS_PK ON PROJECT_MAPS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROJECT_MAP_CONTENTS_PK ON PROJECT_MAP_CONTENTS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROJECT_MAP_CONTENT_SOURCES_PK ON PROJECT_MAP_CONTENT_SOURCES
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CONTEXT_STATIONS_TRANSMITTER ON CONTEXT_STATIONS_TRANSMITTER
(STATION_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CONTEXT_STATIONS_SITE_PK ON CONTEXT_STATIONS_SITE
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CONTEXT_STATIONS_RECEIVER ON CONTEXT_STATIONS_RECEIVER
(STATION_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CONTEXT_STATIONS_ANTENNA_PK ON CONTEXT_STATIONS_ANTENNA
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CONTEXT_STATIONS_PK ON CONTEXT_STATIONS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_ADDITIONAL ON CLIENT_CONTEXTS_ADDITIONAL
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CLUTTERS_DESCS_PK ON CLUTTERS_DESCS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_TROPO ON CLIENT_CONTEXTS_TROPO
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CLIENT_CONTEXTS_SUBPATHDIFFRACTION ON CLIENT_CONTEXTS_SUBPATHDIFFRACTION
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_REFLECTION ON CLIENT_CONTEXTS_REFLECTION
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_MAINBLOCK ON CLIENT_CONTEXTS_MAINBLOCK
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_GLOBALPARAMS ON CLIENT_CONTEXTS_GLOBALPARAMS
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_DUCTING ON CLIENT_CONTEXTS_DUCTING
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_DIFFRACTION ON CLIENT_CONTEXTS_DIFFRACTION
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_CLUTTER ON CLIENT_CONTEXTS_CLUTTER
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_ATMOSPHERIC ON CLIENT_CONTEXTS_ATMOSPHERIC
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLIENT_CONTEXTS_ABSORPTION ON CLIENT_CONTEXTS_ABSORPTION
(CONTEXT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_GN06_AFFECTED_ADM_RESULT ON GN06_AFFECTED_ADM_RESULT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_GN06_ALLOTMENT_OR_ASSIGNMENT_RESULT ON GN06_ALLOTMENT_OR_ASSIGNMENT_RESULT
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MD_APPLICATIONS_PK ON MD_APPLICATIONS
(ID)
LOGGING
NOPARALLEL;


CREATE INDEX MD_APP_FILE_TYPE_IDX ON MD_APPLICATIONFILES
(TYPE, ID)
LOGGING
NOPARALLEL;


CREATE INDEX MD_STATE_TYPE__ID ON MD_APPLICATIONFILES
(STATE, TYPE, ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MD_APPLICATIONFILES_PK ON MD_APPLICATIONFILES
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MD_FILE_ARTIFACTS_PK ON MD_FILE_ARTIFACTS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MD_TABLESPACES_PK ON MD_TABLESPACES
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CLIENT_CONTEXTS_PK ON CLIENT_CONTEXTS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CALCTASKS_POINTFIELDSTRENGTH_ARGS_DEF ON CALCTASKS_POINTFIELDSTRENGTH_ARGS_DEF
(TASK_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CALCTASKS_POINTFIELDSTRENGTH_ARGS ON CALCTASKS_POINTFIELDSTRENGTH_ARGS
(TASK_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CALCTASKS_COVERAGEPROFILES_PK ON CALCTASKS_COVERAGEPROFILES
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CALCTASKS_PK ON CALCTASKS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CALCRESULTS_STATION_STA_PK ON CALCRESULTS_STATION_CALIBRATION_STA
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CALCRESULTS_STATION_DRVTEST_PK ON CALCRESULTS_STATION_CALIBRATION_DRIVE_TEST
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CALCRESULTS_STATION_CALIBRA_PK ON CALCRESULTS_STATION_CALIBRATION
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CALCRESULTS_POINTFIELDSTRENGTH ON CALCRESULTS_POINTFIELDSTRENGTH
(RESULT_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CALCRESULTS_PK ON CALCRESULTS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CONTEXT_STATION_PATTERNS ON CONTEXT_STATION_PATTERNS
(STATION_ID, ANTENNA_PLANE, WAVE_PLANE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CONTEXT_STATION_COORDINATES ON CONTEXT_STATION_COORDINATES
(STATION_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CONTEXT_PLANNEDCALCTASK_PK ON CONTEXT_PLANNEDCALCTASK
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLUTTERS_DESCS_FREQS_CLUTTERS ON CLUTTERS_DESCS_FREQS_CLUTTERS
(FREQ_ID, CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CLUTTERS_DESCS_FREQS_PK ON CLUTTERS_DESCS_FREQS
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CLUTTERS_DESCS_CLUTTERS ON CLUTTERS_DESCS_CLUTTERS
(CLUTTERS_DESC_ID, CODE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CALCTASKS_STATION_CALIBRATION_ARGS_DEF_NEW_ ON CALCTASKS_STATION_CALIBRATION_ARGS_DEF
(TASK_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CALCTASKS_POINTFIELDSTRENGTH_ARGS_NEW ON CALCTASKS_STATION_CALIBRATION_ARGS
(TASK_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_CALCRESULTS_GN06 ON CALCRESULTS_GN06
(ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CALCRESULT_EVENTS_PK ON CALCRESULT_EVENTS
(ID)
LOGGING
NOPARALLEL;


CREATE OR REPLACE FUNCTION      GetID (inttable_name IN varchar2)
return number
is
n number(15);


BEGIN


if inttable_name ='CALCRESULTS' then
select CALC.CALCRESULTS_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CALCRESULTS_POINTFIELDSTRENGTH' then
select CALC.CALCRESULTS_POINTFIELDSTRENGTH_ID_SEQ.nextval
into n
from dual;
end if;



if inttable_name ='CALCRESULTS_STATION_CALIBRATION' then
select CALC.CALCRESULTS_STATION_CALIBRATION_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CALCRESULTS_STATION_CALIBRATION_DRIVE_TEST' then
select CALC.CALCRESULTS_STATION_CALIBRATION_DRIVE_TEST_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CALCRESULTS_STATION_CALIBRATION_STA' then
select CALC.CALCRESULTS_STATION_CALIBRATION_STA_ID_SEQ.nextval
into n
from dual;
end if;



if inttable_name ='CALCTASKS' then
select CALC.CALCTASKS_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CALCTASKS_COVERAGEPROFILES' then
select CALC.CALCTASKS_COVERAGEPROFILES_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CALCTASKS_POINTFIELDSTRENGTH_ARGS' then
select CALC.CALCTASKS_POINTFIELDSTRENGTH_ARGS_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CALCTASKS_POINTFIELDSTRENGTH_ARGS_DEF' then
select CALC.CALCTASKS_POINTFIELDSTRENGTH_ARGS_DEF_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CALCTASKS_STATION_CALIBRATION_ARGS' then
select CALC.CALCTASKS_STATION_CALIBRATION_ARGS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CALCTASKS_STATION_CALIBRATION_ARGS_DEF' then
select CALC.CALCTASKS_STATION_CALIBRATION_ARGS_DEF_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CLIENT_CONTEXTS' then
select CALC.CLIENT_CONTEXTS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLIENT_CONTEXTS_ABSORPTION' then
select CALC.CLIENT_CONTEXTS_ABSORPTION_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CLIENT_CONTEXTS_ADDITIONAL' then
select CALC.CLIENT_CONTEXTS_ADDITIONAL_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLIENT_CONTEXTS_ATMOSPHERIC' then
select CALC.CLIENT_CONTEXTS_ATMOSPHERIC_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLIENT_CONTEXTS_CLUTTER' then
select CALC.CLIENT_CONTEXTS_CLUTTER_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CLIENT_CONTEXTS_DIFFRACTION' then
select CALC.CLIENT_CONTEXTS_DIFFRACTION_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CLIENT_CONTEXTS_DIFFRACTION' then
select CALC.CLIENT_CONTEXTS_DIFFRACTION_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLIENT_CONTEXTS_DUCTING' then
select CALC.CLIENT_CONTEXTS_DUCTING_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CLIENT_CONTEXTS_GLOBALPARAMS' then
select CALC.CLIENT_CONTEXTS_GLOBALPARAMS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLIENT_CONTEXTS_MAINBLOCK' then
select CALC.CLIENT_CONTEXTS_MAINBLOCK_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLIENT_CONTEXTS_REFLECTION' then
select CALC.CLIENT_CONTEXTS_REFLECTION_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLIENT_CONTEXTS_SUBPATHDIFFRACTION' then
select CALC.CLIENT_CONTEXTS_SUBPATHDIFFRACTION_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLIENT_CONTEXTS_TROPO' then
select CALC.CLIENT_CONTEXTS_TROPO_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLUTTERS_DESCS' then
select CALC.CLUTTERS_DESCS_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CLUTTERS_DESCS_CLUTTERS' then
select CALC.CLUTTERS_DESCS_CLUTTERS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLUTTERS_DESCS_FREQS' then
select CALC.CLUTTERS_DESCS_FREQS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CLUTTERS_DESCS_FREQS_CLUTTERS' then
select CALC.CLUTTERS_DESCS_FREQS_CLUTTERS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CONTEXT_PLANNEDCALCTASK' then
select CALC.CONTEXT_PLANNEDCALCTASK_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CONTEXT_STATION_COORDINATES' then
select CALC.CONTEXT_STATION_COORDINATES_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CONTEXT_STATION_PATTERNS' then
select CALC.CONTEXT_STATION_PATTERNS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CONTEXT_STATIONS' then
select CALC.CONTEXT_STATIONS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CONTEXT_STATIONS_ANTENNA' then
select CALC.CONTEXT_STATIONS_ANTENNA_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CONTEXT_STATIONS_RECEIVER' then
select CALC.CONTEXT_STATIONS_RECEIVER_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CONTEXT_STATIONS_SITE' then
select CALC.CONTEXT_STATIONS_SITE_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CONTEXT_STATIONS_TRANSMITTER' then
select CALC.CONTEXT_STATIONS_TRANSMITTER_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='PROJECT_MAP_CONTENT_SOURCES' then
select CALC.PROJECT_MAP_CONTENT_SOURCES_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='PROJECT_MAP_CONTENTS' then
select CALC.PROJECT_MAP_CONTENTS_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='PROJECT_MAPS' then
select CALC.PROJECT_MAPS_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='PROJECTS' then
select CALC.PROJECTS_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='CALCRESULTS_GN06' then
select CALC.CALCRESULTS_GN06_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CALCTASKS_GN06_ARGS_DEF' then
select CALC.CALCTASKS_GN06_ARGS_DEF_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='CALCTASKS_GN06_ARGS' then
select CALC.CALCTASKS_GN06_ARGS_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='GN06_AFFECTED_ADM_RESULT' then
select CALC.GN06_AFFECTED_ADM_RESULT_ID_SEQ.nextval
into n
from dual;
end if;


if inttable_name ='GN06_CONTOURS_RESULT' then
select CALC.GN06_CONTOURS_RESULT_ID_SEQ.nextval
into n
from dual;
end if;

if inttable_name ='GN06_ALLOTMENT_OR_ASSIGNMENT_RESULT' then
select CALC.GN06_ALLOTMENT_OR_ASSIGNMENT_RESULT_ID_SEQ.nextval
into n
from dual;
end if;



if inttable_name ='CALCRESULT_EVENTS' then
select CALC.CALCRESULT_EVENTS_ID_SEQ.nextval
into n
from dual;
end if;


return(n);
end;
/

SHOW ERRORS;


