ALTER TABLE CALC.CALCTASKS_STATION_CALIBRATION_ARGS
  ADD (
 AREAS NVARCHAR2(1000)
);

ALTER TABLE CALC.CALCTASKS_STATION_CALIBRATION_ARGS_DEF
  ADD (
 AREAS NVARCHAR2(1000)
);

CREATE TABLE CALC.CHECKPOINTS
(
  ID            NUMBER(15),
  CREATED_DATE  TIMESTAMP(7) WITH TIME ZONE     DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT' NOT NULL,
  RESULT_ID     NUMBER(15)                      NOT NULL,
  STATUS_CODE   NUMBER(3)                       NOT NULL,
  STATUS_NAME   NVARCHAR2(50)                   NOT NULL,
  STATUS_NOTE   NCLOB,
  NAME          NVARCHAR2(250)                  NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CHECKPOINTS_PK ON CALC.CHECKPOINTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CHECKPOINTS ADD (
  CONSTRAINT CHECKPOINTS_PK
 PRIMARY KEY
 (ID));



 CREATE TABLE CALC.CHECKPOINTS_DATA
(
  ID             NUMBER(15),
  CREATED_DATE   TIMESTAMP(7) WITH TIME ZONE    DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT' NOT NULL,
  CHECKPOINT_ID  NUMBER(15)                     NOT NULL,
  DATA_CONTEXT   NVARCHAR2(250)                 NOT NULL,
  DATA_JSON      NCLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.CHECKPOINTS_DATA_PK ON CALC.CHECKPOINTS_DATA
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.CHECKPOINTS_DATA ADD (
  CONSTRAINT CHECKPOINTS_DATA_PK
 PRIMARY KEY
 (ID));


 CREATE TABLE CALC.COMMANDS
(
  ID                 NUMBER(15),
  CREATED_DATE       TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT' NOT NULL,
  TYPE_CODE          NUMBER(15)                 NOT NULL,
  TYPE_NAME          NVARCHAR2(250)             NOT NULL,
  STATUS_CODE        NUMBER(3)                  NOT NULL,
  STATUS_NAME        NVARCHAR2(50)              NOT NULL,
  STATUS_NOTE        NCLOB,
  CALLER_INSTANCE    NVARCHAR2(250)             NOT NULL,
  CALLER_COMMAND_ID  VARCHAR2(36 BYTE)          NOT NULL,
  START_TIME         TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  FINISH_TIME        TIMESTAMP(7) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT',
  ARGS_JSON          NCLOB,
  RESULT_JSON        NCLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CALC.COMMANDS_PK ON CALC.COMMANDS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CALC.COMMANDS ADD (
  CONSTRAINT COMMANDS_PK
 PRIMARY KEY
 (ID));
