//-------------------------------------------------------------------------
//FILE GENERATED BY ICS MANAGER FROM SCHEMA 'SensorPlugin' DON'T MODIFY IT;
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace OrmCs
{
	public class YXbsSensor : Yyy
	{
		public YXbsSensor() { construct("XBS_Sensor",null); }
		public YXbsSensor(OrmLinker lk) { construct("XBS_Sensor",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_sensoridentifier_id { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_sensoridentifier_id { get { return new DatPtr(this,1); } }
		public string m_status { get { return getString(2); } set { setString(2,25,value); } }
			public DatPtr z_status { get { return new DatPtr(this,2); } }
		public string m_name { get { return getString(3); } set { setString(3,150,value); } }
			public DatPtr z_name { get { return new DatPtr(this,3); } }
		public string m_administration { get { return getString(4); } set { setString(4,50,value); } }
			public DatPtr z_administration { get { return new DatPtr(this,4); } }
		public string m_networkid { get { return getString(5); } set { setString(5,150,value); } }
			public DatPtr z_networkid { get { return new DatPtr(this,5); } }
		public string m_remark { get { return getString(6); } set { setString(6,250,value); } }
			public DatPtr z_remark { get { return new DatPtr(this,6); } }
		public DateTime m_biusedate { get { return getDateTime(7); } set { setDateTime(7,value); } }
			public DatPtr z_biusedate { get { return new DatPtr(this,7); } }
		public DateTime m_eousedate { get { return getDateTime(8); } set { setDateTime(8,value); } }
			public DatPtr z_eousedate { get { return new DatPtr(this,8); } }
		public double m_azimuth { get { return getDouble(9); } set { setDouble(9,value); } }
			public DatPtr z_azimuth { get { return new DatPtr(this,9); } }
		public double m_elevation { get { return getDouble(10); } set { setDouble(10,value); } }
			public DatPtr z_elevation { get { return new DatPtr(this,10); } }
		public double m_agl { get { return getDouble(11); } set { setDouble(11,value); } }
			public DatPtr z_agl { get { return new DatPtr(this,11); } }
		public string m_idsysargus { get { return getString(12); } set { setString(12,50,value); } }
			public DatPtr z_idsysargus { get { return new DatPtr(this,12); } }
		public string m_typesensor { get { return getString(13); } set { setString(13,50,value); } }
			public DatPtr z_typesensor { get { return new DatPtr(this,13); } }
		public double m_stepmeastime { get { return getDouble(14); } set { setDouble(14,value); } }
			public DatPtr z_stepmeastime { get { return new DatPtr(this,14); } }
		public double m_rxloss { get { return getDouble(15); } set { setDouble(15,value); } }
			public DatPtr z_rxloss { get { return new DatPtr(this,15); } }
		public double m_ophhfr { get { return getDouble(16); } set { setDouble(16,value); } }
			public DatPtr z_ophhfr { get { return new DatPtr(this,16); } }
		public double m_ophhto { get { return getDouble(17); } set { setDouble(17,value); } }
			public DatPtr z_ophhto { get { return new DatPtr(this,17); } }
		public string m_opdays { get { return getString(18); } set { setString(18,50,value); } }
			public DatPtr z_opdays { get { return new DatPtr(this,18); } }
		public string m_custtxt1 { get { return getString(19); } set { setString(19,50,value); } }
			public DatPtr z_custtxt1 { get { return new DatPtr(this,19); } }
		public DateTime m_custdata1 { get { return getDateTime(20); } set { setDateTime(20,value); } }
			public DatPtr z_custdata1 { get { return new DatPtr(this,20); } }
		public double m_custnbr1 { get { return getDouble(21); } set { setDouble(21,value); } }
			public DatPtr z_custnbr1 { get { return new DatPtr(this,21); } }
		public DateTime m_datecreated { get { return getDateTime(22); } set { setDateTime(22,value); } }
			public DatPtr z_datecreated { get { return new DatPtr(this,22); } }
		public string m_createdby { get { return getString(23); } set { setString(23,50,value); } }
			public DatPtr z_createdby { get { return new DatPtr(this,23); } }
	}

	public class YXbsSensorantenna : Yyy
	{
		public YXbsSensorantenna() { construct("XBS_SensorAntenna",null); }
		public YXbsSensorantenna(OrmLinker lk) { construct("XBS_SensorAntenna",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_sensorid { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_sensorid { get { return new DatPtr(this,1); } }
		public string m_code { get { return getString(2); } set { setString(2,50,value); } }
			public DatPtr z_code { get { return new DatPtr(this,2); } }
		public double m_slewang { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_slewang { get { return new DatPtr(this,3); } }
		public string m_manufacturer { get { return getString(4); } set { setString(4,50,value); } }
			public DatPtr z_manufacturer { get { return new DatPtr(this,4); } }
		public string m_name { get { return getString(5); } set { setString(5,50,value); } }
			public DatPtr z_name { get { return new DatPtr(this,5); } }
		public string m_techid { get { return getString(6); } set { setString(6,50,value); } }
			public DatPtr z_techid { get { return new DatPtr(this,6); } }
		public string m_antdir { get { return getString(7); } set { setString(7,50,value); } }
			public DatPtr z_antdir { get { return new DatPtr(this,7); } }
		public double m_hbeamwidth { get { return getDouble(8); } set { setDouble(8,value); } }
			public DatPtr z_hbeamwidth { get { return new DatPtr(this,8); } }
		public double m_vbeamwidth { get { return getDouble(9); } set { setDouble(9,value); } }
			public DatPtr z_vbeamwidth { get { return new DatPtr(this,9); } }
		public string m_polarization { get { return getString(10); } set { setString(10,50,value); } }
			public DatPtr z_polarization { get { return new DatPtr(this,10); } }
		public string m_usetype { get { return getString(11); } set { setString(11,50,value); } }
			public DatPtr z_usetype { get { return new DatPtr(this,11); } }
		public string m_category { get { return getString(12); } set { setString(12,50,value); } }
			public DatPtr z_category { get { return new DatPtr(this,12); } }
		public string m_gaintype { get { return getString(13); } set { setString(13,50,value); } }
			public DatPtr z_gaintype { get { return new DatPtr(this,13); } }
		public double m_gainmax { get { return getDouble(14); } set { setDouble(14,value); } }
			public DatPtr z_gainmax { get { return new DatPtr(this,14); } }
		public double m_lowerfreq { get { return getDouble(15); } set { setDouble(15,value); } }
			public DatPtr z_lowerfreq { get { return new DatPtr(this,15); } }
		public double m_upperfreq { get { return getDouble(16); } set { setDouble(16,value); } }
			public DatPtr z_upperfreq { get { return new DatPtr(this,16); } }
		public double m_addloss { get { return getDouble(17); } set { setDouble(17,value); } }
			public DatPtr z_addloss { get { return new DatPtr(this,17); } }
		public double m_xpd { get { return getDouble(18); } set { setDouble(18,value); } }
			public DatPtr z_xpd { get { return new DatPtr(this,18); } }
		public string m_antclass { get { return getString(19); } set { setString(19,50,value); } }
			public DatPtr z_antclass { get { return new DatPtr(this,19); } }
		public string m_remark { get { return getString(20); } set { setString(20,250,value); } }
			public DatPtr z_remark { get { return new DatPtr(this,20); } }
		public string m_custtxt1 { get { return getString(21); } set { setString(21,250,value); } }
			public DatPtr z_custtxt1 { get { return new DatPtr(this,21); } }
		public string m_custdata1 { get { return getString(22); } set { setString(22,250,value); } }
			public DatPtr z_custdata1 { get { return new DatPtr(this,22); } }
		public double m_custnbr1 { get { return getDouble(23); } set { setDouble(23,value); } }
			public DatPtr z_custnbr1 { get { return new DatPtr(this,23); } }
	}

	public class YXbsSensorequip : Yyy
	{
		public YXbsSensorequip() { construct("XBS_SensorEquip",null); }
		public YXbsSensorequip(OrmLinker lk) { construct("XBS_SensorEquip",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_sensorid { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_sensorid { get { return new DatPtr(this,1); } }
		public string m_code { get { return getString(2); } set { setString(2,50,value); } }
			public DatPtr z_code { get { return new DatPtr(this,2); } }
		public string m_manufacturer { get { return getString(3); } set { setString(3,50,value); } }
			public DatPtr z_manufacturer { get { return new DatPtr(this,3); } }
		public string m_name { get { return getString(4); } set { setString(4,50,value); } }
			public DatPtr z_name { get { return new DatPtr(this,4); } }
		public string m_family { get { return getString(5); } set { setString(5,50,value); } }
			public DatPtr z_family { get { return new DatPtr(this,5); } }
		public string m_techid { get { return getString(6); } set { setString(6,50,value); } }
			public DatPtr z_techid { get { return new DatPtr(this,6); } }
		public string m_version { get { return getString(7); } set { setString(7,50,value); } }
			public DatPtr z_version { get { return new DatPtr(this,7); } }
		public double m_lowerfreq { get { return getDouble(8); } set { setDouble(8,value); } }
			public DatPtr z_lowerfreq { get { return new DatPtr(this,8); } }
		public double m_upperfreq { get { return getDouble(9); } set { setDouble(9,value); } }
			public DatPtr z_upperfreq { get { return new DatPtr(this,9); } }
		public double m_rbwmin { get { return getDouble(10); } set { setDouble(10,value); } }
			public DatPtr z_rbwmin { get { return new DatPtr(this,10); } }
		public double m_rbwmax { get { return getDouble(11); } set { setDouble(11,value); } }
			public DatPtr z_rbwmax { get { return new DatPtr(this,11); } }
		public double m_vbwmin { get { return getDouble(12); } set { setDouble(12,value); } }
			public DatPtr z_vbwmin { get { return new DatPtr(this,12); } }
		public double m_vbwmax { get { return getDouble(13); } set { setDouble(13,value); } }
			public DatPtr z_vbwmax { get { return new DatPtr(this,13); } }
		public int m_mobility { get { return getInt(14); } set { setInt(14,value); } }
			public DatPtr z_mobility { get { return new DatPtr(this,14); } }
		public double m_fftpointmax { get { return getDouble(15); } set { setDouble(15,value); } }
			public DatPtr z_fftpointmax { get { return new DatPtr(this,15); } }
		public double m_refleveldbm { get { return getDouble(16); } set { setDouble(16,value); } }
			public DatPtr z_refleveldbm { get { return new DatPtr(this,16); } }
		public string m_operationmode { get { return getString(17); } set { setString(17,50,value); } }
			public DatPtr z_operationmode { get { return new DatPtr(this,17); } }
		public string m_type { get { return getString(18); } set { setString(18,50,value); } }
			public DatPtr z_type { get { return new DatPtr(this,18); } }
		public string m_equipclass { get { return getString(19); } set { setString(19,50,value); } }
			public DatPtr z_equipclass { get { return new DatPtr(this,19); } }
		public double m_tuningstep { get { return getDouble(20); } set { setDouble(20,value); } }
			public DatPtr z_tuningstep { get { return new DatPtr(this,20); } }
		public string m_usetype { get { return getString(21); } set { setString(21,50,value); } }
			public DatPtr z_usetype { get { return new DatPtr(this,21); } }
		public string m_category { get { return getString(22); } set { setString(22,50,value); } }
			public DatPtr z_category { get { return new DatPtr(this,22); } }
		public string m_remark { get { return getString(23); } set { setString(23,250,value); } }
			public DatPtr z_remark { get { return new DatPtr(this,23); } }
		public string m_custtxt1 { get { return getString(24); } set { setString(24,250,value); } }
			public DatPtr z_custtxt1 { get { return new DatPtr(this,24); } }
		public DateTime m_custdata1 { get { return getDateTime(25); } set { setDateTime(25,value); } }
			public DatPtr z_custdata1 { get { return new DatPtr(this,25); } }
		public double m_custnbr1 { get { return getDouble(26); } set { setDouble(26,value); } }
			public DatPtr z_custnbr1 { get { return new DatPtr(this,26); } }
	}

	public class YXbsSensorequipsens : Yyy
	{
		public YXbsSensorequipsens() { construct("XBS_SensorEquipSens",null); }
		public YXbsSensorequipsens(OrmLinker lk) { construct("XBS_SensorEquipSens",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_sensorequip_id { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_sensorequip_id { get { return new DatPtr(this,1); } }
		public double m_freq { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_freq { get { return new DatPtr(this,2); } }
		public double m_ktbf { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_ktbf { get { return new DatPtr(this,3); } }
		public double m_noisef { get { return getDouble(4); } set { setDouble(4,value); } }
			public DatPtr z_noisef { get { return new DatPtr(this,4); } }
		public double m_freqstability { get { return getDouble(5); } set { setDouble(5,value); } }
			public DatPtr z_freqstability { get { return new DatPtr(this,5); } }
		public double m_addloss { get { return getDouble(6); } set { setDouble(6,value); } }
			public DatPtr z_addloss { get { return new DatPtr(this,6); } }
	}

	public class YXbsSensorlocation : Yyy
	{
		public YXbsSensorlocation() { construct("XBS_SensorLocation",null); }
		public YXbsSensorlocation(OrmLinker lk) { construct("XBS_SensorLocation",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_sensorid { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_sensorid { get { return new DatPtr(this,1); } }
		public DateTime m_datafrom { get { return getDateTime(2); } set { setDateTime(2,value); } }
			public DatPtr z_datafrom { get { return new DatPtr(this,2); } }
		public DateTime m_datato { get { return getDateTime(3); } set { setDateTime(3,value); } }
			public DatPtr z_datato { get { return new DatPtr(this,3); } }
		public DateTime m_datacreated { get { return getDateTime(4); } set { setDateTime(4,value); } }
			public DatPtr z_datacreated { get { return new DatPtr(this,4); } }
		public string m_status { get { return getString(5); } set { setString(5,25,value); } }
			public DatPtr z_status { get { return new DatPtr(this,5); } }
		public double m_lon { get { return getDouble(6); } set { setDouble(6,value); } }
			public DatPtr z_lon { get { return new DatPtr(this,6); } }
		public double m_lat { get { return getDouble(7); } set { setDouble(7,value); } }
			public DatPtr z_lat { get { return new DatPtr(this,7); } }
		public double m_asl { get { return getDouble(8); } set { setDouble(8,value); } }
			public DatPtr z_asl { get { return new DatPtr(this,8); } }
	}

	public class YXbsAntennapattern : Yyy
	{
		public YXbsAntennapattern() { construct("XBS_AntennaPattern",null); }
		public YXbsAntennapattern(OrmLinker lk) { construct("XBS_AntennaPattern",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_sensorantenna_id { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_sensorantenna_id { get { return new DatPtr(this,1); } }
		public double m_freq { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_freq { get { return new DatPtr(this,2); } }
		public double m_gain { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_gain { get { return new DatPtr(this,3); } }
		public string m_diaga { get { return getString(4); } set { setString(4,1000,value); } }
			public DatPtr z_diaga { get { return new DatPtr(this,4); } }
		public string m_diagh { get { return getString(5); } set { setString(5,1000,value); } }
			public DatPtr z_diagh { get { return new DatPtr(this,5); } }
		public string m_diagv { get { return getString(6); } set { setString(6,1000,value); } }
			public DatPtr z_diagv { get { return new DatPtr(this,6); } }
	}

	public class YXbsSensorpolig : Yyy
	{
		public YXbsSensorpolig() { construct("XBS_SensorPolig",null); }
		public YXbsSensorpolig(OrmLinker lk) { construct("XBS_SensorPolig",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_sensorid { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_sensorid { get { return new DatPtr(this,1); } }
		public double m_lon { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_lon { get { return new DatPtr(this,2); } }
		public double m_lat { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_lat { get { return new DatPtr(this,3); } }
	}

	public class YXbsMeastask : Yyy
	{
		public YXbsMeastask() { construct("XBS_MeasTask",null); }
		public YXbsMeastask(OrmLinker lk) { construct("XBS_MeasTask",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public string m_status { get { return getString(1); } set { setString(1,50,value); } }
			public DatPtr z_status { get { return new DatPtr(this,1); } }
		public int m_orderid { get { return getInt(2); } set { setInt(2,value); } }
			public DatPtr z_orderid { get { return new DatPtr(this,2); } }
		public string m_type { get { return getString(3); } set { setString(3,50,value); } }
			public DatPtr z_type { get { return new DatPtr(this,3); } }
		public string m_name { get { return getString(4); } set { setString(4,100,value); } }
			public DatPtr z_name { get { return new DatPtr(this,4); } }
		public string m_executionmode { get { return getString(5); } set { setString(5,50,value); } }
			public DatPtr z_executionmode { get { return new DatPtr(this,5); } }
		public string m_task { get { return getString(6); } set { setString(6,50,value); } }
			public DatPtr z_task { get { return new DatPtr(this,6); } }
		public int m_prio { get { return getInt(7); } set { setInt(7,value); } }
			public DatPtr z_prio { get { return new DatPtr(this,7); } }
		public string m_resulttype { get { return getString(8); } set { setString(8,50,value); } }
			public DatPtr z_resulttype { get { return new DatPtr(this,8); } }
		public int m_maxtimebs { get { return getInt(9); } set { setInt(9,value); } }
			public DatPtr z_maxtimebs { get { return new DatPtr(this,9); } }
		public DateTime m_datecreated { get { return getDateTime(10); } set { setDateTime(10,value); } }
			public DatPtr z_datecreated { get { return new DatPtr(this,10); } }
		public string m_createdby { get { return getString(11); } set { setString(11,50,value); } }
			public DatPtr z_createdby { get { return new DatPtr(this,11); } }
		public string m_id_start { get { return getString(12); } set { setString(12,50,value); } }
			public DatPtr z_id_start { get { return new DatPtr(this,12); } }
	}

	public class YXbsStationdatform : Yyy
	{
		public YXbsStationdatform() { construct("XBS_StationDatForM",null); }
		public YXbsStationdatform(OrmLinker lk) { construct("XBS_StationDatForM",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public string m_globalsid { get { return getString(1); } set { setString(1,50,value); } }
			public DatPtr z_globalsid { get { return new DatPtr(this,1); } }
		public string m_status { get { return getString(2); } set { setString(2,20,value); } }
			public DatPtr z_status { get { return new DatPtr(this,2); } }
		public string m_standart { get { return getString(3); } set { setString(3,50,value); } }
			public DatPtr z_standart { get { return new DatPtr(this,3); } }
		public int m_id_xbs_meastask { get { return getInt(4); } set { setInt(4,value); } }
			public DatPtr z_id_xbs_meastask { get { return new DatPtr(this,4); } }
		public YXbsMeastask m_XBS_MeasTask { get { return (YXbsMeastask)getYyy(5); }  set { setYyy(5,value); } }
		public YXbsOwnerdata m_XBS_OwnerData { get { return (YXbsOwnerdata)getYyy(6); }  set { setYyy(6,value); } }
		public YXbsSitestformeas m_XBS_SiteStForMeas { get { return (YXbsSitestformeas)getYyy(7); }  set { setYyy(7,value); } }
		public YXbsSectstformeas m_XBS_SectStForMeas { get { return (YXbsSectstformeas)getYyy(8); }  set { setYyy(8,value); } }
		public YXbsPermassign m_XBS_PermAssign { get { return (YXbsPermassign)getYyy(9); }  set { setYyy(9,value); } }
	}

	public class YXbsMeassubtask : Yyy
	{
		public YXbsMeassubtask() { construct("XBS_MeasSubTask",null); }
		public YXbsMeassubtask(OrmLinker lk) { construct("XBS_MeasSubTask",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public DateTime m_timestart { get { return getDateTime(1); } set { setDateTime(1,value); } }
			public DatPtr z_timestart { get { return new DatPtr(this,1); } }
		public DateTime m_timestop { get { return getDateTime(2); } set { setDateTime(2,value); } }
			public DatPtr z_timestop { get { return new DatPtr(this,2); } }
		public string m_status { get { return getString(3); } set { setString(3,50,value); } }
			public DatPtr z_status { get { return new DatPtr(this,3); } }
		public int m_interval { get { return getInt(4); } set { setInt(4,value); } }
			public DatPtr z_interval { get { return new DatPtr(this,4); } }
		public int m_id_xbs_meastask { get { return getInt(5); } set { setInt(5,value); } }
			public DatPtr z_id_xbs_meastask { get { return new DatPtr(this,5); } }
	}

	public class YXbsMeasstation : Yyy
	{
		public YXbsMeasstation() { construct("XBS_MeasStation",null); }
		public YXbsMeasstation(OrmLinker lk) { construct("XBS_MeasStation",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_stationid { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_stationid { get { return new DatPtr(this,1); } }
		public string m_stationtype { get { return getString(2); } set { setString(2,50,value); } }
			public DatPtr z_stationtype { get { return new DatPtr(this,2); } }
		public int m_id_xbs_meastask { get { return getInt(3); } set { setInt(3,value); } }
			public DatPtr z_id_xbs_meastask { get { return new DatPtr(this,3); } }
	}

	public class YXbsMeassubtasksta : Yyy
	{
		public YXbsMeassubtasksta() { construct("XBS_MeasSubTaskSta",null); }
		public YXbsMeassubtasksta(OrmLinker lk) { construct("XBS_MeasSubTaskSta",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public string m_status { get { return getString(1); } set { setString(1,50,value); } }
			public DatPtr z_status { get { return new DatPtr(this,1); } }
		public int m_count { get { return getInt(2); } set { setInt(2,value); } }
			public DatPtr z_count { get { return new DatPtr(this,2); } }
		public DateTime m_timenexttask { get { return getDateTime(3); } set { setDateTime(3,value); } }
			public DatPtr z_timenexttask { get { return new DatPtr(this,3); } }
		public int m_id_xbs_sensor { get { return getInt(4); } set { setInt(4,value); } }
			public DatPtr z_id_xbs_sensor { get { return new DatPtr(this,4); } }
		public int m_id_xb_meassubtask { get { return getInt(5); } set { setInt(5,value); } }
			public DatPtr z_id_xb_meassubtask { get { return new DatPtr(this,5); } }
	}

	public class YXbsMeasother : Yyy
	{
		public YXbsMeasother() { construct("XBS_MeasOther",null); }
		public YXbsMeasother(OrmLinker lk) { construct("XBS_MeasOther",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_swnumber { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_swnumber { get { return new DatPtr(this,1); } }
		public string m_typespectrumscan { get { return getString(2); } set { setString(2,50,value); } }
			public DatPtr z_typespectrumscan { get { return new DatPtr(this,2); } }
		public string m_typespectrumoccupation { get { return getString(3); } set { setString(3,50,value); } }
			public DatPtr z_typespectrumoccupation { get { return new DatPtr(this,3); } }
		public double m_levelminoccup { get { return getDouble(4); } set { setDouble(4,value); } }
			public DatPtr z_levelminoccup { get { return new DatPtr(this,4); } }
		public int m_nchenal { get { return getInt(5); } set { setInt(5,value); } }
			public DatPtr z_nchenal { get { return new DatPtr(this,5); } }
		public int m_id_xbs_meastask { get { return getInt(6); } set { setInt(6,value); } }
			public DatPtr z_id_xbs_meastask { get { return new DatPtr(this,6); } }
	}

	public class YXbsMeastimeparaml : Yyy
	{
		public YXbsMeastimeparaml() { construct("XBS_MeasTimeParamL",null); }
		public YXbsMeastimeparaml(OrmLinker lk) { construct("XBS_MeasTimeParamL",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public DateTime m_perstart { get { return getDateTime(1); } set { setDateTime(1,value); } }
			public DatPtr z_perstart { get { return new DatPtr(this,1); } }
		public DateTime m_perstop { get { return getDateTime(2); } set { setDateTime(2,value); } }
			public DatPtr z_perstop { get { return new DatPtr(this,2); } }
		public DateTime m_timestart { get { return getDateTime(3); } set { setDateTime(3,value); } }
			public DatPtr z_timestart { get { return new DatPtr(this,3); } }
		public DateTime m_timestop { get { return getDateTime(4); } set { setDateTime(4,value); } }
			public DatPtr z_timestop { get { return new DatPtr(this,4); } }
		public string m_days { get { return getString(5); } set { setString(5,250,value); } }
			public DatPtr z_days { get { return new DatPtr(this,5); } }
		public double m_perinterval { get { return getDouble(6); } set { setDouble(6,value); } }
			public DatPtr z_perinterval { get { return new DatPtr(this,6); } }
		public int m_id_xbs_meastask { get { return getInt(7); } set { setInt(7,value); } }
			public DatPtr z_id_xbs_meastask { get { return new DatPtr(this,7); } }
	}

	public class YXbsMeaslocparam : Yyy
	{
		public YXbsMeaslocparam() { construct("XBS_MeasLocParam",null); }
		public YXbsMeaslocparam(OrmLinker lk) { construct("XBS_MeasLocParam",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_lon { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_lon { get { return new DatPtr(this,1); } }
		public double m_lat { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_lat { get { return new DatPtr(this,2); } }
		public double m_asl { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_asl { get { return new DatPtr(this,3); } }
		public double m_maxdist { get { return getDouble(4); } set { setDouble(4,value); } }
			public DatPtr z_maxdist { get { return new DatPtr(this,4); } }
		public int m_id_xbs_meastask { get { return getInt(5); } set { setInt(5,value); } }
			public DatPtr z_id_xbs_meastask { get { return new DatPtr(this,5); } }
	}

	public class YXbsMeasdtparam : Yyy
	{
		public YXbsMeasdtparam() { construct("XBS_MeasDtParam",null); }
		public YXbsMeasdtparam(OrmLinker lk) { construct("XBS_MeasDtParam",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public string m_typemeasurements { get { return getString(1); } set { setString(1,50,value); } }
			public DatPtr z_typemeasurements { get { return new DatPtr(this,1); } }
		public string m_detecttype { get { return getString(2); } set { setString(2,50,value); } }
			public DatPtr z_detecttype { get { return new DatPtr(this,2); } }
		public double m_rfattenuation { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_rfattenuation { get { return new DatPtr(this,3); } }
		public double m_ifattenuation { get { return getDouble(4); } set { setDouble(4,value); } }
			public DatPtr z_ifattenuation { get { return new DatPtr(this,4); } }
		public double m_meastime { get { return getDouble(5); } set { setDouble(5,value); } }
			public DatPtr z_meastime { get { return new DatPtr(this,5); } }
		public string m_demod { get { return getString(6); } set { setString(6,50,value); } }
			public DatPtr z_demod { get { return new DatPtr(this,6); } }
		public int m_preamplification { get { return getInt(7); } set { setInt(7,value); } }
			public DatPtr z_preamplification { get { return new DatPtr(this,7); } }
		public string m_mode { get { return getString(8); } set { setString(8,50,value); } }
			public DatPtr z_mode { get { return new DatPtr(this,8); } }
		public double m_rbw { get { return getDouble(9); } set { setDouble(9,value); } }
			public DatPtr z_rbw { get { return new DatPtr(this,9); } }
		public double m_vbw { get { return getDouble(10); } set { setDouble(10,value); } }
			public DatPtr z_vbw { get { return new DatPtr(this,10); } }
		public int m_id_xbs_meastask { get { return getInt(11); } set { setInt(11,value); } }
			public DatPtr z_id_xbs_meastask { get { return new DatPtr(this,11); } }
	}

	public class YXbsMeasfreqparam : Yyy
	{
		public YXbsMeasfreqparam() { construct("XBS_MeasFreqParam",null); }
		public YXbsMeasfreqparam(OrmLinker lk) { construct("XBS_MeasFreqParam",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public string m_mode { get { return getString(1); } set { setString(1,50,value); } }
			public DatPtr z_mode { get { return new DatPtr(this,1); } }
		public double m_rgl { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_rgl { get { return new DatPtr(this,2); } }
		public double m_rgu { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_rgu { get { return new DatPtr(this,3); } }
		public double m_step { get { return getDouble(4); } set { setDouble(4,value); } }
			public DatPtr z_step { get { return new DatPtr(this,4); } }
		public int m_id_xbs_meastask { get { return getInt(5); } set { setInt(5,value); } }
			public DatPtr z_id_xbs_meastask { get { return new DatPtr(this,5); } }
	}

	public class YXbsMeasfreq : Yyy
	{
		public YXbsMeasfreq() { construct("XBS_MeasFreq",null); }
		public YXbsMeasfreq(OrmLinker lk) { construct("XBS_MeasFreq",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_freq { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_freq { get { return new DatPtr(this,1); } }
		public int m_id_xbs_measfreqparam { get { return getInt(2); } set { setInt(2,value); } }
			public DatPtr z_id_xbs_measfreqparam { get { return new DatPtr(this,2); } }
	}

	public class YXbsOwnerdata : Yyy
	{
		public YXbsOwnerdata() { construct("XBS_OwnerData",null); }
		public YXbsOwnerdata(OrmLinker lk) { construct("XBS_OwnerData",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public string m_ownername { get { return getString(1); } set { setString(1,100,value); } }
			public DatPtr z_ownername { get { return new DatPtr(this,1); } }
		public string m_okpo { get { return getString(2); } set { setString(2,50,value); } }
			public DatPtr z_okpo { get { return new DatPtr(this,2); } }
		public string m_zip { get { return getString(3); } set { setString(3,50,value); } }
			public DatPtr z_zip { get { return new DatPtr(this,3); } }
		public string m_code { get { return getString(4); } set { setString(4,50,value); } }
			public DatPtr z_code { get { return new DatPtr(this,4); } }
		public string m_addres { get { return getString(5); } set { setString(5,2000,value); } }
			public DatPtr z_addres { get { return new DatPtr(this,5); } }
		public int m_id_stationdatform { get { return getInt(6); } set { setInt(6,value); } }
			public DatPtr z_id_stationdatform { get { return new DatPtr(this,6); } }
		public YXbsStationdatform m_XBS_StationDatForM { get { return (YXbsStationdatform)getYyy(7); }  set { setYyy(7,value); } }
	}

	public class YXbsSitestformeas : Yyy
	{
		public YXbsSitestformeas() { construct("XBS_SiteStForMeas",null); }
		public YXbsSitestformeas(OrmLinker lk) { construct("XBS_SiteStForMeas",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_lon { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_lon { get { return new DatPtr(this,1); } }
		public double m_lat { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_lat { get { return new DatPtr(this,2); } }
		public string m_addres { get { return getString(3); } set { setString(3,2000,value); } }
			public DatPtr z_addres { get { return new DatPtr(this,3); } }
		public string m_region { get { return getString(4); } set { setString(4,50,value); } }
			public DatPtr z_region { get { return new DatPtr(this,4); } }
		public int m_id_stationdatform { get { return getInt(5); } set { setInt(5,value); } }
			public DatPtr z_id_stationdatform { get { return new DatPtr(this,5); } }
		public YXbsStationdatform m_XBS_StationDatForM { get { return (YXbsStationdatform)getYyy(6); }  set { setYyy(6,value); } }
	}

	public class YXbsSectstformeas : Yyy
	{
		public YXbsSectstformeas() { construct("XBS_SectStForMeas",null); }
		public YXbsSectstformeas(OrmLinker lk) { construct("XBS_SectStForMeas",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_agl { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_agl { get { return new DatPtr(this,1); } }
		public double m_eirp { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_eirp { get { return new DatPtr(this,2); } }
		public double m_azimut { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_azimut { get { return new DatPtr(this,3); } }
		public double m_bw { get { return getDouble(4); } set { setDouble(4,value); } }
			public DatPtr z_bw { get { return new DatPtr(this,4); } }
		public string m_classemission { get { return getString(5); } set { setString(5,20,value); } }
			public DatPtr z_classemission { get { return new DatPtr(this,5); } }
		public int m_id_stationdatform { get { return getInt(6); } set { setInt(6,value); } }
			public DatPtr z_id_stationdatform { get { return new DatPtr(this,6); } }
		public YXbsStationdatform m_XBS_StationDatForM { get { return (YXbsStationdatform)getYyy(7); }  set { setYyy(7,value); } }
		public YXbsMaskelements m_XBS_MaskElements { get { return (YXbsMaskelements)getYyy(8); }  set { setYyy(8,value); } }
		public YXbsFreqforsectics m_XBS_FreqForSectICS { get { return (YXbsFreqforsectics)getYyy(9); }  set { setYyy(9,value); } }
	}

	public class YXbsPermassign : Yyy
	{
		public YXbsPermassign() { construct("XBS_PermAssign",null); }
		public YXbsPermassign(OrmLinker lk) { construct("XBS_PermAssign",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public DateTime m_startdate { get { return getDateTime(1); } set { setDateTime(1,value); } }
			public DatPtr z_startdate { get { return new DatPtr(this,1); } }
		public DateTime m_enddate { get { return getDateTime(2); } set { setDateTime(2,value); } }
			public DatPtr z_enddate { get { return new DatPtr(this,2); } }
		public DateTime m_closedate { get { return getDateTime(3); } set { setDateTime(3,value); } }
			public DatPtr z_closedate { get { return new DatPtr(this,3); } }
		public string m_dozvilname { get { return getString(4); } set { setString(4,100,value); } }
			public DatPtr z_dozvilname { get { return new DatPtr(this,4); } }
		public int m_id_stationdatform { get { return getInt(5); } set { setInt(5,value); } }
			public DatPtr z_id_stationdatform { get { return new DatPtr(this,5); } }
		public YXbsStationdatform m_XBS_StationDatForM { get { return (YXbsStationdatform)getYyy(6); }  set { setYyy(6,value); } }
	}

	public class YXbsMaskelements : Yyy
	{
		public YXbsMaskelements() { construct("XBS_MaskElements",null); }
		public YXbsMaskelements(OrmLinker lk) { construct("XBS_MaskElements",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_level { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_level { get { return new DatPtr(this,1); } }
		public double m_bw { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_bw { get { return new DatPtr(this,2); } }
		public int m_id_sectstformeas { get { return getInt(3); } set { setInt(3,value); } }
			public DatPtr z_id_sectstformeas { get { return new DatPtr(this,3); } }
		public YXbsSectstformeas m_XBS_SectStForMeas { get { return (YXbsSectstformeas)getYyy(4); }  set { setYyy(4,value); } }
	}

	public class YXbsFreqforsectics : Yyy
	{
		public YXbsFreqforsectics() { construct("XBS_FreqForSectICS",null); }
		public YXbsFreqforsectics(OrmLinker lk) { construct("XBS_FreqForSectICS",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_idplan { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_idplan { get { return new DatPtr(this,1); } }
		public int m_channalnumber { get { return getInt(2); } set { setInt(2,value); } }
			public DatPtr z_channalnumber { get { return new DatPtr(this,2); } }
		public double m_frequency { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_frequency { get { return new DatPtr(this,3); } }
		public int m_id_sectstformeas { get { return getInt(4); } set { setInt(4,value); } }
			public DatPtr z_id_sectstformeas { get { return new DatPtr(this,4); } }
		public YXbsSectstformeas m_XBS_SectStForMeas { get { return (YXbsSectstformeas)getYyy(5); }  set { setYyy(5,value); } }
	}

	public class YXbsMeasurementres : Yyy
	{
		public YXbsMeasurementres() { construct("XBS_MeasurementRes",null); }
		public YXbsMeasurementres(OrmLinker lk) { construct("XBS_MeasurementRes",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_meastaskid { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_meastaskid { get { return new DatPtr(this,1); } }
		public int m_submeastaskid { get { return getInt(2); } set { setInt(2,value); } }
			public DatPtr z_submeastaskid { get { return new DatPtr(this,2); } }
		public int m_submeastaskstationid { get { return getInt(3); } set { setInt(3,value); } }
			public DatPtr z_submeastaskstationid { get { return new DatPtr(this,3); } }
		public int m_sensorid { get { return getInt(4); } set { setInt(4,value); } }
			public DatPtr z_sensorid { get { return new DatPtr(this,4); } }
		public double m_antval { get { return getDouble(5); } set { setDouble(5,value); } }
			public DatPtr z_antval { get { return new DatPtr(this,5); } }
		public DateTime m_timemeas { get { return getDateTime(6); } set { setDateTime(6,value); } }
			public DatPtr z_timemeas { get { return new DatPtr(this,6); } }
		public int m_datarank { get { return getInt(7); } set { setInt(7,value); } }
			public DatPtr z_datarank { get { return new DatPtr(this,7); } }
		public int m_n { get { return getInt(8); } set { setInt(8,value); } }
			public DatPtr z_n { get { return new DatPtr(this,8); } }
		public string m_status { get { return getString(9); } set { setString(9,50,value); } }
			public DatPtr z_status { get { return new DatPtr(this,9); } }
		public string m_typemeasurements { get { return getString(10); } set { setString(10,50,value); } }
			public DatPtr z_typemeasurements { get { return new DatPtr(this,10); } }
	}

	public class YXbsStationmeas : Yyy
	{
		public YXbsStationmeas() { construct("XBS_StationMeas",null); }
		public YXbsStationmeas(OrmLinker lk) { construct("XBS_StationMeas",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public int m_id_xbs_sensor { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_id_xbs_sensor { get { return new DatPtr(this,1); } }
		public int m_id_xbs_measurementres { get { return getInt(2); } set { setInt(2,value); } }
			public DatPtr z_id_xbs_measurementres { get { return new DatPtr(this,2); } }
	}

	public class YXbsLocationsensorm : Yyy
	{
		public YXbsLocationsensorm() { construct("XBS_LocationSensorM",null); }
		public YXbsLocationsensorm(OrmLinker lk) { construct("XBS_LocationSensorM",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_lon { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_lon { get { return new DatPtr(this,1); } }
		public double m_lat { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_lat { get { return new DatPtr(this,2); } }
		public double m_asl { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_asl { get { return new DatPtr(this,3); } }
		public int m_id_xbs_measurementres { get { return getInt(4); } set { setInt(4,value); } }
			public DatPtr z_id_xbs_measurementres { get { return new DatPtr(this,4); } }
	}

	public class YXbsFrequencymeas : Yyy
	{
		public YXbsFrequencymeas() { construct("XBS_FrequencyMeas",null); }
		public YXbsFrequencymeas(OrmLinker lk) { construct("XBS_FrequencyMeas",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_freq { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_freq { get { return new DatPtr(this,1); } }
		public int m_id_xbs_measurementres { get { return getInt(2); } set { setInt(2,value); } }
			public DatPtr z_id_xbs_measurementres { get { return new DatPtr(this,2); } }
		public int m_num { get { return getInt(3); } set { setInt(3,value); } }
			public DatPtr z_num { get { return new DatPtr(this,3); } }
	}

	public class YXbsLevelmeasres : Yyy
	{
		public YXbsLevelmeasres() { construct("XBS_LevelMeasRes",null); }
		public YXbsLevelmeasres(OrmLinker lk) { construct("XBS_LevelMeasRes",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_value { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_value { get { return new DatPtr(this,1); } }
		public double m_stddev { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_stddev { get { return new DatPtr(this,2); } }
		public double m_vmin { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_vmin { get { return new DatPtr(this,3); } }
		public double m_vmmax { get { return getDouble(4); } set { setDouble(4,value); } }
			public DatPtr z_vmmax { get { return new DatPtr(this,4); } }
		public double m_limit { get { return getDouble(5); } set { setDouble(5,value); } }
			public DatPtr z_limit { get { return new DatPtr(this,5); } }
		public double m_occupancy { get { return getDouble(6); } set { setDouble(6,value); } }
			public DatPtr z_occupancy { get { return new DatPtr(this,6); } }
		public double m_pmin { get { return getDouble(7); } set { setDouble(7,value); } }
			public DatPtr z_pmin { get { return new DatPtr(this,7); } }
		public double m_pmax { get { return getDouble(8); } set { setDouble(8,value); } }
			public DatPtr z_pmax { get { return new DatPtr(this,8); } }
		public double m_pdiff { get { return getDouble(9); } set { setDouble(9,value); } }
			public DatPtr z_pdiff { get { return new DatPtr(this,9); } }
		public int m_id_xbs_measurementres { get { return getInt(10); } set { setInt(10,value); } }
			public DatPtr z_id_xbs_measurementres { get { return new DatPtr(this,10); } }
	}

	public class YXbsSpectoccupmeas : Yyy
	{
		public YXbsSpectoccupmeas() { construct("XBS_SpectOccupMeas",null); }
		public YXbsSpectoccupmeas(OrmLinker lk) { construct("XBS_SpectOccupMeas",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_value { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_value { get { return new DatPtr(this,1); } }
		public double m_stddev { get { return getDouble(2); } set { setDouble(2,value); } }
			public DatPtr z_stddev { get { return new DatPtr(this,2); } }
		public double m_vmin { get { return getDouble(3); } set { setDouble(3,value); } }
			public DatPtr z_vmin { get { return new DatPtr(this,3); } }
		public double m_vmmax { get { return getDouble(4); } set { setDouble(4,value); } }
			public DatPtr z_vmmax { get { return new DatPtr(this,4); } }
		public double m_limit { get { return getDouble(5); } set { setDouble(5,value); } }
			public DatPtr z_limit { get { return new DatPtr(this,5); } }
		public double m_occupancy { get { return getDouble(6); } set { setDouble(6,value); } }
			public DatPtr z_occupancy { get { return new DatPtr(this,6); } }
		public int m_id_xbs_measurementres { get { return getInt(7); } set { setInt(7,value); } }
			public DatPtr z_id_xbs_measurementres { get { return new DatPtr(this,7); } }
	}

	public class YXbsLevelmeasonlres : Yyy
	{
		public YXbsLevelmeasonlres() { construct("XBS_LevelMeasOnlRes",null); }
		public YXbsLevelmeasonlres(OrmLinker lk) { construct("XBS_LevelMeasOnlRes",lk); }
		public int m_id { get { return getInt(0); } set { setInt(0,value); } }
			public DatPtr z_id { get { return new DatPtr(this,0); } }
		public double m_value { get { return getDouble(1); } set { setDouble(1,value); } }
			public DatPtr z_value { get { return new DatPtr(this,1); } }
		public int m_id_xbs_measurementres { get { return getInt(2); } set { setInt(2,value); } }
			public DatPtr z_id_xbs_measurementres { get { return new DatPtr(this,2); } }
	}

}
