CREATE TABLE [dbo].[STATION_SITE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LON] [float] NULL,
	[LAT] [float] NULL,
	[ADDRES] [varchar](2000) NULL,
	[REGION] [varchar](50) NULL,
 CONSTRAINT [XBS_STATIONSITE_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


