CREATE TABLE [dbo].[SENSOR_EQUIPMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SENSORID] [int] NULL,
	[CODE] [varchar](50) NULL,
	[MANUFACTURER] [varchar](50) NULL,
	[NAME] [varchar](50) NULL,
	[FAMILY] [varchar](50) NULL,
	[TECHID] [varchar](200) NULL,
	[VERSION] [varchar](50) NULL,
	[LOWERFREQ] [float] NULL,
	[UPPERFREQ] [float] NULL,
	[RBWMIN] [float] NULL,
	[RBWMAX] [float] NULL,
	[VBWMIN] [float] NULL,
	[VBWMAX] [float] NULL,
	[MOBILITY] [tinyint] NULL,
	[FFTPOINTMAX] [float] NULL,
	[REFLEVELDBM] [float] NULL,
	[OPERATIONMODE] [varchar](50) NULL,
	[TYPE] [varchar](50) NULL,
	[EQUIPCLASS] [varchar](50) NULL,
	[TUNINGSTEP] [float] NULL,
	[USETYPE] [varchar](50) NULL,
	[CATEGORY] [varchar](50) NULL,
	[REMARK] [varchar](250) NULL,
	[CUSTTXT1] [varchar](250) NULL,
	[CUSTDATA1] [datetime] NULL,
	[CUSTNBR1] [float] NULL,
 CONSTRAINT [XBS_SENSOREQUIP_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SENSOR_EQUIPMENT]  WITH CHECK ADD  CONSTRAINT [FK_XBS_SENSOREQUIP_XBS_SENSOR] FOREIGN KEY([SENSORID])
REFERENCES [dbo].[SENSOR] ([ID])
GO

ALTER TABLE [dbo].[SENSOR_EQUIPMENT] CHECK CONSTRAINT [FK_XBS_SENSOREQUIP_XBS_SENSOR]
GO


