CREATE TABLE [dbo].[SENSOR_EQUIPMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SENSOR_ID] [int] NULL,
	[CODE] [varchar](50) NULL,
	[MANUFACTURER] [varchar](50) NULL,
	[NAME] [varchar](50) NULL,
	[FAMILY] [varchar](50) NULL,
	[TECHID] [varchar](200) NULL,
	[VERSION] [varchar](50) NULL,
	[LOWER_FREQ] [float] NULL,
	[UPPER_FREQ] [float] NULL,
	[RBW_MIN] [float] NULL,
	[RBW_MAX] [float] NULL,
	[VBW_MIN] [float] NULL,
	[VBW_MAX] [float] NULL,
	[MOBILITY] [tinyint] NULL,
	[FFT_POINT_MAX] [float] NULL,
	[REF_LEVEL_DBM] [float] NULL,
	[OPERATION_MODE] [varchar](50) NULL,
	[TYPE] [varchar](50) NULL,
	[EQUIP_CLASS] [varchar](50) NULL,
	[TUNING_STEP] [float] NULL,
	[USE_TYPE] [varchar](50) NULL,
	[CATEGORY] [varchar](50) NULL,
	[REMARK] [varchar](250) NULL,
	[CUST_TXT1] [varchar](250) NULL,
	[CUST_DATA1] [datetime] NULL,
	[CUST_NBR1] [float] NULL,
 CONSTRAINT [XBS_SENSOREQUIP_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SENSOR_EQUIPMENT]  WITH CHECK ADD  CONSTRAINT [FK_XBS_SENSOREQUIP_XBS_SENSOR] FOREIGN KEY([SENSOR_ID])
REFERENCES [dbo].[SENSOR] ([ID])
GO

ALTER TABLE [dbo].[SENSOR_EQUIPMENT] CHECK CONSTRAINT [FK_XBS_SENSOREQUIP_XBS_SENSOR]
GO


