CREATE TABLE [dbo].[MEAS_STATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[STATIONID] [varchar](50) NULL,
	[GLOBALSID] [varchar](100) NULL,
	[OWNERGLOBALSID] [varchar](100) NULL,
	[STATUS] [varchar](20) NULL,
	[STANDARD] [varchar](50) NULL,
	[ID_XBS_MEASTASK] [bigint] NULL,
	[ID_OWNER] [bigint] NULL,
	[ID_SITE] [bigint] NULL,
	[ID_LICENCE] [bigint] NULL,
 CONSTRAINT [XBS_MEASSTATION_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MEAS_STATION]  WITH CHECK ADD  CONSTRAINT [FK_MEAS_STATION_LICENCE_INFO] FOREIGN KEY([ID_LICENCE])
REFERENCES [dbo].[LICENCE_INFO] ([ID])
GO

ALTER TABLE [dbo].[MEAS_STATION] CHECK CONSTRAINT [FK_MEAS_STATION_LICENCE_INFO]
GO

ALTER TABLE [dbo].[MEAS_STATION]  WITH CHECK ADD  CONSTRAINT [FK_MEAS_STATION_MEAS_TASK] FOREIGN KEY([ID_XBS_MEASTASK])
REFERENCES [dbo].[MEAS_TASK] ([ID])
GO

ALTER TABLE [dbo].[MEAS_STATION] CHECK CONSTRAINT [FK_MEAS_STATION_MEAS_TASK]
GO

ALTER TABLE [dbo].[MEAS_STATION]  WITH CHECK ADD  CONSTRAINT [FK_MEAS_STATION_OWNER_DATA] FOREIGN KEY([ID_OWNER])
REFERENCES [dbo].[OWNER_DATA] ([ID])
GO

ALTER TABLE [dbo].[MEAS_STATION] CHECK CONSTRAINT [FK_MEAS_STATION_OWNER_DATA]
GO

ALTER TABLE [dbo].[MEAS_STATION]  WITH CHECK ADD  CONSTRAINT [FK_MEAS_STATION_STATION_SITE] FOREIGN KEY([ID_SITE])
REFERENCES [dbo].[STATION_SITE] ([ID])
GO

ALTER TABLE [dbo].[MEAS_STATION] CHECK CONSTRAINT [FK_MEAS_STATION_STATION_SITE]
GO


