CREATE TABLE [dbo].[TASK_PARAMETERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SDRTASKID] [nvarchar](100) NULL,
	[MEASTYPE] [nvarchar](100) NULL,
	[MINFREQ] [float] NULL,
	[MAXFREQ] [float] NULL,
	[RBW] [float] NULL,
	[VBW] [float] NULL,
	[STEPSO] [float] NULL,
	[NCHENAL] [numeric](9, 0) NULL,
	[LEVELMINOCCUP] [float] NULL,
	[TYPESO] [nvarchar](100) NULL,
	[STATUS] [nvarchar](20) NULL,
	[RECEIVEIQSTREAM] [float] NULL,
	[TYPETECHNOLOGY] [nvarchar](100) NULL,
	[STARTTIME] [datetime] NULL,
	[STOPTTIME] [datetime] NULL,
	[NCOUNT] [numeric](9, 0) NULL,
	[SWEEPTIME] [float] NULL,
	[SENSORID] [numeric](9, 0) NULL,
	[CMPTRACEJUSTWITHREFLVL] [numeric](1, 0) NULL,
	[AUTODEVISIONEMITTING] [numeric](1, 0) NULL,
	[FILTRATIONTRACE] [numeric](1, 0) NULL,
	[DIFFMINMAX] [numeric](22, 8) NULL,
	[ALLOWEXCESSDB] [numeric](22, 8) NULL,
	[PERCENTFORCALCNOICE] [numeric](22, 8) NULL,
	[SIGNALIZATIONNCOUNT] [numeric](9, 0) NULL,
	[SIGNALIZATIONNCHENAL] [numeric](9, 0) NULL,
 CONSTRAINT [PK_XBS_TASKPARAMETERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


