CREATE TABLE [dbo].[SENSOR_POLYGON](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SENSORID] [int] NULL,
	[LON] [float] NULL,
	[LAT] [float] NULL,
 CONSTRAINT [XBS_SENSORPOLIG_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SENSOR_POLYGON]  WITH NOCHECK ADD  CONSTRAINT [FK_SENSORPOLIG_ID] FOREIGN KEY([SENSORID])
REFERENCES [dbo].[SENSOR] ([ID])
GO

ALTER TABLE [dbo].[SENSOR_POLYGON] NOCHECK CONSTRAINT [FK_SENSORPOLIG_ID]
GO

ALTER TABLE [dbo].[SENSOR_POLYGON]  WITH CHECK ADD  CONSTRAINT [FK_XBS_SENSORPOLIG_XBS_SENSOR] FOREIGN KEY([SENSORID])
REFERENCES [dbo].[SENSOR] ([ID])
GO

ALTER TABLE [dbo].[SENSOR_POLYGON] CHECK CONSTRAINT [FK_XBS_SENSORPOLIG_XBS_SENSOR]
GO



