CREATE TABLE [dbo].[SENSOR_LOCATION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SENSOR_ID] [int] NULL,
	[DATE_FROM] [datetime] NULL,
	[DATE_TO] [datetime] NULL,
	[DATE_CREATED] [datetime] NULL,
	[STATUS] [varchar](25) NULL,
	[LON] [float] NULL,
	[LAT] [float] NULL,
	[ASL] [float] NULL,
 CONSTRAINT [XBS_SENSORLOCATION_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SENSOR_LOCATION]  WITH NOCHECK ADD  CONSTRAINT [FK_SENSORLOCATION_ID] FOREIGN KEY([SENSOR_ID])
REFERENCES [dbo].[SENSOR] ([ID])
GO

ALTER TABLE [dbo].[SENSOR_LOCATION] NOCHECK CONSTRAINT [FK_SENSORLOCATION_ID]
GO

ALTER TABLE [dbo].[SENSOR_LOCATION]  WITH CHECK ADD  CONSTRAINT [FK_XBS_SENSORLOCATION_XBS_SENSOR] FOREIGN KEY([SENSOR_ID])
REFERENCES [dbo].[SENSOR] ([ID])
GO

ALTER TABLE [dbo].[SENSOR_LOCATION] CHECK CONSTRAINT [FK_XBS_SENSORLOCATION_XBS_SENSOR]
GO


