CREATE TABLE [dbo].[SIGNAL_MASK](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOSS_DB] [float] NULL,
	[FREQ_KHZ] [float] NULL,
	[REFERENCE_SIGNAL_ID] [bigint] NULL,
 CONSTRAINT [PK_XBS_SIGNALMASKRAW] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SIGNAL_MASK]  WITH CHECK ADD  CONSTRAINT [FK_SIGNAL_MASK_REFERENCE_SIGNAL] FOREIGN KEY([REFERENCE_SIGNAL_ID])
REFERENCES [dbo].[REFERENCE_SIGNAL] ([ID])
GO

ALTER TABLE [dbo].[SIGNAL_MASK] CHECK CONSTRAINT [FK_SIGNAL_MASK_REFERENCE_SIGNAL]
GO


