CREATE TABLE [dbo].[TASK_PARAMETERS_FREQ](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FREQ_CH] [float] NULL,
	[TASK_PARAMETERS_ID] [bigint] NULL,
 CONSTRAINT [PK_XBS_TASKPARAMFREQ] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TASK_PARAMETERS_FREQ]  WITH CHECK ADD  CONSTRAINT [FK_TASK_PARAMETERS_FREQ_TASK_PARAMETERS] FOREIGN KEY([TASK_PARAMETERS_ID])
REFERENCES [dbo].[TASK_PARAMETERS] ([ID])
GO

ALTER TABLE [dbo].[TASK_PARAMETERS_FREQ] CHECK CONSTRAINT [FK_TASK_PARAMETERS_FREQ_TASK_PARAMETERS]
GO


