CREATE TABLE [dbo].[SENSOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SENSORIDENTIFIER_ID] [int] NULL,
	[STATUS] [varchar](25) NULL,
	[NAME] [varchar](150) NULL,
	[ADMINISTRATION] [varchar](50) NULL,
	[NETWORKID] [varchar](150) NULL,
	[REMARK] [varchar](250) NULL,
	[BIUSEDATE] [datetime] NULL,
	[EOUSEDATE] [datetime] NULL,
	[AZIMUTH] [float] NULL,
	[ELEVATION] [float] NULL,
	[AGL] [float] NULL,
	[IDSYSARGUS] [varchar](50) NULL,
	[TYPESENSOR] [varchar](50) NULL,
	[STEPMEASTIME] [float] NULL,
	[RXLOSS] [float] NULL,
	[OPHHFR] [float] NULL,
	[OPHHTO] [float] NULL,
	[OPDAYS] [varchar](50) NULL,
	[CUSTTXT1] [varchar](50) NULL,
	[CUSTDATA1] [datetime] NULL,
	[CUSTNBR1] [float] NULL,
	[DATECREATED] [datetime] NULL,
	[CREATEDBY] [varchar](50) NULL,
	[APIVERSION] [varchar](10) NULL,
	[TECHID] [varchar](150) NULL,
 CONSTRAINT [XBS_SENSOR_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SENSOR] ADD  CONSTRAINT [DF__XBS_SENSO__APIVE__6EF57B66]  DEFAULT ('v1.0') FOR [APIVERSION]
GO


