CREATE TABLE [dbo].[SECTOR](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IDSECTOR] [varchar](100) NULL,
	[AGL] [float] NULL,
	[EIRP] [float] NULL,
	[AZIMUT] [float] NULL,
	[BW] [float] NULL,
	[CLASSEMISSION] [varchar](20) NULL,
	[ID_MEASSTATION] [bigint] NULL,
 CONSTRAINT [XBS_SECTOR_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SECTOR]  WITH CHECK ADD  CONSTRAINT [FK_SECTOR_MEAS_STATION] FOREIGN KEY([ID_MEASSTATION])
REFERENCES [dbo].[MEAS_STATION] ([ID])
GO

ALTER TABLE [dbo].[SECTOR] CHECK CONSTRAINT [FK_SECTOR_MEAS_STATION]
GO


