CREATE TABLE [dbo].[SECTOR_MASK_ELEMENT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LEVEL] [float] NULL,
	[BW] [float] NULL,
	[SECTOR_ID] [bigint] NULL,
 CONSTRAINT [XBS_SECTORMASKELEM_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SECTOR_MASK_ELEMENT]  WITH CHECK ADD  CONSTRAINT [FK_SECTOR_MASK_ELEMENT_SECTOR] FOREIGN KEY([SECTOR_ID])
REFERENCES [dbo].[SECTOR] ([ID])
GO

ALTER TABLE [dbo].[SECTOR_MASK_ELEMENT] CHECK CONSTRAINT [FK_SECTOR_MASK_ELEMENT_SECTOR]
GO


