CREATE TABLE [dbo].[MEAS_TASK](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[STATUS] [varchar](50) NULL,
	[TASKID] [varchar](50) NULL,
	[SDRNSERVER] [varchar](50) NULL,
	[SENSORNAME] [varchar](50) NULL,
	[EQUIPMENTTECHID] [varchar](200) NULL,
	[TIMESTART] [datetime] NULL,
	[TIMESTOP] [datetime] NULL,
	[PRIORITY] [int] NULL,
	[SCANPERTASKNUMBER] [int] NULL,
	[MOBEQMEASUREMENTS] [varchar](4000) NULL,
 CONSTRAINT [XBS_MEASTASK_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


