CREATE TABLE [dbo].[SCAN_PARAMETER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[STANDARD] [varchar](50) NULL,
	[FREQ_RELATIVE] [float] NULL,
	[LEVEL_DBM] [float] NULL,
	[DETECT_LEVEL_DBM] [float] NULL,
	[MAX_PERMISS_BW] [float] NULL,
	[RBW] [float] NULL,
	[VBW] [float] NULL,
	[SCAN_BW] [float] NULL,
	[MEAS_TIME_SEC] [float] NULL,
	[REF_LEVEL_DBM] [float] NULL,
	[DETECT_TYPE] [varchar](50) NULL,
	[PREAMPLIFICATION] [int] NULL,
	[RF_ATTENUATION] [int] NULL,
	[MEAS_TASK_ID] [bigint] NULL,
 CONSTRAINT [XBS_SCANPARAMETER_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SCAN_PARAMETER]  WITH CHECK ADD  CONSTRAINT [FK_XBS_SCANPARAMETER_XBS_MEASTASK] FOREIGN KEY([MEAS_TASK_ID])
REFERENCES [dbo].[MEAS_TASK] ([ID])
GO

ALTER TABLE [dbo].[SCAN_PARAMETER] CHECK CONSTRAINT [FK_XBS_SCANPARAMETER_XBS_MEASTASK]
GO


