CREATE TABLE [dbo].[ANTENNA_PATTERN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SENSOR_ANTENNA_ID] [int] NULL,
	[FREQ] [float] NULL,
	[GAIN] [float] NULL,
	[DIAGA] [varchar](1000) NULL,
	[DIAGH] [varchar](1000) NULL,
	[DIAGV] [varchar](1000) NULL,
 CONSTRAINT [XBS_ANTENNAPATTERN_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ANTENNA_PATTERN]  WITH NOCHECK ADD  CONSTRAINT [FK_ANTENNAPATTERN_ID] FOREIGN KEY([SENSOR_ANTENNA_ID])
REFERENCES [dbo].[SENSOR_ANTENNA] ([ID])
GO

ALTER TABLE [dbo].[ANTENNA_PATTERN] NOCHECK CONSTRAINT [FK_ANTENNAPATTERN_ID]
GO

ALTER TABLE [dbo].[ANTENNA_PATTERN]  WITH CHECK ADD  CONSTRAINT [FK_XBS_ANTENNAPATTERN_XBS_SENSORANTENNA] FOREIGN KEY([SENSOR_ANTENNA_ID])
REFERENCES [dbo].[SENSOR_ANTENNA] ([ID])
GO

ALTER TABLE [dbo].[ANTENNA_PATTERN] CHECK CONSTRAINT [FK_XBS_ANTENNAPATTERN_XBS_SENSORANTENNA]
GO

