CREATE TABLE [dbo].[MEAS_STATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[STATION_ID] [varchar](50) NULL,
	[GLOBAL_SID] [varchar](100) NULL,
	[OWNER_GLOBAL_SID] [varchar](100) NULL,
	[STATUS] [varchar](20) NULL,
	[STANDARD] [varchar](50) NULL,
	[MEAS_TASK_ID] [bigint] NULL,
	[OWNER_DATA_ID] [bigint] NULL,
	[STATION_SITE_ID] [bigint] NULL,
	[LICENCE_INFO_ID] [bigint] NULL,
 CONSTRAINT [XBS_MEASSTATION_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MEAS_STATION]  WITH CHECK ADD  CONSTRAINT [FK_MEAS_STATION_LICENCE_INFO] FOREIGN KEY([LICENCE_INFO_ID])
REFERENCES [dbo].[LICENCE_INFO] ([ID])
GO

ALTER TABLE [dbo].[MEAS_STATION] CHECK CONSTRAINT [FK_MEAS_STATION_LICENCE_INFO]
GO

ALTER TABLE [dbo].[MEAS_STATION]  WITH CHECK ADD  CONSTRAINT [FK_MEAS_STATION_MEAS_TASK] FOREIGN KEY([MEAS_TASK_ID])
REFERENCES [dbo].[MEAS_TASK] ([ID])
GO

ALTER TABLE [dbo].[MEAS_STATION] CHECK CONSTRAINT [FK_MEAS_STATION_MEAS_TASK]
GO

ALTER TABLE [dbo].[MEAS_STATION]  WITH CHECK ADD  CONSTRAINT [FK_MEAS_STATION_OWNER_DATA] FOREIGN KEY([OWNER_DATA_ID])
REFERENCES [dbo].[OWNER_DATA] ([ID])
GO

ALTER TABLE [dbo].[MEAS_STATION] CHECK CONSTRAINT [FK_MEAS_STATION_OWNER_DATA]
GO

ALTER TABLE [dbo].[MEAS_STATION]  WITH CHECK ADD  CONSTRAINT [FK_MEAS_STATION_STATION_SITE] FOREIGN KEY([STATION_SITE_ID])
REFERENCES [dbo].[STATION_SITE] ([ID])
GO

ALTER TABLE [dbo].[MEAS_STATION] CHECK CONSTRAINT [FK_MEAS_STATION_STATION_SITE]
GO


