
CREATE TABLE [dbo].[SECTOR_FREQ](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IDPLAN] [int] NULL,
	[CHANNAL_NUMBER] [int] NULL,
	[FREQUENCY] [float] NULL,
	[SECTOR_ID] [bigint] NULL,
 CONSTRAINT [XBS_SECTORFREQ_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SECTOR_FREQ]  WITH CHECK ADD  CONSTRAINT [FK_SECTOR_FREQ_SECTOR] FOREIGN KEY([SECTOR_ID])
REFERENCES [dbo].[SECTOR] ([ID])
GO

ALTER TABLE [dbo].[SECTOR_FREQ] CHECK CONSTRAINT [FK_SECTOR_FREQ_SECTOR]
GO


