CREATE TABLE [dbo].[TASK_PARAMETERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SDRTASKID] [nvarchar](100) NULL,
	[MEAS_TYPE] [nvarchar](100) NULL,
	[MIN_FREQ] [float] NULL,
	[MAX_FREQ] [float] NULL,
	[RBW] [float] NULL,
	[VBW] [float] NULL,
	[STEP_SO] [float] NULL,
	[NCHENAL] [numeric](9, 0) NULL,
	[LEVEL_MIN_OCCUP] [float] NULL,
	[TYPE_SO] [nvarchar](100) NULL,
	[STATUS] [nvarchar](20) NULL,
	[RECEIVE_IQ_STREAM] [float] NULL,
	[TYPE_TECHNOLOGY] [nvarchar](100) NULL,
	[START_TIME] [datetime] NULL,
	[STOP_TIME] [datetime] NULL,
	[NCOUNT] [numeric](9, 0) NULL,
	[SWEEP_TIME] [float] NULL,
	[SENSOR_ID] [int] NULL,
	[COMPARE_TRACE_JUST_WITH_REF_LEVELS] [bit] NULL,
	[AUTO_DEVISION_EMITTING] [bit] NULL,
	[FILTRATION_TRACE] [bit] NULL,
	[DIFF_MINMAX] [numeric](22, 8) NULL,
	[ALLOW_EXCESS_DB] [numeric](22, 8) NULL,
	[PERCENT_FOR_CALC_NOICE] [numeric](22, 8) NULL,
	[SIGNALIZATION_NCOUNT] [numeric](9, 0) NULL,
	[SIGNALIZATION_NCHENAL] [numeric](9, 0) NULL,
 CONSTRAINT [PK_XBS_TASKPARAMETERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO