CREATE TABLE [dbo].[LICENCE_INFO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ICSM_ID] [bigint] NULL,
	[NAME] [varchar](100) NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[CLOSE_DATE] [datetime] NULL,
 CONSTRAINT [XBS_LICENCEINFO_PK] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


