SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO 

CREATE TABLE [CALC].[CONTEXT_STATION_PATTERNS](
	[STATION_ID] [bigint]  NOT NULL,
	[ANTENNA_PLANE] [nvarchar](1)  NOT NULL,
	[WAVE_PLANE] [nvarchar](1)  NOT NULL,
	[LOSS_DB] [varbinary](max) NOT NULL,
	[ANGLE_DEG] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_CONTEXT_STATION_PATTERNS] PRIMARY KEY CLUSTERED 
(
	[STATION_ID] ASC, [ANTENNA_PLANE] ASC, [WAVE_PLANE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]  TEXTIMAGE_ON [PRIMARY]
GO
