SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[PROJECT_MAP_CONTENT_SOURCES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CONTENT_ID] [bigint] NOT NULL,
	[INFOC_MAP_ID] [bigint] NOT NULL,
	[INFOC_MAP_NAME] [nvarchar](450) NOT NULL,
	[COVERAGE] [numeric](22, 8) NULL,
	[CRD_UPL_X] [int] NOT NULL,
	[CRD_UPL_Y] [int] NOT NULL,
	[CRD_LWR_X] [int] NOT NULL,
	[CRD_LWR_Y] [int] NOT NULL,
	[PRIORITY_CODE] [tinyint] NULL,
	[PRIORITY_NAME] [nvarchar](50) NULL,
 CONSTRAINT [PK_PROJECT_MAP_CONTENT_SOURCES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

