SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[CONTEXT_PLANNEDCALCTASK](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CONTEXT_ID] [bigint] NOT NULL,
	[TYPE_CODE] [int] NOT NULL,
	[TYPE_NAME] [nvarchar](250) NOT NULL,
	[START_NUMBER] [int] NOT NULL,
	[MAP_NAME] [nvarchar](250) NULL,
	[NOTE] [nvarchar](max) NULL,
 CONSTRAINT [PK_CONTEXT_PLANNEDCALCTASK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



