SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[CALCTASKS_GN06_ARGS](
	[TASK_ID] [bigint] NOT NULL,
	[AZIMUTH_STEP_DEG] [float] NULL,
	[ADDITIONAL_CONTOURS_BY_DISTANCE] [bit] NULL,
	[INFOC_MEAS_RESULTS] [varbinary](max) NULL,
	[CONTURE_BY_FIELD_STRENGTH] [bit] NULL,
	[FIELD_STRENGTH] [varbinary](max) NULL,
	[SUBSCRIBERS_HEIGHT] [int] NULL,
	[PERCENTAGE_TIME] [real] NULL,
	[USE_EFFECTIVE_HEIGHT] [bit] NULL,
	[CALCULATION_TYPE_CODE] [tinyint] NOT NULL,
	[CALCULATION_TYPE_NAME] [nvarchar](50) NULL,
	[BROADCASTING_EXTEND] [nvarchar](max) NULL,
 CONSTRAINT [PK_CALCTASKS_GN06_ARGS] PRIMARY KEY CLUSTERED 
(
	[TASK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
