SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO 

CREATE TABLE [CALC].[CLIENT_CONTEXTS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PROJECT_ID] [bigint] NOT NULL,
	[OWNER_INSTANCE] [nvarchar](250) NOT NULL,
	[OWNER_CONTEXT_ID] [uniqueidentifier] NOT NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,

 CONSTRAINT [PK_CLIENT_CONTEXTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

ALTER TABLE [CALC].[CLIENT_CONTEXTS] ADD  CONSTRAINT [DF_CLIENT_CONTEXTS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO