SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO 

CREATE TABLE [CALC].[CONTEXT_STATIONS_ANTENNA](
	[ID] [bigint] NOT NULL,
	[GAIN_DB] [REAL] NOT NULL,
	[TILT_DEG] [FLOAT] NOT NULL,
	[AZIMUTH_DEG] [FLOAT] NOT NULL,
	[XPD_DB] [REAL] NOT NULL,
	[ITU_PATTERN_CODE] [tinyint] NOT NULL,
	[ITU_PATTERN_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CONTEXT_STATIONS_ANTENNA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

