SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO 

CREATE TABLE [CALC].[CONTEXT_STATIONS_RECEIVER](
	[ID] [bigint] NOT NULL,
	[FREQ_MHZ] [FLOAT] NOT NULL,
	[BW_KHZ] [FLOAT] NOT NULL,
	[LOSS_DB] [REAL] NOT NULL,
	[KTBF_DBM] [REAL] NOT NULL,
	[THRESHOLD_DBM] [REAL] NOT NULL,
	[POLARIZING_CODE] [tinyint] NOT NULL,
	[POLARIZING_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CONTEXT_STATIONS_RECEIVER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

