SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[REF_SPECTRUM_BY_DRIVE_TESTS_ARGS_DEF](
 [RESULT_ID] [bigint] NOT NULL,
 [TASK_ID] [bigint] NOT NULL,
 [COMMENTS] [nvarchar](2000)  NULL,
 [POWER_THRESHOLD_DBM] [FLOAT]  NULL,
 [SENSOR_IDS] [varbinary](max) NULL,
 [STATION_IDS] [varbinary](max) NULL,
 CONSTRAINT [PK_REF_SPECTRUM_BY_DRIVE_TESTS_ARGS_DEF] PRIMARY KEY CLUSTERED 
(
	[TASK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

