SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO 

CREATE TABLE [CALC].[CONTEXT_STATIONS_SITE](
	[ID] [bigint] NOT NULL,
	[LON_DEC] [FLOAT] NOT NULL,
	[LAT_DEC] [FLOAT] NOT NULL,
	[ALT_M] [FLOAT] NOT NULL,
 CONSTRAINT [PK_CONTEXT_STATIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

