SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS](
	[RESULT_ID] [bigint] NOT NULL,
	[DATE_CREATED] [datetimeoffset](7) NOT NULL,
	[PARAMETERS_TASK_ID] [bigint] NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [CALC].[CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS] ADD  CONSTRAINT [DF_CALCRESULTS_REF_SPECTRUM_BY_DRIVE_TESTS]  DEFAULT (sysdatetimeoffset()) FOR [DATE_CREATED]
GO

