SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[CALCTASKS_COVERAGEPROFILES](
	[ID] [bigint] NOT NULL,
	[MODE_CODE] [tinyint] NOT NULL,
	[MODE_NAME] [nvarchar](50) NULL,
	[POINTS_CRDS_X] [varbinary](max) NULL,
	[POINTS_CRDS_Y] [varbinary](max) NULL,
	[RESULT_PATH] [nvarchar](450) NULL,
 CONSTRAINT [PK_CALCTASKS_COVERAGEPROFILES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



