SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[PROJECT_MAP_CONTENTS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MAP_ID] [bigint] NOT NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[TYPE_CODE] [tinyint] NOT NULL,
	[TYPE_NAME] [nvarchar](50) NOT NULL,
	[STEP_DATATYPE] [nvarchar](50) NOT NULL,
	[STEP_DATASIZE] [tinyint] NOT NULL,
	[SOURCE_COUNT] [int] NULL,
	[SOURCE_COVERAGE] [numeric](22,8) NULL,
	[CONTENT_SIZE] [int] NOT NULL,
	[CONTENT_TYPE] [nvarchar](250) NOT NULL,
	[CONTENT_ENCODING] [nvarchar](250) NOT NULL,
	[CONTENT] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_PROJECT_MAP_CONTENTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [CALC].[PROJECT_MAP_CONTENTS] ADD  CONSTRAINT [DF_PROJECT_MAP_CONTENTS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO