SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[CALCRESULTS_STATION_CALIBRATION_DRIVE_TEST](
	[CALCRESULTS_STATION_CALIBRATION_ID] [bigint] NOT NULL,
	[EXTERNAL_SOURCE] [nvarchar](50) NULL,
	[EXTERNAL_CODE] [nvarchar](50) NULL,
	[STATION_GSID] [nvarchar](100) NULL,
	[MEAS_GSID] [nvarchar](100) NULL,
	[RESULT_DRIVE_TEST_STATUS] [nvarchar](50) NULL,
	[MAX_PERCENT_CORELLATION] [float] NULL,
	[COUNT_POINTS_IN_DRIVE_TEST] [int] NULL,
	[DRIVE_TEST_ID] [bigint] NULL,
	[LINK_STATION_MONITORING_ID] [bigint] NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_CALCRESULTS_STATION_CALIBRATION_DRIVE_TEST] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
