SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[CALCTASKS_POINTFIELDSTRENGTH](
	[ID] [bigint] NOT NULL,
	[STATION_ID] [bigint] NOT NULL,
	[POINT_LON_DEC] [FLOAT] NOT NULL,
	[POINT_LAT_DEC] [FLOAT] NOT NULL,
	[POINT_ALT_M]   [FLOAT] NOT NULL,
 CONSTRAINT [PK_CALCTASKS_POINTFIELDSTRENGTH] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



