SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CALC].[CLUTTERS_DESCS_FREQS_CLUTTERS](
	[FREQ_ID] [bigint] NOT NULL,
	[CODE] [tinyint] NOT NULL,
	[LINEAR_LOSS_DBKM] [REAL] NULL,
	[FLAT_LOSS_DB] [REAL] NULL,
	[REFLECTION_MHZ] [REAL] NULL,
	[NOTE] [nvarchar](max) NULL,
 CONSTRAINT [PK_CLUTTERS_DESCS_FREQS_CLUTTERS] PRIMARY KEY CLUSTERED 
(
	[FREQ_ID] ASC,
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO