
CREATE OR REPLACE TRIGGER ICSM.TASKFORCE_AFTER_DELETE
AFTER DELETE
   ON ICSM.TASKFORCE    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='TASKFORCE';
END;
/



CREATE OR REPLACE TRIGGER ICSM.TASKFORCE_AFTER_INSERT
AFTER INSERT
   ON ICSM.TASKFORCE    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='TASKFORCE';
END;
/

CREATE OR REPLACE TRIGGER ICSM.TASKFORCE_AFTER_UPDATE
AFTER UPDATE
   ON ICSM.TASKFORCE    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='TASKFORCE';
END;
/


CREATE OR REPLACE TRIGGER ICSM.TSKF_MEMBER_AFTER_DELETE
AFTER DELETE
   ON ICSM.TSKF_MEMBER    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='TSKF_MEMBER';
END;
/


CREATE OR REPLACE TRIGGER ICSM.TSKF_MEMBER_AFTER_INSERT
AFTER INSERT
   ON ICSM.TSKF_MEMBER    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='TSKF_MEMBER';
END;
/


CREATE OR REPLACE TRIGGER ICSM.TSKF_MEMBER_AFTER_UPDATE
AFTER UPDATE
   ON ICSM.TSKF_MEMBER    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='TSKF_MEMBER';
END;
/


CREATE OR REPLACE TRIGGER ICSM.XWEBCONSTRAINT_AFTER_DELETE
AFTER DELETE
   ON ICSM.XWEBCONSTRAINT    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBCONSTRAINT';
END;
/


CREATE OR REPLACE TRIGGER ICSM.XWEBCONSTRAINT_AFTER_INSERT
AFTER INSERT
   ON ICSM.XWEBCONSTRAINT    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBCONSTRAINT';
END;
/

CREATE OR REPLACE TRIGGER ICSM.XWEBCONSTRAINT_AFTER_UPDATE
AFTER UPDATE
   ON ICSM.XWEBCONSTRAINT    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBCONSTRAINT';
END;
/

CREATE OR REPLACE TRIGGER ICSM.XWEBORDERS_AFTER_DELETE
AFTER DELETE
   ON ICSM.XWEBQUERYORDERS    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERYORDERS';
END;
/

CREATE OR REPLACE TRIGGER ICSM.XWEBORDERS_AFTER_INSERT
AFTER INSERT
   ON ICSM.XWEBQUERYORDERS    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERYORDERS';
END;
/


CREATE OR REPLACE TRIGGER ICSM.XWEBORDERS_AFTER_UPDATE
AFTER UPDATE
   ON ICSM.XWEBQUERYORDERS    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERYORDERS';
END;
/


CREATE OR REPLACE TRIGGER ICSM.XWEBQUERY_AFTER_DELETE
AFTER DELETE
   ON ICSM.XWEBQUERY    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERY';
END;
/

CREATE OR REPLACE TRIGGER ICSM.XWEBQUERY_AFTER_INSERT
AFTER INSERT
   ON ICSM.XWEBQUERY    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERY';
END;
/

CREATE OR REPLACE TRIGGER ICSM.XWEBQUERY_AFTER_UPDATE
AFTER UPDATE
   ON ICSM.XWEBQUERY    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERY';
END;
/

CREATE OR REPLACE TRIGGER ICSM.XWEBTTR_AFTER_DELETE
AFTER DELETE
   ON ICSM.XWEBQUERYATTRIBUTES    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERYATTRIBUTES';
END;
/

CREATE OR REPLACE TRIGGER ICSM.XWEBTTR_AFTER_INSERT
AFTER INSERT
   ON ICSM.XWEBQUERYATTRIBUTES    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERYATTRIBUTES';
END;
/

CREATE OR REPLACE TRIGGER ICSM.XWEBTTR_AFTER_UPDATE
AFTER UPDATE
   ON ICSM.XWEBQUERYATTRIBUTES    FOR EACH ROW
BEGIN

    UPDATE ICSM.XUPDATEOBJECTS A SET A.DATEMODIFIED = SYSDATE WHERE A.OBJTABLE='XWEBQUERYATTRIBUTES';
END;
/