//-------------------------------------------------------------------------
//FILE GENERATED BY ICS MANAGER FROM SCHEMA 'Atdi.Icsm.Plugins.WebQueryExtended' DON'T MODIFY IT;
//-------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace OrmCs
{
	public class YXvWebBc : Yyy
	{
		public YXvWebBc() { construct("XV_WEB_BC",null); }
		public YXvWebBc(OrmLinker lk) { construct("XV_WEB_BC",lk); }
		public string m_licence { get { return getString(0); } set { setString(0,200,value); } }
			public DatPtr z_licence { get { return new DatPtr(this,0); } }
		public int m_lic_id { get { return getInt(1); } set { setInt(1,value); } }
			public DatPtr z_lic_id { get { return new DatPtr(this,1); } }
		public string m_conc_number { get { return getString(2); } set { setString(2,200,value); } }
			public DatPtr z_conc_number { get { return new DatPtr(this,2); } }
		public DateTime m_conc_date_from { get { return getDateTime(3); } set { setDateTime(3,value); } }
			public DatPtr z_conc_date_from { get { return new DatPtr(this,3); } }
		public string m_dozv_number { get { return getString(4); } set { setString(4,200,value); } }
			public DatPtr z_dozv_number { get { return new DatPtr(this,4); } }
		public DateTime m_dozv_date_from { get { return getDateTime(5); } set { setDateTime(5,value); } }
			public DatPtr z_dozv_date_from { get { return new DatPtr(this,5); } }
		public string m_equip_name { get { return getString(6); } set { setString(6,50,value); } }
			public DatPtr z_equip_name { get { return new DatPtr(this,6); } }
		public int m_equip_id { get { return getInt(7); } set { setInt(7,value); } }
			public DatPtr z_equip_id { get { return new DatPtr(this,7); } }
		public string m_modulation { get { return getString(8); } set { setString(8,20,value); } }
			public DatPtr z_modulation { get { return new DatPtr(this,8); } }
		public string m_address { get { return getString(9); } set { setString(9,4000,value); } }
			public DatPtr z_address { get { return new DatPtr(this,9); } }
		public int m_pos_id { get { return getInt(10); } set { setInt(10,value); } }
			public DatPtr z_pos_id { get { return new DatPtr(this,10); } }
		public double m_longitude { get { return getDouble(11); } set { setDouble(11,value); } }
			public DatPtr z_longitude { get { return new DatPtr(this,11); } }
		public double m_latitude { get { return getDouble(12); } set { setDouble(12,value); } }
			public DatPtr z_latitude { get { return new DatPtr(this,12); } }
		public double m_power { get { return getDouble(13); } set { setDouble(13,value); } }
			public DatPtr z_power { get { return new DatPtr(this,13); } }
		public string m_antenna_name { get { return getString(14); } set { setString(14,50,value); } }
			public DatPtr z_antenna_name { get { return new DatPtr(this,14); } }
		public int m_antenna_id { get { return getInt(15); } set { setInt(15,value); } }
			public DatPtr z_antenna_id { get { return new DatPtr(this,15); } }
		public double m_gain { get { return getDouble(16); } set { setDouble(16,value); } }
			public DatPtr z_gain { get { return new DatPtr(this,16); } }
		public double m_agl { get { return getDouble(17); } set { setDouble(17,value); } }
			public DatPtr z_agl { get { return new DatPtr(this,17); } }
		public double m_angle_elev { get { return getDouble(18); } set { setDouble(18,value); } }
			public DatPtr z_angle_elev { get { return new DatPtr(this,18); } }
		public string m_diag { get { return getString(19); } set { setString(19,4000,value); } }
			public DatPtr z_diag { get { return new DatPtr(this,19); } }
		public string m_polarization { get { return getString(20); } set { setString(20,4,value); } }
			public DatPtr z_polarization { get { return new DatPtr(this,20); } }
		public string m_azimuth { get { return getString(21); } set { setString(21,4000,value); } }
			public DatPtr z_azimuth { get { return new DatPtr(this,21); } }
		public string m_tx_freq { get { return getString(22); } set { setString(22,200,value); } }
			public DatPtr z_tx_freq { get { return new DatPtr(this,22); } }
		public string m_rx_freq { get { return getString(23); } set { setString(23,200,value); } }
			public DatPtr z_rx_freq { get { return new DatPtr(this,23); } }
		public string m_des_emission { get { return getString(24); } set { setString(24,9,value); } }
			public DatPtr z_des_emission { get { return new DatPtr(this,24); } }
		public string m_sector_number { get { return getString(25); } set { setString(25,1,value); } }
			public DatPtr z_sector_number { get { return new DatPtr(this,25); } }
		public string m_edrpou { get { return getString(26); } set { setString(26,50,value); } }
			public DatPtr z_edrpou { get { return new DatPtr(this,26); } }
	}

}
