//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Atdi.CoreServices.EntityOrm.Metadata
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Entity", Namespace="http://schemas.atdi.com/orm/entity.xsd", IsNullable=false)]
    public partial class EntityDef {
        
        /// <remarks/>
        public DataSourceDef DataSource;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public FieldDef[] Fields;
        
        /// <remarks/>
        public PrimaryKeyDef PrimaryKey;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(EntityType.Normal)]
        public EntityType Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseEntity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public InheritanceType Inheritance;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InheritanceSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtendEntity;
        
        public EntityDef() {
            this.Type = EntityType.Normal;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class DataSourceDef {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Schema;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataSourceType Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataSourceObject Object;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum DataSourceType {
        
        /// <remarks/>
        Database,
        
        /// <remarks/>
        Json,
        
        /// <remarks/>
        Xml,
        
        /// <remarks/>
        Csv,
        
        /// <remarks/>
        Excel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum DataSourceObject {
        
        /// <remarks/>
        Table,
        
        /// <remarks/>
        Query,
        
        /// <remarks/>
        File,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class PrimaryKeyFieldRefDef {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SortDirection.Ascending)]
        public SortDirection SortOrder;
        
        public PrimaryKeyFieldRefDef() {
            this.SortOrder = SortDirection.Ascending;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum SortDirection {
        
        /// <remarks/>
        Ascending,
        
        /// <remarks/>
        Descending,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class PrimaryKeyDef {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FieldRef")]
        public PrimaryKeyFieldRefDef[] FieldRef;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Clustered;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class PrimaryKeyMappedDef {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KeyFieldName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PrimaryKeyMappedMatchWith MatchWith;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum PrimaryKeyMappedMatchWith {
        
        /// <remarks/>
        Value,
        
        /// <remarks/>
        Field,
        
        /// <remarks/>
        SourceName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class RelationConditionDef {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RelationConditionJoinType JoinType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum RelationConditionJoinType {
        
        /// <remarks/>
        Inner,
        
        /// <remarks/>
        Outer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class FieldDef {
        
        /// <remarks/>
        public RelationConditionDef RelationCondition;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Mapped", IsNullable=false)]
        public PrimaryKeyMappedDef[] PrimaryKeyMapping;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Desc;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Required;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FieldSourceType SourceType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public UnitType Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitSpecified;
        
        public FieldDef() {
            this.Required = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum FieldSourceType {
        
        /// <remarks/>
        Column,
        
        /// <remarks/>
        Reference,
        
        /// <remarks/>
        Extension,
        
        /// <remarks/>
        Relation,
        
        /// <remarks/>
        Expression,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum UnitType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Angle.Degree")]
        AngleDegree,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Frequency.Hz")]
        FrequencyHz,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Frequency.kHz")]
        FrequencykHz,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Frequency.MHz")]
        FrequencyMHz,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Latitude.DEC")]
        LatitudeDEC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Length.m")]
        Lengthm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Level.dBm")]
        LeveldBm,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Longitude.DEC")]
        LongitudeDEC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Power.dB")]
        PowerdB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum EntityType {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Extention,
        
        /// <remarks/>
        Predefined,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum InheritanceType {
        
        /// <remarks/>
        Prototype,
        
        /// <remarks/>
        Role,
        
        /// <remarks/>
        Simple,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("DataType", Namespace="http://schemas.atdi.com/orm/entity.xsd", IsNullable=false)]
    public partial class DataTypeDef {
        
        /// <remarks/>
        public DataTypeDefAutonum Autonum;
        
        /// <remarks/>
        public DataTypeDefCodeVarType CodeVarType;
        
        /// <remarks/>
        public DataTypeDefSourceVarType SourceVarType;
        
        /// <remarks/>
        public DataTypeDefLength Length;
        
        /// <remarks/>
        public DataTypeDefPrecision Precision;
        
        /// <remarks/>
        public DataTypeDefScale Scale;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataSourceType DataSourceType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class DataTypeDefAutonum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Start;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Step;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class DataTypeDefCodeVarType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public CodeVarType Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum CodeVarType {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Bytes,
        
        /// <remarks/>
        Guid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class DataTypeDefSourceVarType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public SourceVarType Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public enum SourceVarType {
        
        /// <remarks/>
        INT_1,
        
        /// <remarks/>
        INT_8,
        
        /// <remarks/>
        INT_16,
        
        /// <remarks/>
        INT_32,
        
        /// <remarks/>
        INT_64,
        
        /// <remarks/>
        NCHAR,
        
        /// <remarks/>
        NVARCHAR,
        
        /// <remarks/>
        NTEXT,
        
        /// <remarks/>
        CHAR,
        
        /// <remarks/>
        VARCHAR,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        BIT,
        
        /// <remarks/>
        BYTE,
        
        /// <remarks/>
        BYTES,
        
        /// <remarks/>
        BLOB,
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        TIME,
        
        /// <remarks/>
        DATETIME,
        
        /// <remarks/>
        DOUBLE,
        
        /// <remarks/>
        FLOAT,
        
        /// <remarks/>
        DECIMAL,
        
        /// <remarks/>
        GUID,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        JSON,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class DataTypeDefLength {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class DataTypeDefPrecision {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class DataTypeDefScale {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Unit", Namespace="http://schemas.atdi.com/orm/entity.xsd", IsNullable=false)]
    public partial class UnitDef {
        
        /// <remarks/>
        public UnitDefDimension Dimension;
        
        /// <remarks/>
        public UnitDefCategory Category;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class UnitDefDimension {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class UnitDefCategory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Environment", Namespace="http://schemas.atdi.com/orm/entity.xsd", IsNullable=false)]
    public partial class EnvironmentDef {
        
        /// <remarks/>
        public EnvironmentDefRootPath RootPath;
        
        /// <remarks/>
        public EnvironmentDefAssembly Assembly;
        
        /// <remarks/>
        public EnvironmentDefNamespace Namespace;
        
        /// <remarks/>
        public EnvironmentDefEntitiesPath EntitiesPath;
        
        /// <remarks/>
        public EnvironmentDefDataTypesPath DataTypesPath;
        
        /// <remarks/>
        public EnvironmentDefUnitsPath UnitsPath;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class EnvironmentDefRootPath {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class EnvironmentDefAssembly {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class EnvironmentDefNamespace {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class EnvironmentDefEntitiesPath {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class EnvironmentDefDataTypesPath {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.atdi.com/orm/entity.xsd")]
    public partial class EnvironmentDefUnitsPath {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
}
