CREATE SCHEMA [INFOC]
GO

CREATE SCHEMA [STATIONS]
GO

CREATE SCHEMA [SDRNSVR]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[CLUTTERS_DESCS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MAP_ID] [bigint] NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[NAME] [nvarchar](450) NOT NULL,
	[NOTE] [nvarchar](max) NULL,
 CONSTRAINT [PK_CLUTTERS_DESCS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [INFOC].[CLUTTERS_DESCS] ADD  CONSTRAINT [DF_CLUTTERS_DESCS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[CLUTTERS_DESCS_CLUTTERS](
	[CLUTTERS_DESC_ID] [bigint] NOT NULL,
	[CODE] [tinyint] NOT NULL,
	[NAME] [nvarchar](150) NOT NULL,
	[NOTE] [nvarchar](max) NULL,
	[HEIGHT_M] [tinyint] NOT NULL,
 CONSTRAINT [PK_CLUTTERS_DESCS_CLUTTERS] PRIMARY KEY CLUSTERED 
(
	[CLUTTERS_DESC_ID] ASC,
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[CLUTTERS_DESCS_FREQS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CLUTTERS_DESC_ID] [bigint] NOT NULL,
	[FREQ_MHZ] [FLOAT] NOT NULL,
	[NOTE] [nvarchar](max) NULL
 CONSTRAINT [PK_CLUTTERS_DESCS_FREQS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[CLUTTERS_DESCS_FREQS_CLUTTERS](
	[FREQ_ID] [bigint] NOT NULL,
	[CODE] [tinyint] NOT NULL,
	[LINEAR_LOSS_DBKM] [REAL] NULL,
	[FLAT_LOSS_DB] [REAL] NULL,
	[REFLECTION_MHZ] [REAL] NULL,
	[NOTE] [nvarchar](max) NULL,
 CONSTRAINT [PK_CLUTTERS_DESCS_FREQS_CLUTTERS] PRIMARY KEY CLUSTERED 
(
	[FREQ_ID] ASC,
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[INTEGRATION_LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[OBJECT_ID] [bigint]  NOT NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[STATUS_CODE] [tinyint] NOT NULL,
	[STATUS_NAME] [nvarchar](50) NOT NULL,
	[STATUS_NOTE] [nvarchar](max) NULL,
	[START_TIME] [datetimeoffset](7) NULL,
	[FINISH_TIME] [datetimeoffset](7) NULL,
	[SYNC_TOTAL] [nvarchar](max) NULL,
 CONSTRAINT [PK_INTEGRATION_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [INFOC].[INTEGRATION_LOG] ADD  CONSTRAINT [DF_INTEGRATION_LOG_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[INTEGRATION_OBJECTS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DATA_SOURCE] [nvarchar](150) NOT NULL,
	[OBJECT_NAME] [nvarchar](150) NOT NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[SYNC_KEY_CONTENT] [varbinary](max) NULL,
	[SYNC_KEY_TYPE] [nvarchar](250) NULL,
	[SYNC_KEY_NOTE] [nvarchar](max) NULL,
	[LAST_SYNC_TIME] [datetimeoffset](7) NULL,
 CONSTRAINT [PK_INTEGRATION_OBJECTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [INFOC].[INTEGRATION_OBJECTS] ADD  CONSTRAINT [DF_INTEGRATION_OBJECTS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[MAP_SECTORS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MAP_ID] [bigint] NOT NULL,
	[SECTOR_NAME] [nvarchar](250) NOT NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[AXIS_X_INDEX] [int] NOT NULL,
	[AXIS_Y_INDEX] [int] NOT NULL,
	[AXIS_X_NUMBER] [int] NOT NULL,
	[AXIS_Y_NUMBER] [int] NOT NULL,
	[CRD_UPL_X] [int] NOT NULL,
	[CRD_UPL_Y] [int] NOT NULL,
	[CRD_UPR_X] [int] NOT NULL,
	[CRD_UPR_Y] [int] NOT NULL,
	[CRD_LWL_X] [int] NOT NULL,
	[CRD_LWL_Y] [int] NOT NULL,
	[CRD_LWR_X] [int] NOT NULL,
	[CRD_LWR_Y] [int] NOT NULL,
	[CONTENT_SIZE] [int] NOT NULL,
	[CONTENT_TYPE] [nvarchar](250) NOT NULL,
	[CONTENT_ENCODING] [nvarchar](250) NOT NULL,
	[CONTENT] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_MAP_SECTORS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [INFOC].[MAP_SECTORS] ADD  CONSTRAINT [DF_MAP_SECTORS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[MAPS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[STATUS_CODE] [tinyint] NOT NULL,
	[STATUS_NAME] [nvarchar](50) NOT NULL,
	[STATUS_NOTE] [nvarchar](max) NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[TYPE_CODE] [tinyint] NOT NULL,
	[TYPE_NAME] [nvarchar](50) NOT NULL,
	[PROJECTION] [nvarchar](50) NOT NULL,
	[STEP_UNIT] [nvarchar](10) NOT NULL,
	[STEP_DATATYPE] [nvarchar](50) NOT NULL,
	[STEP_DATASIZE] [tinyint] NOT NULL,
	[AXIS_X_NUMBER] [int] NOT NULL,
	[AXIS_X_STEP] [int] NOT NULL,
	[AXIS_Y_NUMBER] [int] NOT NULL,
	[AXIS_Y_STEP] [int] NOT NULL,
	[CRD_UPL_X] [int] NOT NULL,
	[CRD_UPL_Y] [int] NOT NULL,
	[CRD_UPR_X] [int] NOT NULL,
	[CRD_UPR_Y] [int] NOT NULL,
	[CRD_LWL_X] [int] NOT NULL,
	[CRD_LWL_Y] [int] NOT NULL,
	[CRD_LWR_X] [int] NOT NULL,
	[CRD_LWR_Y] [int] NOT NULL,
	[CONTENT_SIZE] [int] NOT NULL,
	[CONTENT_SOURCE] [nvarchar](50) NOT NULL,
	[FILE_NAME] [nvarchar](250) NULL,
	[FILE_SIZE] [int] NULL,
	[MAP_NAME] [nvarchar](450) NOT NULL,
	[MAP_NOTE] [nvarchar](max) NULL,
	[SECTORS_COUNT] [int] NULL,
	[SECTORS_X_COUNT] [int] NULL,
	[SECTORS_Y_COUNT] [int] NULL,
 CONSTRAINT [PK_MAPS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [INFOC].[MAPS] ADD  CONSTRAINT [DF_MAPS_STATUS_CODE]  DEFAULT ((1)) FOR [STATUS_CODE]
GO

ALTER TABLE [INFOC].[MAPS] ADD  CONSTRAINT [DF_MAPS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[DRIVE_ROUTES](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[RESULT_ID] [bigint] NOT NULL,
	[LON]  [FLOAT] NOT NULL,
	[LAT]  [FLOAT] NOT NULL,
	[ALT]  [FLOAT] NULL,
 CONSTRAINT [PK_DRIVE_ROUTES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[DRIVE_TESTS](
	[ID]        [BIGINT] NOT NULL,
	[RESULT_ID] [bigint] NOT NULL,
	[GSID]      [NVARCHAR](250) NULL,
	[FREQ_MHZ]  [FLOAT] NOT NULL,
	[STANDARD]  [NVARCHAR](50) NULL,
	[POINTS_COUNT] [int] NOT NULL,
 CONSTRAINT [PK_DRIVE_TESTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[DRIVE_TESTS_POINTS](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[DRIVE_TEST_ID] [bigint] NOT NULL,
	[POINTS_ARRAY] [varbinary](max) NOT NULL,
	[POINTS_COUNT] [int] NOT NULL,
 CONSTRAINT [PK_DRIVE_TESTS_POINTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[SM_MEAS_RESULTS](
	[ID] [bigint] NOT NULL,
	[STATUS_CODE] [tinyint] NOT NULL,
	[STATUS_NAME] [nvarchar](50) NOT NULL,
	[STATUS_NOTE] [nvarchar](max) NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[MEAS_TIME] [datetime] NULL,
	[SENSOR_NAME] [nvarchar](150) NULL,
	[SENSOR_TITLE] [nvarchar](250) NULL,
 CONSTRAINT [PK_SM_MEAS_RESULTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [SDRNSVR].[SM_MEAS_RESULTS] ADD  CONSTRAINT [DF_SM_MEAS_RESULTS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[SM_MEAS_RESULTS_STATS](
	[ID] [bigint] NOT NULL,
	[GSID_COUNT] [int] NOT NULL,
	[MIN_FREQ_MHZ] [FLOAT] NULL,
	[MAX_FREQ_MHZ] [FLOAT] NULL,
	[STANDARD_STATS] [varbinary](max) NULL,
 CONSTRAINT [PK_SM_MEAS_RESULTS_STATS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STATIONS].[GLOBAL_IDENTITIES](
	[REGION_CODE] [nvarchar](50) NOT NULL,
	[LICENSE_GSID] [nvarchar](50) NOT NULL,
	[STANDARD] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[REAL_GSID]  [nvarchar](50) NULL,
	
 CONSTRAINT [PK_GLOBAL_IDENTITIES] PRIMARY KEY CLUSTERED 
(
	[REGION_CODE] ASC,
	[LICENSE_GSID] ASC,
	[STANDARD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [STATIONS].[GLOBAL_IDENTITIES] ADD  CONSTRAINT [DF_GLOBAL_IDENTITIES_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO
