SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[CLUTTERS_DESCS_FREQS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CLUTTERS_DESC_ID] [bigint] NOT NULL,
	[FREQ_MHZ] [FLOAT] NOT NULL,
	[NOTE] [nvarchar](max) NULL
 CONSTRAINT [PK_CLUTTERS_DESCS_FREQS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO