SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [INFOC].[MAPS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[STATUS_CODE] [tinyint] NOT NULL,
	[STATUS_NAME] [nvarchar](50) NOT NULL,
	[STATUS_NOTE] [nvarchar](max) NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[TYPE_CODE] [tinyint] NOT NULL,
	[TYPE_NAME] [nvarchar](50) NOT NULL,
	[PROJECTION] [nvarchar](50) NOT NULL,
	[STEP_UNIT] [nvarchar](10) NOT NULL,
	[STEP_DATATYPE] [nvarchar](50) NOT NULL,
	[STEP_DATASIZE] [tinyint] NOT NULL,
	[AXIS_X_NUMBER] [int] NOT NULL,
	[AXIS_X_STEP] [int] NOT NULL,
	[AXIS_Y_NUMBER] [int] NOT NULL,
	[AXIS_Y_STEP] [int] NOT NULL,
	[CRD_UPL_X] [int] NOT NULL,
	[CRD_UPL_Y] [int] NOT NULL,
	[CRD_UPR_X] [int] NOT NULL,
	[CRD_UPR_Y] [int] NOT NULL,
	[CRD_LWL_X] [int] NOT NULL,
	[CRD_LWL_Y] [int] NOT NULL,
	[CRD_LWR_X] [int] NOT NULL,
	[CRD_LWR_Y] [int] NOT NULL,
	[CONTENT_SIZE] [int] NOT NULL,
	[CONTENT_SOURCE] [nvarchar](50) NOT NULL,
	[FILE_NAME] [nvarchar](250) NULL,
	[FILE_SIZE] [int] NULL,
	[MAP_NAME] [nvarchar](450) NOT NULL,
	[MAP_NOTE] [nvarchar](max) NULL,
	[SECTORS_COUNT] [int] NULL,
	[SECTORS_X_COUNT] [int] NULL,
	[SECTORS_Y_COUNT] [int] NULL,
 CONSTRAINT [PK_MAPS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [INFOC].[MAPS] ADD  CONSTRAINT [DF_MAPS_STATUS_CODE]  DEFAULT ((1)) FOR [STATUS_CODE]
GO

ALTER TABLE [INFOC].[MAPS] ADD  CONSTRAINT [DF_MAPS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO

