SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[DRIVE_TESTS_POINTS](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[DRIVE_TEST_ID] [bigint] NOT NULL,
	[POINTS_ARRAY] [varbinary](max) NOT NULL,
	[POINTS_COUNT] [int] NOT NULL,
 CONSTRAINT [PK_DRIVE_TESTS_POINTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

