SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[DRIVE_ROUTES](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[RESULT_ID] [bigint] NOT NULL,
	[LON]  [FLOAT] NOT NULL,
	[LAT]  [FLOAT] NOT NULL,
	[ALT]  [FLOAT] NULL,
 CONSTRAINT [PK_DRIVE_ROUTES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

