SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[DRIVE_TESTS](
	[ID]        [BIGINT] NOT NULL,
	[RESULT_ID] [bigint] NOT NULL,
	[GSID]      [NVARCHAR](250) NULL,
	[FREQ_MHZ]  [FLOAT] NOT NULL,
	[STANDARD]  [NVARCHAR](50) NULL,
	[POINTS_COUNT] [int] NOT NULL,
 CONSTRAINT [PK_DRIVE_TESTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

