SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SDRNSVR].[MEAS_RESULTS](
	[ID] [bigint] NOT NULL,
	[STATUS_CODE] [tinyint] NOT NULL,
	[STATUS_NAME] [nvarchar](50) NOT NULL,
	[STATUS_NOTE] [nvarchar](max) NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[MEAS_TIME] [datetimeoffset](7) NULL,
	[SENSOR_NAME] [nvarchar](150) NULL,
	[SENSOR_TITLE] [nvarchar](250) NULL,
 CONSTRAINT [PK_MEAS_RESULTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [SDRNSVR].[MEAS_RESULTS] ADD  CONSTRAINT [DF_MEAS_RESULTS_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO