SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [STATIONS].[GLOBAL_IDENTITIES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_DATE] [datetimeoffset](7) NOT NULL,
	[LICENSE_GSID] [nvarchar](250) NULL,
	[REAL_GSID]  [nvarchar](250) NULL,
	[REGION_CODE] [nvarchar](50) NULL,
 CONSTRAINT [PK_GLOBAL_IDENTITIES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [STATIONS].[GLOBAL_IDENTITIES] ADD  CONSTRAINT [DF_GLOBAL_IDENTITIES_CREATED_DATE]  DEFAULT (sysdatetimeoffset()) FOR [CREATED_DATE]
GO
