ALTER TABLE [CALC].[CALCRESULTS_STATION_CALIBRATION_STA] ADD  [DELTA_CORRELATION_PC] [REAL]  NULL
GO

ALTER TABLE [CALC].[CALCRESULTS_STATION_CALIBRATION_STA] ADD  [USED_POINTS_PC] [int]  NULL
GO


ALTER TABLE [CALC].[CALCRESULTS_STATION_CALIBRATION_STA] ADD  [COUNT_POINTS_IN_DRIVE_TEST] [int]  NULL
GO

