CREATE TABLE SDRNSVR.MEAS_RESULTS
(
  ID            NUMBER(15)                      NOT NULL,
  STATUS_CODE   NUMBER(3)                       NOT NULL,
  STATUS_NAME   NVARCHAR2(150)                  NOT NULL,
  STATUS_NOTE   NCLOB,
  CREATED_DATE  TIMESTAMP(7) WITH TIME ZONE     DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'GMT' NOT NULL,
  MEAS_TIME     TIMESTAMP(7) WITH TIME ZONE,
  SENSOR_NAME   NVARCHAR2(150),
  SENSOR_TITLE  NVARCHAR2(250)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SDRNSVR.MEAS_RESULTS_PK ON SDRNSVR.MEAS_RESULTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SDRNSVR.MEAS_RESULTS ADD (
  CONSTRAINT MEAS_RESULTS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
