CREATE TABLE SDRNSVR.DRIVE_TESTS
(
  ID            NUMBER(15)                      NOT NULL,
  RESULT_ID     NUMBER(15)                      NOT NULL,
  GSID          NVARCHAR2(50)                   NOT NULL,
  FREQ_MHZ      NUMBER(22,8)                    NOT NULL,
  STANDARD      NVARCHAR2(50),
  POINTS_COUNT  NUMBER(9)                       NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SDRNSVR.MAP_SECTORS_PK ON SDRNSVR.DRIVE_TESTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SDRNSVR.DRIVE_TESTS ADD (
  CONSTRAINT DRIVE_TESTS_PK
 PRIMARY KEY
 (ID));
