CREATE TABLE STATIONS.GLOBAL_IDENTITIES
(
  ID            NUMBER(15)                      NOT NULL,
  REGION_CODE   NVARCHAR2(50)                   NOT NULL,
  LICENSE_GSID  NVARCHAR2(50)                   NOT NULL,
  STANDARD      NVARCHAR2(50)                   NOT NULL,
  CREATED_DATE  TIMESTAMP(7) WITH TIME ZONE     NOT NULL,
  REAL_GSID     NVARCHAR2(50)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX STATIONS.GLOBAL_IDENTITIES_PK ON STATIONS.GLOBAL_IDENTITIES
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE STATIONS.GLOBAL_IDENTITIES ADD (
  CONSTRAINT GLOBAL_IDENTITIES_PK
 PRIMARY KEY
 (ID));
